### ISSUE TITLE
Getting the pid of a long-running process

### ISSUE THREAD

**Issue by lukehorvat** [sindresorhus/execa#10]
I'm using execa to start a process that runs "forever" (a web server). I would like to send a kill signal to the process about 30 seconds after launch, but I don't know how/where to get its process id from execa. Is it possible?

At the moment, execa returns a promise that is only resolved after the process ends, which isn't really useful for indefinitely-running processes. It would be nice if execa returned some additional info along with the promise, like the pid.

**Comment by sindresorhus** [comment]
Yeah, would be useful to attach the `.pid` and `.kill()` to the promise. PR welcome :)
