### ISSUE TITLE
9.0.0 release

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#1028]
This is time! :tada: 

I have created [draft release notes](https://github.com/sindresorhus/execa/releases/tag/untagged-51a43e724ad3242234ed). Could you please review them @sindresorhus? Please feel free to directly edit them. The internal links will not work until the release is done and the release notes are published, but should point to the right version then.

Also, I have created [a release post](https://medium.com/@ehmicky/execa-9-release-d0d5daaa097f). It is currently in draft, but I believe you should be able to leave comments too, thanks!

This issue is primarily intended for @sindresorhus. However, anyone reading this issue is free to check those drafts and comment too. :)

Once reviewed, I can proceed with making the actual release, if that sounds good.

**Comment by sindresorhus** [comment]
> When the [encoding option](https://github.com/sindresorhus/execa/blob/untagged-d2e7baafd39240ac4b15/docs/api.md#optionsencoding) is 'buffer', the output ([result.stdout](https://github.com/sindresorhus/execa/blob/untagged-d2e7baafd39240ac4b15/docs/api.md#resultstdout), [result.stderr](https://github.com/sindresorhus/execa/blob/untagged-d2e7baafd39240ac4b15/docs/api.md#resultstderr), [result.all](https://github.com/sindresorhus/execa/blob/untagged-d2e7baafd39240ac4b15/docs/api.md#resultall)) is now an [Uint8Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array) instead of a [Buffer](https://nodejs.org/api/buffer.html#class-buffer). (by @GODLiangCY) (https://github.com/sindresorhus/execa/pull/586)

Maybe link to https://sindresorhus.com/blog/goodbye-nodejs-buffer for context on why we are doing this.

> The [input](https://github.com/sindresorhus/execa/blob/untagged-d2e7baafd39240ac4b15/docs/api.md#optionsinput) option now accepts an [Uint8Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array) instead of a [Buffer](https://nodejs.org/api/buffer.html#class-buffer). (https://github.com/sindresorhus/execa/commit/834e3726f0c7b7f23827b6e09b69b66dedbddd47)

This is not a breaking change. `Buffer` is a subclass of `Uint8Array`. So it's only a breaking change for return values (since the user may be using Buffer-specific methods).

**Comment by ehmicky** [comment]
> Maybe link to [sindresorhus.com/blog/goodbye-nodejs-buffer](https://sindresorhus.com/blog/goodbye-nodejs-buffer) for context on why we are doing this.

Done. :+1: 

> This is not a breaking change. Buffer is a subclass of Uint8Array. So it's only a breaking change for return values (since the user may be using Buffer-specific methods).

We are currently throwing an error when passing a `Buffer` instead of `Uint8Array`.

https://github.com/sindresorhus/execa/blob/5182195ee8f0ecd32d1c9567c4b49a8954c7afcc/lib/stdio/input-option.js#L28-L32

https://github.com/sindresorhus/execa/blob/5182195ee8f0ecd32d1c9567c4b49a8954c7afcc/lib/utils/uint-array.js#L8

I am submit a PR though if you think we should avoid the breaking change there and accept `Buffer` (although we still document it as `Uint8Array`).

**Comment by sindresorhus** [comment]
> I can submit a PR though if you think we should avoid the breaking change there and accept Buffer (although we still document it as Uint8Array).

Yeah, it doesn't make sense to block `Buffer` as input.

**Comment by ehmicky** [comment]
Done in https://github.com/sindresorhus/execa/pull/1029. I've also updated the release notes accordingly.

If you find anything else, please let me know! The release notes are a good moment to get a high-level overview of all the changes together.

**Comment by ehmicky** [comment]
Should something else be fixed in either the release notes or the release post @sindresorhus?
If not, can I make the major release?

**Comment by sindresorhus** [comment]
I finally had some time to read through it all now. It looks great. Feel free to release.

**Comment by sindresorhus** [comment]
From blog post:

> Although this might seem simple at first sight, it is surprisingly hard to get right.

Without an example how hard it is to do without Execa, I don't think the user will realize how much simpler Execa makes it.

**Comment by ehmicky** [comment]
> Without an example how hard it is to do without Execa, I don't think the user will realize how much simpler Execa makes it.

Fixed it by adding a link to your line splitting implementation.

Execa 9.0.0 is now published! :tada: 

I also published the release post: https://medium.com/@ehmicky/execa-9-release-d0d5daaa097f.

**Comment by mattfysh** [comment]
what happened to the `const $$ = $({ cwd: '/my/dir' })` pattern?

**Comment by ehmicky** [comment]
It has been kept as is, which is why it is mentioned in the release notes. :)

However, now you can also use that pattern with other Execa methods, not only `$`.
