### ISSUE TITLE
stylelint execution never finishes

### ISSUE THREAD

**Issue by patrickhousley** [sindresorhus/execa#103]
Config:
```
"lint-staged": {
    "src/**/*.ts": [
      "prettier --parser typescript --single-quote --write",
      "tslint --type-check --project tsconfig.json",
      "jest --findRelatedTests",
      "git add"
    ],
    "src/**/*.scss": [
      "stylefmt",
      "stylelint --syntax scss --allow-empty-input",
      "git add"
    ],
    "src/**/*.css": [
      "stylefmt",
      "stylelint --allow-empty-input",
      "git add"
    ]
  }
```

The scss styelint never finishes. I believe it is because I am passing in options to `stylelint` and `lint-staged` appends those with the files to be linted. However, `stylelint` expects the file name or blob to be the second argument before any flags.

**Comment by patrickhousley** [comment]
I can confirm that if I remove the flags to `stylelint`, it runs fine.

**Comment by SamVerschueren** [comment]
What does this have to do with execa? It looks like an issue with lint-staged.

**Comment by patrickhousley** [comment]
Ah hell sorry, I forgot I pulled this repo up to look at the source code since lint-staged was using it.
