### ISSUE TITLE
breaking changes not included in v9 release notes

### ISSUE THREAD

**Issue by Zamiell** [sindresorhus/execa#1048]
Hello, and thanks for the library.
In execa version 9, it no longer exports some types that I was depending on:

![image](https://github.com/sindresorhus/execa/assets/5511220/adfd1b36-8459-4062-8139-626a8282e324)

Can you advise how to use them now? And also can we document/add those breaking changes to the release notes for 9.0?

**Comment by ehmicky** [comment]
Hi @Zamiell,

The type changes are included in the [release notes](https://github.com/sindresorhus/execa/releases/tag/v9.0.0) under the "Types (breaking changes)" section. You might also be interested in the new [TypeScript documentation](docs/typescript.md) section.

The `ExecaReturnBase` was renamed to `Result`.

For `Execa$`, you can use `typeof $`:

```ts
import {$} from 'execa';

type Execa$ = typeof $;
```

The types `Execa$` and `TemplateExpression`  were [not previous exported](https://github.com/sindresorhus/execa/blob/f4b8b3ab601c94d1503f1010822952758dcc6350/index.d.ts#L773). However, the `TemplateExpression` sounds quite useful, so I opened a PR at https://github.com/sindresorhus/execa/pull/1049 to export it.

**Comment by Zamiell** [comment]
Ah, I see. I looked under the section called "breaking changes" and didn't see it. It is pretty confusing that there is both a "breaking changes" section and a "types (breaking changes)" section. Maybe they should be combined? Or maybe rename the "breaking changes" section to "breaking changes (not types)", with a link to the other section?

**Comment by ehmicky** [comment]
Good point. I fixed the release notes. :+1:

**Comment by Zamiell** [comment]
Thank you. Can you release the new version so that I can use `TemplateExpression`?

**Comment by ehmicky** [comment]
Released in [`9.1.0`](https://github.com/sindresorhus/execa/releases/tag/v9.1.0).
