### ISSUE TITLE
v9.1.0 possible bug

### ISSUE THREAD

**Issue by dh049** [sindresorhus/execa#1064]
when updating execa to v9.1.0, i get this error: 
`SyntaxError: The requested module 'node:events' does not provide an export named 'addAbortListener'`

any ideas? all my files at .ts extention with esmodule import/export syntax.

**Comment by ehmicky** [comment]
Hi @dh049,

Thanks for reaching out.

The `9.0.0` major release increased the minimum Node.js version to `18.19.0`. This error message seems to indicate you might be using an older version. Is that correct?

**Comment by dh049** [comment]
v20.0.0

**Comment by ehmicky** [comment]
The `9.0.0` major release also dropped support for Node `20.0.0 - 20.4.0`. Could you please try with Node `20.5.0` and see if this works?

**Comment by dh049** [comment]
that did it. thanks.
