### ISSUE TITLE
template syntax

### ISSUE THREAD

**Issue by dh049** [sindresorhus/execa#1065]
i cannot for the life of me get the template syntax to work at all. any ideas? my error is: 
`The "file" argument must be of type string. Received an instance of Array`

**Comment by ehmicky** [comment]
Hi @dh049,

Can you please provide us with an example?

**Comment by dh049** [comment]
i just discovered that template syntax is only workong for the $ method in v8.0.1 since i cannot get v9.1.0 to work currently. node is version 20. so i think this issue might be able to be closed. sorry.
