### ISSUE TITLE
backup-file-in-package

### ISSUE THREAD

**Issue by SimonSiefke** [sindresorhus/execa#1072]
In execa v9 there are backup files, for example `specific.js~`:

![backup-file-in-package](https://github.com/sindresorhus/execa/assets/23744935/f89a6b0d-b089-41b2-b54c-22d222bdc849)

Perhaps the files are there accidentally and could be removed since it seems they are not needed.

**Comment by ehmicky** [comment]
Hi @SimonSiefke,

Thanks a lot for finding this problem and taking the time to reporting it! :pray: 

I have opened a PR at #1074 to fix this.

**Comment by ehmicky** [comment]
This was released in [`9.2.0`](https://github.com/sindresorhus/execa/releases/tag/v9.2.0).
