### ISSUE TITLE
Cannot set properties of null (setting 'peer') 

### ISSUE THREAD

**Issue by seahindeniz** [sindresorhus/execa#1073]
Hello, I have an open issue on `semantic-release/npm` repo, and I was wondering if it is somehow related to this library as an upstream issue. It has some details about the flow and the output of the issue. Could you please take a look?
https://github.com/semantic-release/npm/issues/807

**Comment by ehmicky** [comment]
Hi @seahindeniz,

Thanks for reporting this. However,  this bug does not seem to be coming from Execa. `semantic-release/npm` uses Execa to run commands, but it's the command that's failing, not Execa itself.

Searching GitHub, it seems like this specific bug might be coming from npm itself: https://github.com/search?q=%22Cannot+set+properties+of+null+%28setting+%27peer%27%29%22&type=issues
