### ISSUE TITLE
9.2.0 release post

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#1078]
I have written [a post](https://medium.com/@ehmicky/ipc-made-easy-with-execa-9-2-939c6a358731) for the 9.2.0 upcoming release.

It is currently in draft mode. If you find any problem or anything I should change, please let me know!

**Comment by sindresorhus** [comment]
Generally looks good. Just a few typos:

- "provides with a simple" should be "provides a simple".
- "provides with simpler" should be "provides simpler".
- Missing semicolon after break in if (message === 10) { break }.
- "95% of the times" should be "95% of the time".
- "nor parse anything" should be "or parse anything".

**Comment by ehmicky** [comment]
Thanks @sindresorhus!

Writing those articles is fun.
