### ISSUE TITLE
execa with env option not working

### ISSUE THREAD

**Issue by golddydev** [sindresorhus/execa#1081]
```typescript
const res = await execa({
  lines: true,
  env: {
    NAME: "Hello",
  },
})`echo $NAME`;
console.log({ result: res });
```

the result is 

```typescript
{
  result: {
    command: 'echo $NAME',
    escapedCommand: "echo '$NAME'",
    cwd: '/',
    durationMs: 14.312079,
    failed: false,
    timedOut: false,
    isCanceled: false,
    isTerminated: false,
    isMaxBuffer: false,
    exitCode: 0,
    stdout: [ '$NAME' ],
    stderr: [],
    stdio: [ undefined, [Array], [] ],
    pipedFrom: []
  }
}
```

What is wrong with it?

**Comment by ehmicky** [comment]
Hi @golddydev,

The dollar notation is shell-specific. By default, Execa does not use shells. This is explained [here](https://github.com/sindresorhus/execa/blob/main/docs/bash.md#shell) and [there](https://github.com/sindresorhus/execa/blob/main/docs/bash.md#variable-substitution).

The [following documentation](https://github.com/sindresorhus/execa/blob/main/docs/escaping.md#shells) explains this.

> [Shells](https://github.com/sindresorhus/execa/blob/main/docs/shell.md) ([Bash](https://en.wikipedia.org/wiki/Bash_(Unix_shell)), [cmd.exe](https://en.wikipedia.org/wiki/Cmd.exe), etc.) are not used unless the [shell](https://github.com/sindresorhus/execa/blob/main/docs/api.md#optionsshell) option is set. This means shell-specific syntax has no special meaning and does not need to be escaped:
> - Characters: $variable, &&, ||, ;, |

It's hard to tell you exactly how to fix your example since I am assuming it has been simplified from your use case. Namely, since the value of `$NAME` is already known, you could directly do:

```js
const res = await execa({
  lines: true,
})`echo Hello`;
console.log({ result: res });
```

Now, if you'd like to use an environment variable from the current process, you can do:

```js
const res = await execa({
  lines: true,
})`echo ${process.env.NAME}`;
console.log({ result: res });
```

**Comment by golddydev** [comment]
Thank you for your reply.
With `shell` option set `true`, it works all fine.

By the way, is it not good way to run command with `shell` set `true`?
In terms of performance or security.

**Comment by sindresorhus** [comment]
> By the way, is it not good way to run command with shell set true?
In terms of performance or security.

Correct. You should prefer not using `{shell: true}` whenever possible.

**Comment by golddydev** [comment]
Good to know.
I have one more question.

It worked, 
```typescript
const result = await execa({
  lines: true,
})`echo Hello`;
```
but it is not working
```typescript
const result = await execa({
  lines: true,
})`${"echo Hello"}`;
```

**Comment by ehmicky** [comment]
The [following documentation](https://github.com/sindresorhus/execa/blob/main/docs/execution.md) explains in more details how the template string syntax works. And [this one](https://github.com/sindresorhus/execa/blob/main/docs/escaping.md) how escaping works.

In a nutshell, when you run:

```js
await execa`echo Hello`;
```

Or:

```js
await execa`echo ${"Hello"}`;
```

The file is `echo` and it has one argument `Hello`. So it's like running `echo "Hello"` in the console.

But when you run:

```js
await execa`${"echo Hello"}`;
```

The file is `echo Hello` (including the space in the middle) with no arguments. So it's like running `"echo Hello"` in the console.
