### ISSUE TITLE
Cannot find /bin/sh on android (ENOENT)

### ISSUE THREAD

**Issue by roccomuso** [sindresorhus/execa#109]
I'm using `execa` in [termux](https://github.com/termux) to execute a node project that spawn some processes.
By default execa tries to look for `/bin/sh` but on android (`process.platform === "android"`) the bin path is: `/system/bin/sh`.

The [crossSpawn](https://github.com/IndigoUnited/node-cross-spawn) module handles well android.

On execa I had to manually add the option: `{shell: '/system/bin/sh'}` to make it work and that's weird because crossSpawn is an execa's dependency.

**Comment by kevva** [comment]
That's because you're using the `.shell` method. Did you try using `execa` directly?

**Comment by roccomuso** [comment]
@kevva you're right. Thanks.
