### ISSUE TITLE
Graceful termination

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#1106]
## Problem

There is currently no way to do a graceful termination, i.e. to terminate a subprocess while letting it perform some cleanup logic, in a way that works both on Unix and on Windows.
  - `process.on(signal)` only works for [very specific signals on Windows](https://github.com/ehmicky/cross-platform-node-guide/blob/main/docs/6_networking_ipc/signals.md#cross-platform-signals), and they are only triggered by user interaction with the console, not programmatic `subprocess.kill(signal)`. In other words, our `cancelSignal` option does not allow running any cleanup logic on Windows.
  - `beforeExit` and `exit` handlers are not triggered on signal termination on Windows.

## Solution

We could expose the following API:
  - in the parent process, `abortSignal` option: similar to `cancelSignal` option, but uses IPC messaging under-the-hood instead of signals.
  - in the subprocess, `getAbortSignal()`: to retrieve that signal

```js
// main.js
import {execaNode} from 'execa';

const controller = new AbortController();
setTimeout(() => {
  controller.abort();
}, 1000);
await execaNode('child.js', {abortSignal: controller.signal});
```

```js
// child.js
import {watch} from 'node:fs';
import {getAbortSignal} from 'execa';

const signal = await getAbortSignal();
watch('./src', {signal}, handleFileChange);
```

## Additional details

- The `forceKillAfterDelay` option is used, i.e. by default `SIGKILL` is sent after 5 seconds, in case the subprocess does not exit on its own.
- To pass information to the graceful exit handler, IPC can be used.
- Add `error.isAborted: boolean`.

--- 

What do you think @sindresorhus?

Edit: renamed to `abortSignal`.

**Comment by sindresorhus** [comment]
👍
