### ISSUE TITLE
Document idiomatic ternary interpolation pattern?

### ISSUE THREAD

**Issue by karlhorky** [sindresorhus/execa#1112]
Hey, thanks for execa!

Just wanted to ask whether it's worth documenting this ternary pattern:

```ts
let branch; // potentially undefined

await execa`git clone https://github.com/sindresorhus/execa.git ${
  branch ?
    `--branch ${branch}` :
    [] // Will not add anything to the command string, where an empty string will
}`;
```

I needed this today, and the only place that I could find the `[]` option was the tests:

https://github.com/sindresorhus/execa/blob/a5a4d69aa6f5d9171975d952dd045b49d93ed797/test/methods/template.js#L37

I tried to confirm my suspicion that `''` was causing a problem by inspecting the `escapedCommand`, which does indeed have an extra `''`:

```
> await execa`echo ${''} abc`
{
  command: 'echo  abc',
  escapedCommand: "echo '' abc",
  cwd: '/Users/k/p/preflight',
  durationMs: 5.451958,
  failed: false,
  timedOut: false,
  isCanceled: false,
  isTerminated: false,
  isMaxBuffer: false,
  exitCode: 0,
  stdout: ' abc',
  stderr: '',
  stdio: [ undefined, ' abc', '' ],
  pipedFrom: []
}
```

Using an empty array (`[]`) does not make anything extra show up in the `escapedCommand`:

```
> await execa`echo ${[]} abc`
{
  command: 'echo abc',
  escapedCommand: 'echo abc',
  cwd: '/Users/k/p/preflight',
  durationMs: 11.123583,
  failed: false,
  timedOut: false,
  isCanceled: false,
  isTerminated: false,
  isMaxBuffer: false,
  exitCode: 0,
  stdout: 'abc',
  stderr: '',
  stdio: [ undefined, 'abc', '' ],
  pipedFrom: []
}
```

**Comment by ehmicky** [comment]
You're correct @karlhorky. 

It's nice to see `result.escapedCommand` is helping out, we recently added it to debug specifically that kind of situations.

This situation can happen with other constructs than ternaries, the key difference here being passing `[]` vs `''` inside `${}`.

I have added #1113 to improve the documentation, would you like the check it out?
