### ISSUE TITLE
Accept a string like `execa.shell` but still run it with `spawn`

### ISSUE THREAD

**Issue by borekb** [sindresorhus/execa#112]
From the point of someone writing the code, the easiest way to execute something is to use `execa.shell`:

```js
execa.shell('git log --oneline -10');
```

However, shell can be problematic and the README correctly states _"Prefer `execa()` whenever possible, as it's both faster and safer"_.

So what I end up doing in practice is manually converting the string into a file & an array:

```js
execa('git', ['log', '--oneline', '-10']);
```

This is a boring manual work so I sometimes automate it via [`shell-quote`](https://www.npmjs.com/package/shell-quote):

```js
const args = shellQuote.parse('git log --oneline -10');
execa(args[0], args.slice(1));
```

This feels like it could be supported by the main `execa` function directly, in an ideal case just simply as:

```js
execa('git log --oneline -10');
```

If this were to be more explicit, it could be something like:

```js
execa('git log --oneline -10', { parse: true });
// or
execa.fromString('git log --oneline -10');
```

In either case, it would be a great convenience improvement, IMO. What do you think?

**Comment by sindresorhus** [comment]
I don't think this is a good idea. The whole point of accepting an array is that you're explicit about the argument boundaries. If you use `shell-quote`, you lose the *safe* part of it, and you might be tempted to use template literal interpolation which can also result in a myriad of possible injection vulnerabilities. Also, `shell-quote` is unmaintained and has lots of bugs. I wouldn't want to depend on it even if I thought this was a good idea in general.

**Comment by MartinMuzatko** [comment]
I don't get what is safer and faster about the file/array notation :S

**Comment by borekb** [comment]
@MartinMuzatko Safer is that you're explicit about what arguments are you passing to a program, and faster is that you're calling the program directly. With what I proposed, or with `execa.shell`, another piece of software is involved to decide what the human being possibly meant by that string.

So being explicit is safer and faster, but less convenient to type.

For this feature request to be implemented, there would need to be a rock-solid, well-maintained shell parsing library without any vulnerabilities. If that's even possible because there are many different shells like Bash, zsh, Cmd.exe, PowerShell, etc. So I understand why this issue was closed.

**Comment by abdulhannanali** [comment]
@MartinMuzatko

Moreover, `execa.shell` uses a shell by default (`/bin/sh`) to parse and run the arguments, therefore all what shells like bash could do is available in it, this opens us up to myriad of attacks and injections which means you can literally execute any command you want to, using a syntax like this possibly. `$(rm -rf /)`.

Simply, don't use `execa.shell` with commands having dynamic arguments in them, since this makes you very vulnerable.
