### ISSUE TITLE
Feature request: Possibility to use a custom verbose log format?

### ISSUE THREAD

**Issue by linuswillner** [sindresorhus/execa#1124]
The verbose log function of this library is very handy, as it makes it possible to conveniently log even command runs passed in via template literal. Defining a wrapper function for those is a bit of a faff all said and told.

However, as might be expected, not everyone is using the same log format. That's the case for the project I'm working on, and I'd like the logs to be uniform. Would it be possible to add a way to customize the format used by the `verbose` parameter? I'd be more than happy with just passing in a function somewhere that can take the command that was just run as a parameter, format it however I need to, and return it to execa to be logged.

**Comment by ehmicky** [comment]
Hi @linuswillner,

That makes sense. 

I would suggest the following. Currently, the `verbose` option can be `'none'`, `'short'` or `'full'`. We could allow it to be a function `(verboseEvent) => void` where `verboseEvent` has the following fields:
  - `timestamp` `{Date}`
  - `message` `{string}`: serialized and split line-wise (each `verboseEvent` is a single line)
  - `type` `{string}` among: 
     - `'command'`: when subprocess starts 
     - `'output'`: stdout/stderr output
     - `'ipc'`: IPC message
     - `'error'`: error message
     - `'duration'`: total duration when subprocess ends
  - `failed` `{boolean}`: whether subprocess failed
  - `commandId` `{bigint}`: command identifier, incremented from 0 
  - `pipelineIndex` `{bigint}`: position of the command in the pipeline (0 if no pipeline)
  - `options` `{Options}`: subprocess options. Kept as the user passed them (i.e. before internal normalization).

What are your thoughts on this @sindresorhus?

**Comment by sindresorhus** [comment]
👍 Sounds quite flexible, which would enable multiple use-cases.

**Comment by ehmicky** [comment]
I am currently working on it. :+1:

**Comment by ehmicky** [comment]
PR at #1130.

**Comment by ehmicky** [comment]
This was released in [`9.3.0`](https://github.com/sindresorhus/execa/releases/tag/v9.3.0). 

This is documented [here](https://github.com/sindresorhus/execa/blob/main/docs/debugging.md#custom-logging) and [there](https://github.com/sindresorhus/execa/blob/main/docs/api.md#verbose-function).
