### ISSUE TITLE
stdout/stderr with 'inherit' + transform should not capture output

### ISSUE THREAD

**Issue by bcoughlan** [sindresorhus/execa#1125]
#121 implemented the ability to transform stdout/stderr while using inherit. However the output is captured, like `pipe` mode, which is a source of memory leaks for long running processes.

Example:

```
import { execa } from 'execa';

async function main() {
    await execa({
        stdout: [function* (line) {
            yield `[test] ${line}`;
        }, 'inherit'],
        stderr: [function* (line) {
            yield `[test] ${line}`;
        }, 'inherit'],
    })('sh', ['ls', '-la', '/bad'])
}

main()
```

Expected: thrown error does not contain stdio or stderr properties.

Actual: output includes...

```
  stderr: '[test] /bin/ls: /bin/ls: cannot execute binary file',
  stdio: [
    undefined,
    '',
    '[test] /bin/ls: /bin/ls: cannot execute binary file'
  ],
```

**Comment by ehmicky** [comment]
Hi @bcoughlan,

Thanks for reaching out.

To avoid capturing output, the [`buffer` option](https://github.com/sindresorhus/execa/blob/main/docs/output.md#low-memory) must be set to `false`.

**Comment by bcoughlan** [comment]
Thank you so much, that worked. Apologies for the noise.

**Comment by wtto00** [comment]
Hello, sorry to bother you.

Can I retain the original output text color in the terminal when both `inherit` and `transform` are present?

Or could this become a `feature`?
