### ISSUE TITLE
 Error: Premature close

### ISSUE THREAD

**Issue by FishOrBear** [sindresorhus/execa#1146]
```js
async function run()
{
    const { execa } = await import('execa');
    await execa({
        stdout: {
            file: "out.txt",
        }
    })`npm run tsc`;
}

run();
```

```
        "tsc": "rimraf ./dist/ && tsc --p tsconfig.json"
```

![image](https://github.com/user-attachments/assets/a8dd3d79-074a-43d7-b5fc-77c5aceb4a0f)

**Comment by ehmicky** [comment]
Hi @FishOrBear,

Thanks for reporting this.

The first example is calling `execa()`. But the second one (the one that is an image) is calling `spawn()` instead. How are those examples connected?

**Comment by FishOrBear** [comment]
Hello, this error stack is generated by the above code

**Comment by ehmicky** [comment]
Hi @FishOrBear,

Thanks for reporting this.

Do you get the same error when switching `tsc --p` to `tsc -p`?

**Comment by FishOrBear** [comment]
Thanks for your reply, same error.

**Comment by FishOrBear** [comment]
```
async function run()
{
    const { execa } = await import('execa');
    await execa("npm run tsc").pipeStdout("out.txt");
    console.log(123);
}
```

I used execa@8.0.1 and got no error.

**Comment by ehmicky** [comment]
`execa("npm run tsc")` should not work, but `execa("npm", ["run", "tsc"])` should work.

**Comment by FishOrBear** [comment]
```
async function run()
{
    const { execa } = await import('execa');
    await execa("npm", ["run", "tsc"], {
        stdout: {
            file: "out.txt",
        }
    });
}

run();

```
I tried that and the same editor error stack appears.

**Comment by ehmicky** [comment]
Thanks. Ok, what do you get with the following?

```js
import { execa } from 'execa';

await execa({stdout: {file: "out.txt"}})`npm run tsc`;
```

**Comment by FishOrBear** [comment]
```
        {
            "name": "run cur ts",
            "type": "node",
            "request": "launch",
            "args": [
                "${relativeFile}"
            ],
            "runtimeArgs": [
                "--nolazy",
                "-r",
                "ts-node/register/transpile-only",
            ],
            "cwd": "${workspaceFolder}",
            "internalConsoleOptions": "openOnSessionStart"
        },

```
I currently use ts-node and cjs to run typescript code.
The code above is esm. I'm afraid I need to configure my project.
Wait for me to configure it.

**Comment by FishOrBear** [comment]
![image](https://github.com/user-attachments/assets/349069d0-3034-4d01-aa31-dc61bde3f242)
![image](https://github.com/user-attachments/assets/69b32c88-4ec7-4ce8-ae78-b446f8f67df8)
Same error

**Comment by ehmicky** [comment]
Do you only get this error in VSCode, or can you reproduce in a terminal console (that is not inside VSCode)?

**Comment by FishOrBear** [comment]
I get no errors in the console.

**Comment by FishOrBear** [comment]
https://github.com/nodejs/undici/issues/2540

I think this question is similar to this one

**Comment by ehmicky** [comment]
From reading this thread, it appears to be a problem with Node.js streams + VSCode debugger. 

Execa is just here showing the problem because the `stdout.file` option uses a Node.js stream under-the-hood, but it does not seem to be the actual cause of the bug. Unfortunately, this would lead me to suggest to report this to the Node.js repo, or to the VSCode repo. :-/

Just like the people on that other thread, I cannot reproduce locally in VSCode, so there might be something additional about your VSCode setup (and the other users who were having the same problem in that thread).

To unblock you though, there might some workarounds. If the problem is indeed stream-related, you might want to try whether using something different that the `stdout.file` option would work. For example (even though it's less efficient), would the following work?

```js
async function run()
{
    const { execa } = await import('execa');
    const {writeFile} = await import('fs/promises');

    const {stdout} = await execa`npm run tsc`; 
    await writeFile('./out.txt', stdout);
}

run();
```

**Comment by FishOrBear** [comment]
ok I create a repo
https://github.com/FishOrBear/execa_vscode_debug

https://github.com/user-attachments/assets/35c9a940-d51f-4b45-bc58-27cd2a232a0c

**Comment by FishOrBear** [comment]
> ```js
> import {execa} from 'execa';
> import {writeFile} from 'fs/promises';
> 
> const {stdout} = await execa`npm run tsc`; 
> await writeFile('./out.txt', stdout);
> ```

Both ways of writing give the same error.. Strange.

**Comment by FishOrBear** [comment]
I will use 8.0.1 first, this version is fine

**Comment by ehmicky** [comment]
> Both ways of writing give the same error.. Strange.

Do you get the error without the `writeFile()` line of code?

**Comment by FishOrBear** [comment]
![image](https://github.com/user-attachments/assets/c666b131-a7dd-4ff4-896a-1a84fb22409a)
![image](https://github.com/user-attachments/assets/f41179d9-fdde-49e5-934d-0b9d1266ba97)

**Comment by FishOrBear** [comment]
https://github.com/hashicorp/setup-terraform/pull/125
https://github.com/hashicorp/setup-terraform/issues/328

I found this, is it related?

**Comment by ehmicky** [comment]
> Did you check this?

Yes.

> I found this, is it related?

This is not related.

---

Is there a way to trigger this problem outside of VSCode? If not, this is a problem with VSCode unfortunately, and there is not much we'll be able to do here. :/

**Comment by FishOrBear** [comment]
After updating from nodejs20.6 to nodejs22, the problem was solved

**Comment by ehmicky** [comment]
Node 22 did include a few bug fixes related to streams, so this must have been the problem. Thanks for sharing the solution!
