### ISSUE TITLE
Detaching child process from parent fails to execute child

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/execa#115]
We had an issue in Alfy haunting us for a while. Alfred only shows the results when the process exits. In order to detect if a workflow has an update, we spawn a new process which does this for us in the form of [alfred-notifier](https://github.com/SamVerschueren/alfred-notifier).

This is how we did it first

```js
execa('check.js');
```

Then we noticed what was going on and tried to `unref` the child process.

```js
const cp = execa('check.js');
cp.unref();
```

Unfortunately, this is not enough. In order to detach the child process, you must set the `detached` flag to `true` and make sure there is no communication channel between child and parent.

```js
const cp = execa('check.js', {
    detached: true,
    stdio: 'ignore'
});
cp.unref();
```

However, this results in `check.js` not being executed. Using `child_process` directly however, did the trick.

```js
const subProcess = cp.spawn('check.js', [], {
    detached: true,
    stdio: 'ignore'
});
subProcess.unref();
```

-------------------
## How to reproduce

Create two files, `child.js` and `index.js`.

### child.js
```js
#!/usr/bin/env node
'use strict';
const name = process.argv[2];

setTimeout(() => {
	console.log(`Hello World from ${name}`);
}, 3000);

```

### index.js
```js
'use strict';
const path = require('path');
const fs = require('fs');
const cp = require('child_process');
const execa = require('execa');

const outCp = fs.openSync('out-cp.log', 'w');
const outExeca = fs.openSync('out-execa.log', 'w');

// Spawn the child process with `child_process`
const subProcess = cp.spawn(path.join(__dirname, 'child.js'), ['child_process'], {
	detached: true,
	stdio: ['ignore', outCp, outCp]
});
subProcess.unref();

// Spawn the child process with `execa`
const subProcess2 = execa(path.join(__dirname, 'child.js'), ['execa'], {
	detached: true,
	stdio: ['ignore', outExeca, outExeca]
});
subProcess2.unref();
```

Run `node index.js`. The process exits immediately and you will notice that two files are being created, `out-cp.log` and `out-execa.log`. After 3 seconds, the content of `out-cp.log` changes but the file `out-execa.log` keeps being empty.

**Comment by kasselTrankos** [comment]
hi, im using 
node --version ::: v6.12.0
and when run node index.js
give me this error:

> internal/child_process.js:328
>     throw errnoException(err, 'spawn');
>     ^
> 
> Error: spawn EACCES
>     at exports._errnoException (util.js:1020:11)
>     at ChildProcess.spawn (internal/child_process.js:328:11)
>     at Object.exports.spawn (child_process.js:369:9)
>     at Object.<anonymous> (/home/vera/help-man/index.js:11:23)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.runMain (module.js:604:10)
need upgrade my node ?
thanks

**Comment by SamVerschueren** [comment]
Run `chmod +x child.js`

**Comment by SamVerschueren** [comment]
I debugged this issue and found out that when I set `cleanup` to `false`, it works as expected. Probably because we `unref` the child process, causing the child to to think the parent exited and kills itself.

Should we set `cleanup` to `false` when `detached` is set to `true`? Guess it makes sense.
