### ISSUE TITLE
How to stop execa from escaping?

### ISSUE THREAD

**Issue by shash7** [sindresorhus/execa#1151]
I read the entire documentation but coudn't find any reference on disabling escaping.

I have this command `mysqldump -u root db > sql_backup_8_30-2024.sql` that always gets escaped to `mysqldump -u root db '>' sql_backup_8_30-2024.sql`

^Note the single quotes around >.

This is my code:
```js
let c = await $`mysqldump -u root db > ${fileName}`;
```

How can I stop Execa from escaping this string?

**Comment by ehmicky** [comment]
Hi @shash7,

`>` is a shell-specific character. The answer to your question is in the documentation for [escaping](https://github.com/sindresorhus/execa/blob/main/docs/escaping.md#shells). Namely, this should work:

```js
let c = await $({shell: true})`mysqldump -u root db > ${fileName}`;
```

However, the recommended way to do this is to avoid shells (see why in the documentation for [shells](https://github.com/sindresorhus/execa/blob/main/docs/shell.md)). You can do this like this (see the documentation for [file output](https://github.com/sindresorhus/execa/blob/main/docs/output.md#file-output):

```js
let c = await $({stdout: {file: fileName}})`mysqldump -u root db`;
```

If you need to also use `c.stdout` programmatically, you need to do this instead (see the documentation for it [here](https://github.com/sindresorhus/execa/blob/main/docs/output.md#multiple-targets)):

```js
let c = await $({stdout: [{file: fileName}, 'pipe']})`mysqldump -u root db`;
```

**Comment by ehmicky** [comment]
@shash7 Did this solve your problem?

**Comment by xpuu** [comment]
Hi @ehmicky, I'm also having some strange troubles with escaping. When I use:

```javascript
const exe = execa({
	buffer: { stdout: false, stderr: true },
	verbose: { stdout: 'none', stderr: 'full' },
})

// This works ok
// const cmd = exe('mysqldump', ['--defaults-group-suffix=_local', 'institution'])
// $ mysqldump '--defaults-group-suffix=_local' dbname

// This produces an error
// $ mysqldump '--defaults_group_suffix=_local' institution
// mysqldump: [ERROR] unknown variable 'defaults_group_suffix=_local'
const cmd = exe`mysqldump --defaults_group_suffix=_local dbname`
await cmd
```
Strangely enough, both escapedCommand strings seem to be the same. I'm also wondering if it's necessary to escape `--option` to `'--option'` anyway.

**Comment by ehmicky** [comment]
@xpuu This is a separate question, i.e. probably should be a separate issue, but let's continue on this issue.

Could you please share the same example but:
  - Without setting the `buffer` and `verbose` options?
  - Showing the full error object, since it includes many properties useful for debugging

Also, your example seems to include some mistake. For example, it seems like you are passing `institution` as an argument, but Execa is printing `dbname` instead (or vice-versa). 

The following line seems to work fine:

```js
console.log(await execa`echo --defaults_group_suffix=_local dbname`);
```

```js
{
  command: 'echo --defaults_group_suffix=_local dbname',
  escapedCommand: "echo '--defaults_group_suffix=_local' dbname",
  cwd: '/home/me/Desktop',
  durationMs: 9.045676,
  failed: false,
  timedOut: false,
  isCanceled: false,
  isTerminated: false,
  isMaxBuffer: false,
  exitCode: 0,
  stdout: '--defaults_group_suffix=_local dbname',
  stderr: '',
  stdio: [ undefined, '--defaults_group_suffix=_local dbname', '' ],
  pipedFrom: []
}
```

I also double checked [the code](https://github.com/sindresorhus/execa/blob/main/lib/methods/template.js) and dashes are not significant, so there should not be a reason for them to be stripped.

Based on the above, I am leaning towards thinking there is something in your setup that you might be abbreviating in this report?

**Comment by mkicks** [comment]
Sorry @ehmicky, everything is working fine now. My problem was that I confused `--defaults-group-suffix` with `--defaults_group_suffix`. Feel free to delete my comment to avoid any further confusion.

**Comment by ehmicky** [comment]
Yes, I was thinking there might have been a space after that `--` as well.

>  Feel free to delete my comment to avoid any further confusion.

It might be useful for others with a similar problem. But I will close the issue since the original poster's problem might now have been solved.
