### ISSUE TITLE
Documentation markup problem in `execa/docs/api.md`

### ISSUE THREAD

**Issue by rrthomas** [sindresorhus/execa#1152]
In the documentation of `execaSync`, the following appears: "[SyncOptions](typescript.md". Looks like some Markdown went a bit wrong!

Thanks for execa!

**Comment by ehmicky** [comment]
Thanks @rrthomas!

Would you like to submit a PR to fix this?

**Comment by rrthomas** [comment]
Thanks, it doesn't seem worth the setup cost for such a small saving of time.

**Comment by rrthomas** [comment]
Huh, tried doing it online and it was quite quick actually!
