### ISSUE TITLE
How do I fix ERR_PACKAGE_PATH_NOT_EXPORTED ?

### ISSUE THREAD

**Issue by ringo360** [sindresorhus/execa#1159]
## Steps to reproduce

1. Write code in TypeScript+ESM
```ts
import { execa } from 'execa';
async function main() {
    const { stdout } = await execa`echo hello!`;
    console.log(stdout);
}
main()
```

2. Run with `tsx` (`tsx index.ts`)
3. Terminal will output error (see below)

## Log:
```
$ tsx src/index.ts
node:internal/modules/esm/resolve:304
  return new ERR_PACKAGE_PATH_NOT_EXPORTED(
         ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in C:\Users\ringoXD\Documents\GitHub\exec-pj\node_modules\unicorn-magic\package.json
    at exportsNotFound (node:internal/modules/esm/resolve:304:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:594:13)
    at resolveExports (node:internal/modules/cjs/loader:634:36)
    at Module._findPath (node:internal/modules/cjs/loader:724:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1211:27)
    at a._resolveFilename (C:\Users\ringoXD\Documents\GitHub\exec-trigger\node_modules\tsx\dist\cjs\index.cjs:1:1729)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at C:\Users\ringoXD\Documents\GitHub\exec-trigger\node_modules\npm-run-path\index.js:2:1361 {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v20.17.0
error Command failed with exit code 1.
```

**Comment by ehmicky** [comment]
Hi @ringo360,

I cannot reproduce. I get the expected output `hello!`.

Could you please create a GitHub repository that reproduces this?

**Comment by ringo360** [comment]
[Here](https://github.com/ringo360/exec-trigger) is my repo. I am using
* Node `v20.17.0`
* tsx `4.7.1`
* execa `9.4.0`

**Comment by tjx666** [comment]
I can reproduce:

```
tsx v4.19.1
node v18.20.4
execa 9.4.0
module: commonjs
```

**Comment by ntnyq** [comment]
`execa` is a [pure **esm** package](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).

Workarounds:
- Set `"type": "module"` in your `package.json`
- Change `index.ts` to `index.mts`
-  use `const { execa } = await import('execa')`

**Comment by ringo360** [comment]
I am using ESM and still have this problem...

**Comment by ehmicky** [comment]
@ringo360 I downloaded your repository and can reproduce your problem. 

As mentioned by @ntnyq, you need to set `"type": "module"` in your `package.json`. When doing so, the `ERR_PACKAGE_PATH_NOT_EXPORTED` error does not appear anymore.

@tjx666 Same thing with your reproduction repository. I can also reproduce your problem, and setting `"type": "module"` in `package.json` also fixes your problem.

For more information, please see the link posted by @ntnyq: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by ringo360** [comment]
With the modification of the package.json, the code worked fine!
Thanks for fast support and close this issue 🙏

**Comment by eric-gitta-moore** [comment]
actually, just `execa-cjs`
