### ISSUE TITLE
What is the right way to execute string (not template) command with spaces in it?

### ISSUE THREAD

**Issue by ferenc-a** [sindresorhus/execa#1174]
The `execa(command, options)` invocation (where `command` is say, `git status`) works for any command string for me on Windows, but not on macOS. On mac, commands like `git status` throw an exception including `Command failed with ENOENT`.
As I understand now, I'm supposed to call it like so: `execa("git", ["status"])`. Or, looking at the [docs](https://github.com/sindresorhus/execa/blob/main/docs/execution.md), the template option could probably work also: `execa'${command}'` (with backticks, but I couldn't do that here on GitHub for some reason). I could also just split my command string into an array, but that sounds error prone.

What is the recommended approach among these, or is there another better way? I want to keep my commands as single strings if possible, but if that's bad practice, I guess I could adjust to arrays.
Why does my first naive approach work on Windows, but not on mac, is this documented somewhere?

**Comment by ehmicky** [comment]
Hi @ferenc-a,

Please see the [following part](https://github.com/sindresorhus/execa/blob/main/docs/escaping.md#user-defined-input) of the documentation.

However, whenever possible, we recommend doing the arguments splitting explicitly instead, whether through the [array syntax](https://github.com/sindresorhus/execa/blob/main/docs/escaping.md#array-syntax) or the [template string syntax](https://github.com/sindresorhus/execa/blob/main/docs/escaping.md#template-string-syntax).
