### ISSUE TITLE
docker run -it ?

### ISSUE THREAD

**Issue by tony-kerz** [sindresorhus/execa#1179]
i'm enthusiastic about `execa` so far, but still a noob, tried a few patterns to interact with a call to `docker run -it...` but can't seem to land a working syntax, is it possible?

**Comment by ehmicky** [comment]
Hi @tony-kerz,

This question is more related to how to run `docker` than how to run `execa`.
Also, Execa is a programmatic library, it does not have a binary. Therefore, it is run with `node`. So you just need to run Node inside Docker.

**Comment by tony-kerz** [comment]
hi @ehmicky, thanks for the timely response.

i should have been clearer, i'm not trying to call `execa` from within docker, i'm trying to call `docker run -it` from `execa`.

if not familiar, `docker run -it` spins up a container and opens a command prompt inside the container allowing an interactive session via stdin.

here is an example session that i was hoping to emulate via `execa`:

```
local-prompt> docker run -it ubuntu
container-prompt:/# touch foo
container-prompt:/# ls -la foo
-rw-r--r-- 1 root root 0 Dec 10 18:38 foo
container-prompt:/# exit
exit
```

here is one thing i tried:
```
  const process = execa('docker', ['run', '-it', 'ubuntu']);
  process.stdin.write('touch foo');
  process.stdin.write('ls -la foo');
  process.stdin.end();
  const { out, err } = await process;
```

here is the related failed result:
```
local-prompt> npm start

> execa-scratch@1.0.0 start
> node src/index.js

file:///Users/me/git/execa-scratch/node_modules/execa/lib/return/final-error.js:6
	return new ErrorClass(message, options);
	       ^

ExecaError: Command failed with exit code 1: docker run -it ubuntu

the input device is not a TTY
    at getFinalError (file:///Users/me/git/execa-scratch/node_modules/execa/lib/return/final-error.js:6:9)
    at makeError (file:///Users/me/git/execa-scratch/node_modules/execa/lib/return/result.js:108:16)
    at getAsyncResult (file:///Users/me/git/execa-scratch/node_modules/execa/lib/methods/main-async.js:167:4)
    at handlePromise (file:///Users/me/git/execa-scratch/node_modules/execa/lib/methods/main-async.js:150:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/me/git/execa-scratch/src/index.js:29:24 {
  shortMessage: 'Command failed with exit code 1: docker run -it ubuntu',
  command: 'docker run -it ubuntu',
  escapedCommand: 'docker run -it ubuntu',
  cwd: '/Users/me/git/execa-scratch',
  durationMs: 37.564584,
  failed: true,
  timedOut: false,
  isCanceled: false,
  isGracefullyCanceled: false,
  isTerminated: false,
  isMaxBuffer: false,
  isForcefullyTerminated: false,
  exitCode: 1,
  stdout: '',
  stderr: 'the input device is not a TTY',
  stdio: [ undefined, '', 'the input device is not a TTY' ],
  ipcOutput: [],
  pipedFrom: []
}

Node.js v20.18.0

```

**Comment by ehmicky** [comment]
The `-t` option of `docker run` requires `stdin` to be a TTY.
For this to happen, the `stdin: 'inherit'` option must be used. It will only be a TTY if the current process's `stdin` is also a TTY. 
However, when `stdin: 'inherit'` is used, you cannot write to it. 
Both of the above sentences are due to how `node:child_process` works, it is not specific to Execa.

However, what you can do is removing the `-t` option, while still keeping the `-i` option.

```js
await execa({input: `touch foo\nls -la foo\n`})`docker run -i ubuntu`
```

**Comment by tony-kerz** [comment]
santa visits early this year 🎄 🎁  

this works perfectly @ehmicky, u rock, much appreciated!
