### ISSUE TITLE
EPIPE error when piping to ffmpeg

### ISSUE THREAD

**Issue by epicmet** [sindresorhus/execa#1181]
I'm piping the content of a video to a `ffmpeg` command to extract the first frame of the video. The ffmpeg stream closes as soon as it extracts the first frame info, but the writer (the stream piped into the ffmpeg stream) is not done yet. Thus I get an EPIPE error.

```ts
import { pipeline } from "node:stream/promises";
import { createReadStream, createWriteStream } from "node:fs";

import { execa } from "execa";

const transformStream = execa('ffmpeg', [
  '-i', 'pipe:0',             // Read from stdin
  '-vf', `scale=350:-2`,      // Scale to 350px width (-2 maintains aspect ratio)
  '-vframes', '1',            // Extract only the first frame
  '-q:v', '2',                // High quality JPEG (2 is very high, 31 is lowest)
  '-loglevel', 'error',       // Silence the addtional info
  '-f', 'image2',             // Set the output type to JPEG
  '-'                         // Pipe the output to stdout
]).duplex();

await pipeline(
  createReadStream("./example.mp4"),
  transformStream,
  createWriteStream("./output.jpeg"),
);
```

```output.txt
node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^

Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v20.10.0
```

But as I understood from the documentation and the code, for good reasons you ignore the EPIPE error. Am I doing something wrong here? Cause I thought the EPIPE error should be ignore by the package.

p.s.: The `output.jpeg` is extracted correctly.

**Comment by ehmicky** [comment]
Hi @epicmet,

The following should work instead with `ffmpeg`:

```js
await execa('ffmpeg', [
  '-i', './example.mp4',      // Read from input file
  '-vf', `scale=350:-2`,      // Scale to 350px width (-2 maintains aspect ratio)
  '-vframes', '1',            // Extract only the first frame
  '-q:v', '2',                // High quality JPEG (2 is very high, 31 is lowest)
  '-loglevel', 'error',       // Silence the addtional info
  '-f', 'image2',             // Set the output type to JPEG
  '-y', './output.jpeg'       // Pipe the output to a file
]);
```

My assumption is that `ffmpeg` will not load the whole file in memory, but instead progressively stream it internally. So there should not be no need to implement that streaming at the user level with Execa.

**Comment by epicmet** [comment]
Hello again.
Yeah I figured such approach would work, but in my case since I need to construct a Transform stream based on a file type, I wanted to have a duplex stream and pipe it to a write stream instead of telling ffmpeg where to put the output file. And I couldn't find a better option than `ffmpeg + execa` for videos.

I don't know if it's the "right" thing to do but I overcome this issue by checking for EPIPE error myself.
```ts
transformStream.on("error", (err) => {
  if (isErrnoErr(err) && err.code === "EPIPE") {
     // Ignoring EPIPE and resuming stream to avoid blocking the flow elsewhere
     readStream.resume();
   } else {
     reject(err); // this`reject` comes from a promise handler above
   }
});
```

But you're right, guess my use-case is just weird :))

**Comment by ehmicky** [comment]
What's happening is the following. 

Sending `EPIPE` is a standard way for a process to tell its predecessor in a pipeline that it does not need the whole `stdin`. This allows the previous process to terminate (which is the default way `EPIPE` is handled).

For example, when you do:

```sh
cat file.txt | head -n2
```

`head` is sending `EPIPE` to `cat` after reading two lines.

The same thing is happening here with `ffmpeg` and its `-vframes` option. After reading the first frame, it sends an `EPIPE`. Handling that `EPIPE` and ignoring it is the proper solution here. So the code you're suggesting above is correct.
