### ISSUE TITLE
update to use cross-spawn v7.0.5 or higher 

### ISSUE THREAD

**Issue by MajdT51** [sindresorhus/execa#1183]
Hello,

the used cross-spawn version v7.0.3 has a high vulnerability https://security.snyk.io/package/npm/cross-spawn. Could you please update to v7.0.5 or higher

Thanks

**Comment by ehmicky** [comment]
Hi @MajdT51,

This is a duplicate of #1172, #1171, #1170, #1180 and #1182.

See https://github.com/sindresorhus/execa/pull/1172#issuecomment-2484424731
