### ISSUE TITLE
Returned stdout only contains a snippet of the actual command output

### ISSUE THREAD

**Issue by pmuens** [sindresorhus/execa#119]
Hey there 👋
First of all: Great project and thanks for creating this :+1:

In my code I try to access logs of a Docker container like this:

```javascript
const containerId = '50m3C0nta1n3r1d'
execa('docker', [ 'logs', containerId ]).stdout.pipe(process.stdout)
```

The problem is that I only get a small snippet of the actual logs.

The output from the command above ☝️ looks like this:

```
added 693 packages in 19.107s

> @proj/client@0.1.0 build /usr/src/app
> ./scripts/build
```

The interesting part is that I get the pretty much the same output deterministically even if I run the `docker logs` command on different containers.

BTW: Piping the `stdout` stream into a `fs.createWriteStream` produces the same behavior.

Am I missing something obvious? What am I doing wrong?

*Aside*: I cannot use the `LogPath` returned via `docker inspect` since I run the Docker daemon on macOS where Docker runs in a VM.

**Comment by sindresorhus** [comment]
The other logs are probably printed to `stderr`.

**Comment by pmuens** [comment]
D'oh 🤦‍♂️ 

What a rookie mistake. You're completely right. Thanks for helping out @sindresorhus 👍

Closing...
