### ISSUE TITLE
`input` option

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/execa#12]
[`child_process.execFileSync`](https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback) already have this. Would be useful to have it for the async methods too.

You can already do it with `child.stdin.write(stdin)`, but for tests especially, it would be convenient to specify it upfront.

Right now I'm doing this: https://github.com/sindresorhus/strip-indent-cli/blob/4998c5a41810e7316b1765b490f12f73fc4e4f39/test.js#L10

This would be so much nicer:

```js
await execa('./cli.js', {input: '  foo\\n  bar', cwd: __dirname});
```

-

// @kevva @SamVerschueren

**Comment by kevva** [comment]
I don't know if you can do this cleanly with `execFile` since `stdio` is only available to `.spawn`.

**Comment by sindresorhus** [comment]
@kevva That doesn't matter I think. We can just execFile, take the child and in the same tick `child.stdin.write()`.
