### ISSUE TITLE
executing any execa command prevents Electron apps to be quitted with Ctrl+C from terminal

### ISSUE THREAD

**Issue by astoilkov** [sindresorhus/execa#122]
There are two requirements for Electron apps to stop quitting propertly from the terminal:
1. `window.onbeforeunload = function () {}` - providing any function for onbeforeunload event
2. `require('execa')('ls');` - executing any execa function

I know this is probably something a little off topic regarding execa but there should be a reason for it to happen. This issue may be a sign of some other more serious bug.

I have uploaded a project that reproduces the problem.

[electron-barebone.zip](https://github.com/sindresorhus/execa/files/1634457/electron-barebone.zip)

**Comment by sindresorhus** [comment]
Does it keep `node` alive too? Otherwise, it's probably an Electron issue.

**Comment by astoilkov** [comment]
Yes. It keeps `node` alive too. You could test it in the uploaded project.

**Comment by astoilkov** [comment]
@sindresorhus If I specify the option `detached: true` then it starts working.

**Comment by sindresorhus** [comment]
I can't reproduce with either Electron 1.7 or 1.8 on macOS.

I would be happy to look into it further if you submit a pull request with a [failing test](https://github.com/avajs/ava#failing-tests) for Node.js, but I think it's rather a bug in Electron.

**Comment by astoilkov** [comment]
I am not sure I understand the problem enough to create a test. I will use `detached: true` in our project to fix the problem. I reported the problem to help out `execa` but as you say the problem may not be inside of it.

Closing this issue then.
