### ISSUE TITLE
Running a node script inside multiple ZSH interactive shells make execa freeze

### ISSUE THREAD

**Issue by fabiospampinato** [sindresorhus/execa#123]
I've stumbled upon what seems to be an oddly specific bug. I have the following executable `file.js`:

```javascript
const execa = require ( 'execa' );
async function main () {
  await execa.shell ( '$(which zsh) -ic "node -e \'console.log(\\"foo\\")\'"' );
  console.log ( 'After foo' );
  await execa.shell ( '$(which zsh) -ic "node -e \'console.log(\\"bar\\")\'"' );
  console.log ( 'After bar' );
}
main ();
```

I execute it with `node ./path/to/file.js` and it freezes after printing `After foo`.

This is why this is odd:

- It's not reproducible if the shells are not interactive (`-i` flag), but I use this so that ZSH loads my oh-my-zsh configuration.
- It's not reproducible if the command to execute is a plain `echo foo`, even though the shells are still interactive.
- It's the second `execa.shell` call that makes the whole thing freeze, if I comment it out everything works.
- If I append a ` && exit` to the command I'm passing to ZSH everything works.

Am I doing something wrong here?

**Comment by sindresorhus** [comment]
Yes, this is how shells work, I think. I've encountered this before too. I'm pretty sure this is not an `execa` bug. See if you can reproduce it with plain `child_process.exec()`.

**Comment by sindresorhus** [comment]
Generally, you should never use `.shell()` unless you really have too. Usually much better to use `execa()` which spawns the binary directly.

**Comment by fabiospampinato** [comment]
> See if you can reproduce it with plain child_process.exec().

Yeah, same thing.

I'm closing this then.

Thanks for the help, and for your many other packages I use everyday! ❤️
