### ISSUE TITLE
Explicitly disabling buffering when .then() is used

### ISSUE THREAD

**Issue by also** [sindresorhus/execa#127]
execa's promise based interface is really useful, especially when used with async/await.

However, because calling `.then()` on the child enables buffering of the child's output, it isn't practical to use the promise-based API while also using the output streams.

It would be nice to be able to use the output streams while also taking advantage of the promise API. #84 suggested an explicit option like `{buffer: false}` *or* the current behavior of enabling buffering when `.then()` is called. I think it would be useful to support both, where `{buffer: false}` will disable buffering even if `.then()` is called.

This works fine, and creates a 20mb file:
```js
function test() {
  const child = execa('dd', ['if=/dev/zero', 'count=20480', 'bs=1024']);
  child.stdout.pipe(fs.createWriteStream('zeros'));
}
```

This throws `Error: stdout maxBuffer exceeded`, because `.then()` enables buffering:
```js
async function test() {
  const child = execa('dd', ['if=/dev/zero', 'count=20480', 'bs=1024']);
  child.stdout.pipe(fs.createWriteStream('zeros'));
  await child;
}
```

**Proposed solution: this should create a 20mb file without filling a buffer:**

```js
async function test() {
  const child = execa('dd', ['if=/dev/zero', 'count=20480', 'bs=1024'], {buffer: false});
  child.stdout.pipe(fs.createWriteStream('zeros'));
  await child;
}
```

**Comment by also** [comment]
Without an option, buffering can be prevented by deleting the stream from the child object:

```js
async function test() {
  const child = execa('dd', ['if=/dev/zero', 'count=20480', 'bs=1024']);
  child.stdout.pipe(fs.createWriteStream('zeros'));
  // if child.stdout is set, execa will buffer it
  delete child.stdout;
  await child;
}
```

**Comment by sindresorhus** [comment]
Makes total sense. Thanks for such a succinct issue.
