### ISSUE TITLE
maxBuffer isn't working

### ISSUE THREAD

**Issue by oknoorap** [sindresorhus/execa#130]
I've set maxBuffer as option and it seems not working when buffering large output.

**Comment by kevva** [comment]
Could you share some code?

**Comment by oknoorap** [comment]
it's just add `maxBuffer` option, I set it to `10 * (1024 * 1024)`, but still output is not full and truncated, actually I'm using WordPress coding standards, and I display output in JSON format. I got warning / errors with big JSON string, but it's truncated.

**Comment by milesj** [comment]
I have a similar problem when running Jest with execa. The output is abruptly truncated.

**Comment by sindresorhus** [comment]
`maxBuffer` rejects the promise when exceeding the limit, it doesn’t truncate. Something else is going on. Probably something to do with flushing.

**Comment by sindresorhus** [comment]
What Node.js version are you on? Can you try latest Node.js 8 version and see if the problem is still there?

**Comment by oknoorap** [comment]
I'm using node 9.x.x.

**Comment by oknoorap** [comment]
I have similiar issue with `child_process.spawn`, may be it's node js bug?

**Comment by milesj** [comment]
Yup, I'm on 9.6.1. Maybe this was recently introduced.

**Comment by milesj** [comment]
@oknoorap Have you found a workaround?

**Comment by oknoorap** [comment]
@milesj not yet 😄

**Comment by milesj** [comment]
I created a node issue as this seems to be happening with any child process. https://github.com/nodejs/node/issues/19218

**Comment by oknoorap** [comment]
👍  okay, I'll watch your issue..

**Comment by karlhorky** [comment]
I had this issue as well (also occurred with `child_process.spawnSync()`) and I fixed it by using the `exit` module ([cowboy/node-exit](https://github.com/cowboy/node-exit)) instead of `process.exit()` in my program.

Got a hint from this Jest pull request on that: https://github.com/facebook/jest/pull/5313

**Comment by sindresorhus** [comment]
Closing as this is an issue with Node.js, not Execa.
