### ISSUE TITLE
code `undefined`?

### ISSUE THREAD

**Issue by pablopunk** [sindresorhus/execa#132]
I have a module with the following line

```js
const { code } = shellSync('which ioreg')
```

I rely on that code to be 0, but now my module it's not working as `code is undefined`. The line still works tho, because stdout is still correct:

```js
const { code, stdout, stderr } = shellSync('which ioreg')
// undefined '/usr/sbin/ioreg' ''
````

**Comment by pablopunk** [comment]
```
{ status: 0,
  signal: null,
  output: [ null, '/usr/sbin/ioreg\n', '' ],
  pid: 8637,
  stdout: '/usr/sbin/ioreg',
  stderr: '' }
ReferenceError: code is not defined
    ...trace
```

**Comment by pablopunk** [comment]
@SamVerschueren what's that `status` field? Could that be the code value?

**Comment by SamVerschueren** [comment]
Yes, but I believe it's a bug. I'm going to dive deeper when I find some more time. Or you can debug it yourself to help us out :).

**Comment by pablopunk** [comment]
Okay I found the error. It seems my version of execa was missing [this line](https://github.com/sindresorhus/execa/blob/master/index.js#L338), so maybe the error was introduced in some patch (because I never really changed execa version as it was working fine).

Updating `execa` to latest version worked 🎉 

Thanks!
