### ISSUE TITLE
Child_process error 

### ISSUE THREAD

**Issue by mehdiFiUpm** [sindresorhus/execa#134]
ERROR in ./node_modules/execa/index.js
Module not found: Error: Can't resolve 'child_process' in '/home/mehdi/Escritorio/universal-cli-starter/node_modules/execa'
ERROR in ./node_modules/execa/node_modules/cross-spawn/index.js
Module not found: Error: Can't resolve 'child_process' in '/home/mehdi/Escritorio/universal-cli-starter/node_modules/execa/node_modules/cross-spawn'
 ANy solutions? please 
NOTE: the child_process library is empty on npmjs.com

**Comment by sindresorhus** [comment]
`child_process` is a Node.js built-in. This is not the place to post this issue. Try posting on the `universal-cli-starter` project instead.
