### ISSUE TITLE
Requiring execa throws leak with jest --detectLeaks because errname

### ISSUE THREAD

**Issue by reggi** [sindresorhus/execa#140]
I have a module that requires `execa` and jest is reporting a memory leak for that module, I tracked it down to `execa` just it being required will throw this flag. 

```
➜  execa git:(master) ✗ jest ./jest-leak --detectLeaks
 FAIL  jest-leak/test.js
  ● Test suite failed to run

    EXPERIMENTAL FEATURE!
    Your test suite is leaking memory. Please ensure all references are cleaned.

    There is a number of things that can leak memory:
      - Async operations that have not finished (e.g. fs.readFile).
      - Timers not properly mocked (e.g. setInterval, setTimeout).
      - Keeping references to the global scope.

      at node_modules/jest/node_modules/jest-cli/build/test_scheduler.js:264:22

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.722s
Ran all test suites matching /.\/jest-leak/i.
```

I made a fork and can so I can reproduce it here with `jest ./jest-leak --detectLeaks`.

https://github.com/reggi/execa

**Comment by sindresorhus** [comment]
Not much I can do from the limited amount of information the Jest leaks feature provides. It's also marked as "experimental", so it could easily just be a bug in their implementation.

Happy to merge a fix or a [failing test](https://github.com/avajs/ava#failing-tests) proving the issue though.

**Comment by reggi** [comment]
I am a little skeptical of this `--detectLeaks` flag it's kind of useless and is complaining about all sorts of benign things. I am running node 10.4.0 Will close and reopen if I can track down viable issue.
