### ISSUE TITLE
Spawning a child process on Windows is really slow, takes minutes to complete

### ISSUE THREAD

**Issue by AndyOGo** [sindresorhus/execa#142]
I experience a really weird massive delay on windows by running `npm` or `git` as a child process.
Compared to my running it on MacOS, windows takes ages to complete 🤔 

These are my test scripts:

```js
const execa = require('execa');

execa('npm', ['whoami']).then(({stdout}) => {
  console.log(stdout);
}).catch(reason => {
  console.error(reason);
})
```

```js
const execa = require('execa');

execa('git', ['status']).then(({stdout}) => {
  console.log(stdout);
}).catch(reason => {
  console.error(reason);
})
```

# Timing those calls:

The first call is significantly slower than the second call (that's maybe due to JIT).
**But** the difference between MacOS and Windows is tremendous:

|Run|MacOS|Windows|
|---|---|---|
|1 `npm whoami`|`1289.505351 ms` = `1.2895 sec`|`189807.887698 ms` = `189.8079 sec` = `3.1635 min`|
|2 `git status`|`15.803947 ms` (x`81.59387974409178` times faster)|`201.531065 ms` (x`941.82942812315312` times faster)|

**test script:**
```js
const execa = require('execa');

const precise = require('precise');
const timer = precise();

timer.start();
execa('npm', ['whoami']).then(({stdout}) => {
  timer.stop();
  console.log('Message received in', timer.diff() / 1000000, 'ms');
  console.log(stdout);
}).catch(reason => {
  timer.stop();
  console.log('Message received in', timer.diff() / 1000000, 'ms');
  console.error(reason);
}).then(() => {
  const timer2 = precise();
  timer2.start();
  execa('git', ['status']).then(({stdout}) => {
    timer2.stop();
    console.log('Message received in', timer2.diff() / 1000000, 'ms');
    console.log(stdout);
  }).catch(reason => {
    timer2.stop();
    console.log('Message received in', timer2.diff() / 1000000, 'ms');
    console.error(reason);
  })
})
```

**Windows 10:**
```sh
C:\eplatform\git-repos\patterns-library>npm run test-child-spawn

> @axa-ch/patterns-library@2.0.1-beta.160 test-child-spawn C:\eplatform\git-repos\patterns-library
> node ./stack/tasks/test-child-spawn.js

Message received in 189807.887698 ms
user-name
Message received in 201.531065 ms
On branch bugfix/windows-spawn-hangs
Your branch is up-to-date with 'origin/bugfix/windows-spawn-hangs'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   package.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .idea/
        patterns-library.iml

no changes added to commit (use "git add" and/or "git commit -a")
```

**Mac OSX El Capitan Version 10.11.6:**
```sh
npm run test-child-spawn

> @axa-ch/patterns-library@2.0.1-beta.160 test-child-spawn /Users/axawinterthur/dev/axa-ch_style-html-guide
> node ./stack/tasks/test-child-spawn.js

Message received in 1289.505351 ms
andyogo
Message received in 15.803947 ms
On branch bugfix/windows-spawn-hangs
Your branch is up-to-date with 'github/bugfix/windows-spawn-hangs'.
nothing to commit, working tree clean
```

**Comment by SamVerschueren** [comment]
Can your try running it with Node.js child_process instead of execa? It might have nothing to do with execa itself.

**Comment by AndyOGo** [comment]
@SamVerschueren 
Thanks for your quick answer.
Sure, IMHO I think it will be a bug in node, though we just started to setup basic tests and run them on windows and Mac, to see the measured difference. Will post the results asap.

**Comment by AndyOGo** [comment]
@SamVerschueren 
I shared our test results with using `execa`.
Next we will write a plain `child_process` test, will keep you updated.

**Comment by AndyOGo** [comment]
# Test run with native `child_process.execFile`

|Run|MacOS|Windows|
|---|---|---|
|1 `npm whoami`|`1256.060359 ms` = `1.256 sec`|`189807.887698 ms` = `189.8079 sec` = `3.1635 min`|
|2 `git status`|`16.693848 ms` (x`75.24091264039304` times faster)|`201.531065 ms` (x`941.82942812315312` times faster)|

**test script:**
```js
const { execFile } = require('child_process');
const precise = require('precise');
const timer = precise();

// Node does not support PATHEXT on Windows
const npmCmd = process.platform === 'win32' ? 'npm.cmd' : 'npm';

timer.start();

execFile(npmCmd, ['whoami'], (error, stdout, stderr) => {
  timer.stop();
  console.log('Message received in', timer.diff() / 1000000, 'ms');
  if (error) {
    console.error(error);
  } else {
    console.log(stdout);
  }

  const timer2 = precise();
  timer2.start();

  execFile('git', ['status'], (error, stdout, stderr) => {
    timer2.stop();
    console.log('Message received in', timer2.diff() / 1000000, 'ms');
    if (error) {
      console.error(error);
    } else {
      console.log(stdout);
    }
  });
});
```

**Windows 10:**
```sh
```

**Mac OSX El Capitan Version 10.11.6:**
```sh
npm run test-child-spawn-nodejs

> @axa-ch/patterns-library@2.0.1-beta.160 test-child-spawn-nodejs /Users/axawinterthur/dev/axa-ch_style-html-guide
> node ./stack/tasks/test-child-spawn-nodejs.js

Message received in 1256.060359 ms
andyogo

Message received in 16.693848 ms
On branch bugfix/windows-spawn-hangs
Your branch is up-to-date with 'github/bugfix/windows-spawn-hangs'.
nothing to commit, working tree clean
```

**Comment by AndyOGo** [comment]
I just created an issue at node's repo:
https://github.com/nodejs/node/issues/21632

**Comment by AndyOGo** [comment]
Issue at npm:
https://github.com/npm/npm/issues/21148

**Comment by sindresorhus** [comment]
Got docs on proxy here: https://github.com/sindresorhus/got#proxies

npm should probably use https://github.com/np-maintain/global-tunnel so all the tools they depend on also use the set proxy info.

**Comment by AndyOGo** [comment]
@sindresorhus 
Thanks for your quick response.

Unfortunately those links do not provide reasonable solutions if a user just wants to use `npm` command from his CLI or have script which runs several in order...

Maybe node should have proxy support by environment variables backed in, though current status is definitly not ideal...

**Comment by sindresorhus** [comment]
> Unfortunately those links do not provide reasonable solutions if a user just wants to use npm commands from his CLI or have a script which runs several in order...

Yes, it does `global-tunnel` fixes proxy for *all* request libs used in the dependency tree. Please take a closer look at it.

> Maybe node should have proxy support by environment variables backed in, though current status is definitly not ideal...

It should, but the core team doesn't seem interested in solving the problem: https://github.com/nodejs/node/issues/8381

**Comment by AndyOGo** [comment]
Thanks a lot, seems you faced this issue several times already...
I will look into it.
