### ISSUE TITLE
start ssh session not working

### ISSUE THREAD

**Issue by geeckmc** [sindresorhus/execa#144]
I'm trying to open ssh session in current tty.
My code is : 
   `execa.shellSync('ssh user@server_ip_address');`
But i get this error : 
   `Error: Command failed: /bin/sh -c ssh user@server_ip_address
Pseudo-terminal will not be allocated because stdin is not a terminal.
stdin: is not a tty`

**Comment by sindresorhus** [comment]
The error is already descriptive:

> Pseudo-terminal will not be allocated because stdin is not a terminal. stdin: is not a tty

When you spawn it's not TTY. You need to either set `{stdio: 'inherit'}` (but then you can't read or modify the contents) or use https://github.com/Microsoft/node-pty

This has nothing to do specifically with `execa`, and the same limitation applies to `child_process` too.
