### ISSUE TITLE
 "Error: Commnad failed" when no return or return nothing in child process 

### ISSUE THREAD

**Issue by mengning** [sindresorhus/execa#145]
"Error: Commnad failed" when no return or return nothing in child process.

for example: ffmpeg.exe
my temporary solution is as below, but it is ugly
https://github.com/mengning/execa/blob/master/index.js#L271

**Comment by sindresorhus** [comment]
Not really clear what you're reporting here. Include some more details:

- Node.js and OS version
- How to reproduce it
- What command you ran

Even better, submit a pull request with a [failing test](https://github.com/avajs/ava#failing-tests).

**Comment by fabriciomendonca** [comment]
I have the same issue when running this code:

```javascript
const { stdout: customPath } = execa.shellSync('git config --get core.hooksPath')
```
The error message is `Command failed: /bin/sh -c git config --get core.hooksPath`

But if I run it on my terminal it doesn't return an error.

Check it here https://repl.it/repls/LowestYummyKeygenerator

OS: High Sierra 10.13.6
Node: 9.11.1

**Comment by mengning** [comment]
I fixed it temporary，pls refer to
https://github.com/mengning/execa/commit/b303d8e9af374bba69b0908680e400ac0763c45b
Hope it helpful


mengning





在2018年09月28 23时03分, "Fabricio Mendonca"<notifications@github.com>写道:



I have the same issue when running this code:

const { stdout:customPath } =execa.shellSync('git config --get core.hooksPath')

The error message is Command failed: /bin/sh -c git config --get core.hooksPath

But if I run it on my terminal it doesn't return an error.

Check it here https://repl.it/repls/LowestYummyKeygenerator

OS: High Sierra 10.13.6
Node: 9.11.1

**Comment by sindresorhus** [comment]
I can reproduce this with `child_process` too:

```
❯ node -p "require('util').promisify(require('child_process').exec)('git config --get core.hooksPath').then(console.log).catch(console.error)"
Promise { <pending> }
{ Error: Command failed: git config --get core.hooksPath

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'git config --get core.hooksPath',
  stdout: '',
  stderr: '' }
```

If you believe this should work differently, open an issue on Node.js: https://github.com/nodejs/node/issues
