### ISSUE TITLE
CHANGELOG is missing

### ISSUE THREAD

**Issue by kachkaev** [sindresorhus/execa#154]
I was upgrading my project dependencies and noticed that execa bumped from 0.10.0 to 1.0.0. This looked like a certain breaking change, so I went to search for a CHANGELOG to then update my code if needed.

I could not find any info on the [releases page](https://github.com/sindresorhus/execa/releases) and a commonly used `CHANGELOG.md` file was also missing. It'd be great if at least one of these things was added to execa so that people were wasting less time trying to figure out whether they can safely bump or not. Even if 1.0 is just a 'marketing' version change as https://github.com/sindresorhus/execa/issues/149 suggests, stating this in the changelog can save hundreds of hours for folks around the world.

Thank you for developing execa! It's a really well crafted lib!

**Comment by sindresorhus** [comment]
Done: https://github.com/sindresorhus/execa/releases/tag/v1.0.0

**Comment by 0x6431346e** [comment]
What is the breaking change between `0.10` and `0.11`?
