### ISSUE TITLE
process.binding no longer supported

### ISSUE THREAD

**Issue by cam-shotter** [sindresorhus/execa#163]
I get the following error when trying to implement the username package:

> index.js:1452 execa/lib/errname: unable to establish process.binding('uv') Error: process.binding is not supported
>     at Object.push../node_modules/process/browser.js.process.binding (browser.js:195)
>     at Object.<anonymous> (errname.js:12)
>     at Object../node_modules/username/node_modules/execa/lib/errname.js (errname.js:40)
>     at __webpack_require__ (bootstrap:782)
>     at fn (bootstrap:150)
>     at Object.<anonymous> (index.js:21)
>     at Object../node_modules/username/node_modules/execa/index.js (index.js:411)
>     at __webpack_require__ (bootstrap:782)
>     at fn (bootstrap:150)
>     at Object.<anonymous> (index.js:5)
>     at Object../node_modules/username/index.js (index.js:62)
>     at __webpack_require__ (bootstrap:782)
>     at fn (bootstrap:150)
>     at Module../src/App.js (App.css?da7c:45)
>     at __webpack_require__ (bootstrap:782)
>     at fn (bootstrap:150)
>     at Module../src/index.js (index.css?02e3:45)
>     at __webpack_require__ (bootstrap:782)
>     at fn (bootstrap:150)
>     at Object.0 (serviceWorker.js:131)
>     at __webpack_require__ (bootstrap:782)
>     at checkDeferredModules (bootstrap:45)
>     at Array.webpackJsonpCallback [as push] (bootstrap:32)
>     at main.chunk.js:1

Looks like node has recently deprecated process.binding('uv') in favour of internalBinding('uv') [(https://github.com/nodejs/node/pull/22163)]

(P.S. this is my first issue submission, please let me know if you need more info.)

**Comment by sindresorhus** [comment]
That's a problem with Webpack and should be opened on the Webpack issue tracker.

Execa only uses `process.binding` for older Node.js versions: https://github.com/sindresorhus/execa/blob/bfc9a4e228b7f865c4cff113fb5c015ebc0e01cc/lib/errname.js#L12
