### ISSUE TITLE
Clarification on errors with empty stdout and stderr

### ISSUE THREAD

**Issue by Norris1z** [sindresorhus/execa#168]
I'm resolving an issue related to a package which depends on this package while i found out that the `handlePromise` function sometimes produces an error in the form ` { code: 1, signal: null, stdout: '', stderr: '' }` i want to know if this is valid or maybe if we will have to add other checks like `if (result.error || result.code !== 0 || result.signal !== null  || !(result.stdout !=='' && result.stderr !==''))` before we create and throw or return an error

**Comment by ehmicky** [comment]
Whether a shell command has output (`stdout` or `stderr`) is not correlated to whether it succeeded or failed. A command can fail silently (or not) with an exit code of `1`. A command can also succeed with some output (or not).

I.e. I think this is not an issue.

**Comment by sindresorhus** [comment]
@ehmicky is correct.
