### ISSUE TITLE
Add option to return ChildProcess without Promise

### ISSUE THREAD

**Issue by kellyselden** [sindresorhus/execa#173]
I'm trying to convert my spawn to execa to get the cleanup feature. My simplified spawn code is:

```js
async function spawnProcess() {
  console.log(await exec('print version'));

  return spawn('a process');
}
```

To get this working with execa, the code is:

```js
async function spawnProcess() {
  console.log(await exec('print version'));

  let ps = execa('a process');

  delete ps.then;
  delete ps.catch;

  return ps;
}
```

Because of the async nature of the function, anyone calling `await spawnProcess()` will now hang using execa without the Promise deletion code. An option to turn off the Promise wrapping would be ideal:

```js
async function spawnProcess() {
  console.log(await exec('print version'));

  return execa('a process', [], {
    usePromise: false
  });
}
```

**Comment by jamestalmage** [comment]
Promise support is literally the first bullet point in our feature list. I doubt we'll remove it, even via options.

The cleanup feature is trivial to implement yourself. The code for it is [here](https://github.com/sindresorhus/execa/blob/2210988371f4bf74c37c35aea8e076f43ddf3957/index.js#L217-L219).

Alternatively, just alter your API so you aren't returning the promise directly:

```js
return {process: ps};
```

That way your function can return before the process finishes, but they still have the promisified interface if they want.

**Comment by ehmicky** [comment]
I agree with @jamestalmage, for the same reasons. 

@sindresorhus should we close this?
