### ISSUE TITLE
Feature Proposal: configure option defaults globally

### ISSUE THREAD

**Issue by glor** [sindresorhus/execa#175]
I hereby propose a global configuration option which sets the default options. I usually set reject to false and am tired of setting the option manually everytime. With this example it would look like this:
```javascript
const execa = require('execa');
execa.config({reject: false});
```

**Comment by jamestalmage** [comment]
Altering global state is generally bad. You don't know which dependency in your graph might be relying on the default behavior.

**Comment by sindresorhus** [comment]
What James said. Not interested in doing this.
