### ISSUE TITLE
[Feature proposal] Improved error messages

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#177]
The current code has [some logic](https://github.com/sindresorhus/execa/blob/master/index.js#L155) aimed at providing better error messages. It would be nice to add the following error messages:
  - `Command timed out after 5 seconds: ...` if `timedOut` is `true`.
  - `Command was killed with SIGTERM` if `signal` is not `null`.
  - `Command failed with exit code 2 (ENOENT)` otherwise.

The values (e.g. `SIGTERM`) in the messages above are for example purpose.

I can provide with a PR if this feature proposal is approved.

**Comment by sindresorhus** [comment]
👍 Good idea. PR welcome.

**Comment by ehmicky** [comment]
Done at #180
