### ISSUE TITLE
[Feature proposal] Distinguishing between error strings and error numbers

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#179]
At the moment `result.code` is either a string like `EACCES`, an integer like `13` or `undefined`.

It would be nice to split this property into two: `code` for the string and `errno` for the integer. 

This would be a breaking change if the name `code` is re-used. Otherwise we can pick another property name.

If this sounds good, I will submit a PR.

**Comment by sindresorhus** [comment]
Ah yeah... I should not have reused `.code` for something different.

I don't want to do a breaking change *just* for this, so I suggest we add a `.exitCode` property. I prefer that over `.errno`. [`.errno` in Node.js](https://nodejs.org/api/errors.html#errors_error_errno) can be both a string and a number.

**Comment by ehmicky** [comment]
Sounds good. 

So `code` is currently either string or integer. Should `exitCode` be string? Which property name should be for integer?

**Comment by sindresorhus** [comment]
`.exitCode` should be an integer. The exit code the process excited with.

**Comment by ehmicky** [comment]
Since `code` can be either a string or an integer, should there a third property that can only be a string?

**Comment by sindresorhus** [comment]
What would it contain? Example?

**Comment by ehmicky** [comment]
For example `code` currently can be either a string (`"EACCESS"`), an integer (`2`) or `undefined`.
`exitCode` will only be an integer (`2`) or `undefined`.
A third property could be only a string (`"EACCESS"`) or `undefined`.

**Comment by sindresorhus** [comment]
> A third property could be only a string ("EACCES") or undefined.

Do you have any use-case for this? You could mostly compare `.code` to something anyway, in which the type doesn't matter.

**Comment by ehmicky** [comment]
The use case would be if a user wants to print the signal name but not number. Some users might consider that more user-friendly. Also signal names are cross-platform, whereas signal numbers aren't.

**Comment by sindresorhus** [comment]
Alright, any suggestion on what to name this string-only property?

**Comment by ehmicky** [comment]
`exitName`?

**Comment by sindresorhus** [comment]
I think it should be `exitCode` for the number, since that's what it's called outside the Node.js ecosystem too. As for the string, maybe `exitCodeName` or `exitCodeId`?

**Comment by ehmicky** [comment]
`code` (integer or string), `exitCode` (integer), `exitCodeName` (string) sounds good, I can open a PR.

Should `code` be marked as deprecated and removed in next major release or not?

**Comment by sindresorhus** [comment]
> code (integer or string), exitCode (integer), exitCodeName (string) sounds good, I can open a PR.

👍 

> Should code be marked as deprecated and removed in next major release or not?

No, I think it should stay, since users are used to it from Node.js core errors.

**Comment by ehmicky** [comment]
PR at #187
