### ISSUE TITLE
`execa` and `execa.sync` have return type mismatches.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/execa#19]
I think it would be better if the following were basically equivalent:

```js
const val = execa.sync(...args);

const val = await execa(...args);
```

This would mean a breaking change to `execa.sync`, using `child.spawnSync` instead, but I think it's worth it to have a more consistent API.

**Comment by sindresorhus** [comment]
👍 Good idea. I'm fine with that.

Turns out `execFileSync` is just a tiny wrapper around `spawnSync` anyways. https://github.com/nodejs/node/blob/983a809456b4e993e4defb818ddee3ca0e03b84d/lib/child_process.js#L481-L497
