### ISSUE TITLE
Avoid execa taking over console

### ISSUE THREAD

**Issue by djpalumbo** [sindresorhus/execa#195]
I'm trying to avoid the need to run `mongod` and `redis-server` as services before starting my Node app and I think `execa` has the potential to make that a reality. But let's say I run the following code:
```js
(async () => {
    await execa.shell('/bin/mongod');
    await execa.shell('/bin/redis-server');
   // etc...
})();
```
When I run this, I never get past `mongod`. It completely takes over my shell and doesn't proceed any further ‒ I've checked this using `stdio: 'inherit'`.

On the other hand, I'm certain it's possible to do something like this because I discovered a package called [`mongodb-prebuilt`](https://www.npmjs.com/package/mongodb-prebuilt), which contains a helper class that gets the job done. However, that package uses child processes as opposed to `execa`. Using that, I can run `mongod` using the helper and move on to the `redis-server` execution. But as before, I can go no further.

I've read through the readme a few times now and attempted various solutions, but I can't seem to find any way to do this, and I haven't found any examples anywhere else. Could you please point me in the right direction?

**Comment by ehmicky** [comment]
Hi @djpalumbo.

You need to use the [`detached` option](https://nodejs.org/api/child_process.html#child_process_options_detached).

Also for performance reasons you might consider using `await Promise.all()` instead of using two `await`. Like this your MongoDB server and your Redis server will initialize in parallel, as opposed to one after another.

**Comment by djpalumbo** [comment]
I probably should have mentioned that the `detached` option was the very first thing I tried and unfortunately it behaves exactly the same as if I did not specify the option at all.

**Comment by ehmicky** [comment]
Please check the rest of my reply as well, this might solve your problem.

**Comment by djpalumbo** [comment]
Are you referring to the `Promise.all()`? It's the exact same case if I run both processes inside a `Promise.all()`. Unless you're suggesting that I execute the rest of my code there as well.

**Comment by djpalumbo** [comment]
Is there a best practice way to handle this type of situation? I'd just like to wait until both processes have started successfully. It seems clear that using `await` isn't going to work here, but on the other hand, running everything without waiting for these two processes to begin seems risky.

**Comment by djpalumbo** [comment]
Another question regarding long term processes such as these: if I wanted to terminate one of these before exiting the parent process, what would be the safest way to do that?

**Comment by ehmicky** [comment]
To terminate a process, you would need to send it a termination signal, e.g. calling `childProcess.kill()`.

For the initial question you need to separate two things:
  - when a process terminates. For long-running processes like servers or databases, this only happens on explicit termination (such as sending termination signals).
  - when a long-running process is ready to handle requests. 

That second one is what you are trying to `await`. However this is process-specific, e.g. MongoDB has its own concept of "readiness" and way to communicate it. `execa` (and Node.js `child_process` in general) can only rely on process termination.

I.e. for your problem you will need to find a way to know when your MongoDB database and Redis database are ready, which is not something related to `execa`.
