### ISSUE TITLE
not stripping newlines for stdout 'data' listeners

### ISSUE THREAD

**Issue by mamachanko** [sindresorhus/execa#202]
Hi. Newlines are being stripped as advertised from stdout when waiting for the promise to resolve. However, when going the other route and listening for `data` on stdout they are not being stripped. That would be great though. 

See here: https://runkit.com/mamachanko/5cab0672d9305c0012832b63

**Comment by mamachanko** [comment]
Hm. Now that I am thinking about it, it makes sense. Those newlines are supposed to be there as they are in the somewhere in the middle of the command's output.

**Comment by ehmicky** [comment]
Yes exactly :)

Don't hesitate to raise other issues though.
