### ISSUE TITLE
function cancel and pipe is invaild

### ISSUE THREAD

**Issue by Sinmere** [sindresorhus/execa#204]
const subprocess = execa('node');
	setTimeout(() => {
		subprocess.cancel();
	}, 1000);
	try {
		await subprocess;
	} catch (error) {
		console.log(subprocess.killed); // true
		console.log(error.isCanceled); // true
	}

**Comment by sindresorhus** [comment]
The `.cancel()` method is not released yet.

**Comment by tommedema** [comment]
Is there a workaround while this is not yet released?
