### ISSUE TITLE
Limit child process RAM

### ISSUE THREAD

**Issue by tommedema** [sindresorhus/execa#205]
I'm spawning a child process that exhibits unpredictable behavior. Sometimes it appears to be affected by a memory leak, consuming all of my server's RAM.

Is it possible to have the child process exit if it consumes more than a configured threshold of RAM?

**Comment by ehmicky** [comment]
I don't Node.js exposes the child process RAM consumption (from the point of the view of parent process). 

I.e. we would need to call some shell utility. [`ps-list`](https://github.com/sindresorhus/ps-list) does that, but it does not show RAM on Windows. Also this would require polling, which is not great.

Please someone correct me if I got this wrong.

So I think you might get better results by posting this on https://github.com/nodejs/node and suggesting it as an enhancement of `child_process` instead. I also think your question is relevant for [other types of resources](https://en.wikipedia.org/wiki/Cgroups) such as CPU, disk I/O or network I/O.

**Comment by tommedema** [comment]
Example of a workaround with `pidusage` if anyone's interested:

```javascript
const maxRAMBytes = 1024 * 1000000
  const subprocess = execa.default(bin, command, {
    timeout,
    stdout: process.stdout,
    stderr: process.stderr
  })

  /**
   * Monitor subprocess' RAM here and exit (.kill) when above threshold.
   *
   * This can be improved in the future with the `.cancel` function.
   * @see https://github.com/sindresorhus/execa/issues/205
   * @see https://github.com/sindresorhus/execa/issues/206
   */
  const ramMonitorInterval = setInterval(ramMonitor, 100)
  async function ramMonitor() {
    const { memory } = await pidusage(subprocess.pid)
    if (memory > maxRAMBytes) {
      subprocess.kill()
      pidusage.clear()
      clearInterval(ramMonitorInterval)
      throw new Error(`Sketchtool RAM exceeded ${maxRAMBytes} bytes`)
    }
  }

  await subprocess
  clearInterval(ramMonitorInterval)
```
