### ISSUE TITLE
Detached does not work

### ISSUE THREAD

**Issue by brandonros** [sindresorhus/execa#207]
1. Spawn child process from parent:

```
const childProcess = execa('sh', ['-c', command], { detached: true, stdio: 'ignore', cleanup: false })
childProcess.unref()
await childProcess
```

2. Kill parent

3. Child dies

What do I have to do in order to not have the child die?

```
$ uname -a
4.4.0-143-generic #169-Ubuntu SMP Thu Feb 7 07:56:38 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
```

```
$ node -v
v10.13.0
```

**Comment by ehmicky** [comment]
Hi @brandonros,

I cannot reproduce this bug. I am using Ubuntu 19.04.

`test.js`:

```js
const execa = require('execa')

const spawnSleep = async function() {
  const command = 'sleep 100'
  const childProcess = execa('sh', ['-c', command], { detached: true, stdio: 'ignore', cleanup: false })
  childProcess.unref()
  await childProcess
}

spawnSleep()
```

Then:

```bash
$ pgrep sleep
$ node test.js
$ pgrep sleep
28606
```

I.e. the child process is indeed still running.

My guess is that your `command` (that you are not specifying, so it's hard to tell) has already exited on its own. Try with `sleep 100` and see what you get.

**Comment by brandonros** [comment]
It was pm2’s killtree option not being the default. My apologies. Thank you for such an awesome package!
