### ISSUE TITLE
[TS] execa should accept an array of strings as its only argument

### ISSUE THREAD

**Issue by aleclarson** [sindresorhus/execa#210]
Missing from here:

https://github.com/sindresorhus/execa/blob/075faf3d6885f8f91eb5945d9c8b2f78ad4f0b59/index.d.ts#L336-L349

**Comment by sindresorhus** [comment]
I don't think that's correct. Can you provide a usage example of that?

**Comment by sindresorhus** [comment]
I just saw https://github.com/palmerhq/tsdx/pull/54/files#r279858685. That's definitely not supported.

**Comment by jaredpalmer** [comment]
I made a mistake. Fixed in 1.5.1
