### ISSUE TITLE
Deprecate `execa.shell()` in favor of `execa(..., { shell: true })`

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#211]
Should we deprecate and/or remove `execa.shell()` in favor of `execa(..., { shell: true })`?

The reason being `shell` is a misused option, which creates problems, so we should not encourage its use by providing a shortcut method.

Some of the issues with the `shell` option:
  1) It is not cross-platform. While it does call `cmd.exe` on Windows and `/bin/sh` on Unix, those shells have different syntaxes. If the command uses shell-specific syntax, it won't be cross-platform. It it does not, `shell` is not needed. 
  2) It is slower, as it interprets the command through a shell interpreter.
  3) It is unsafe as it allows for command injection.
  4) It is often used only to be able to pass command and arguments as a string string. Which is not an issue anymore since #182 

There are some legitimate use cases for the `shell` option, but I believe 99% of the times its usage does not satisfy the following criteria:
  a) `shell` is only useful for shell-specific features not available in JavaScript and Node.js. There are really not many of those.
  b) `shell` is only useful when cross-platform is not a concern.

Note: I can submit a PR if approved.

**Comment by marcotuna** [comment]
Same issue here.

**Comment by sindresorhus** [comment]
👍 Also include your above points in the `shell` option docs and TS type for it.

**Comment by ehmicky** [comment]
Done in #219
