### ISSUE TITLE
Deprecate/remove `execa.stdout()` and `execa.stderr()`

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#220]
`execa.stdout()` and `execa.stderr()` are easy enough to reproduce with destructuring:

```js
const { stdout } = await execa(...)
```

Removing those methods would make the API simpler, and reduce code size.

One potential benefit of `execa.stdout()` and `execa.stderr()` would be to pass `ignore` to the other standard output stream, which would make I/O faster. This is not implemented at the moment. This seems to me that this would be a micro-optimization, and easy enough to emulate by letting users explicitly pass that option.

Should those methods be removed or deprecated? 

If so, I can submit a PR.

**Comment by sindresorhus** [comment]
Yes, let's do it.

**Comment by ehmicky** [comment]
Done at #234
