### ISSUE TITLE
Improve stream error handling

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#228]
When `maxBuffer` is reached, the rejected error has a different shape than usual:

```js
{
	"name": "MaxBufferError",
	"bufferedData": "...",
	"stream": "stdout"
}
```

Shouldn't it have the same shape? For example:

```js
// No `code`, `exitCode`, `exitCodeName`, `signal`
{
	// If available
	stdout,
	stderr, 
	all,

	// This indicates a stream error
	stream: "stdout",
	// This indicates a stream error due to `maxBuffer`
	maxBuffer: true|false,

	failed: true,
	timedOut: false,
	isCanceled: false,
	
	command: "...",
}
```

`stdout`, `stderr` and `all` could either:
  a) be present only if the whole stream finished before the error
  b) show the partially `bufferedData`

The error message could be made more descriptive as well.

I can submit a PR if you think that's a good idea.

**Comment by sindresorhus** [comment]
Yes. Good catch. That's really just an oversight. PR welcome.

> b) show the partially bufferedData

👍 Just make sure to document this behavior in the readme/TS.
