### ISSUE TITLE
Why append the entire contents of stdout on error?

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/execa#23]
It seems just as likely the info needed will be in `stderr`, and it could be a whole bunch of data to print. Also, it gives you no means of extracting the original `error.message` property.

Is this providing any real value? If people want to log it to the console, can't they just:

``` js
console.log(error.message + error.stdout);
```

**Comment by jamestalmage** [comment]
Might it be better to do:

```
Contents Of Original Error Message:
stdout:
  head 1
  head 2
  ...
  tail -2
  tail -1

sterr:
  head 1
  head 2
  ...
  tail -2
  tail -1
```

And have an `error.originalMessage` property.

**Comment by sindresorhus** [comment]
It's to get good error messages when exit code is non-zero. I sometimes got empty errors when the relevant error was printed on stdout. I like your suggestion. Let's go with it.

> Is this providing any real value? If people want to log it to the console, can't they just:

Sure, but when using async function you first have to try/catch it and then read the console.log the properties. That is very interrupting for your flow.

-

With most errors the stdout/stderr output is minimal.

**Comment by kevva** [comment]
Mostly, when spawning native binaries (like I do in imagemin) you'll get the real errors on `stderr` (or in bad cases `stdout`) and `err.message` just contains `spawn ERRCODE` and gives you no valuable info. I have to do like this to circumvent it https://github.com/imagemin/imagemin-gifsicle/blob/067cea4948a6709ad9f39813ed912222e9d5966e/index.js#L32-L33.

**Comment by sindresorhus** [comment]
Closing as it's better to be verbose on failure.
