### ISSUE TITLE
Make shebang behavior more cross-platform

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#236]
Shebangs can be used on Unix whether the `shell` option is `true` or `false`. On Windows, they only work when the `shell` option is `false`, because of the way `node-cross-spawn` is [handling it under the hood](https://github.com/moxystudio/node-cross-spawn/blob/master/lib/parse.js#L38).

Should we allow shebangs regardless of the `shell` option?

**Comment by sindresorhus** [comment]
@ehmicky You don't need to assign me. I get notifications for all new issues.

**Comment by sindresorhus** [comment]
I'm not sure I see the benefit of this. Do you have any specific use-cases in mind? Regardless, if this were to be supported, it should probably be added to `node-cross-spawn` and not here.

**Comment by ehmicky** [comment]
No I was just wondering, we can close this issue.
