### ISSUE TITLE
Better `stdio` option.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/execa#24]
I think the `stdio` array is a pretty poor UI, you have to remember the order of things. I'm constantly pulling up that piece of documentation. Instead, of the three member array, let's just give each one it's own named property:

``` js
execa('./cli.js', [], {
  stdin: someReadableStream,
  stdout: 'pipe',
  stderr: 'inherit'
});
```

**Comment by sindresorhus** [comment]
Hah, I was going to comment this exact thing after seeing the example in #20.

Sounds good. `stdio` should still be possible though, to be able to do `stdio: 'inherit'` without having to define all properties individually.

**Comment by jamestalmage** [comment]
Yep - I would say keep `stdio` fully backward compatible. Still able to use the array, just add convenience shortcuts.
