### ISSUE TITLE
Documentation of the `windowsHide` option

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#242]
The `windowsHide` option is not documented.

We default it to `true`, which is probably a good value 99% of the times. So I am not sure if the lack of documentation is intentional or not. Is it?

**Comment by sindresorhus** [comment]
Intentional. I cannot see any reason to change it. If people need it, they’ll complain, and we can add it then.

**Comment by ehmicky** [comment]
Sounds good.
