### ISSUE TITLE
Separate `child_process` options from `execa` options in the `README`

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#252]
I think we should divide the `Options` section in the `README` in two parts:
  - first the options that are specific to `execa`.
  - then the options that we simply forward to `child_process.spawn()`. We can also add a sentence saying those are the same options as `child_process.spawn()`.

This would help users that are already familiar with `child_process.spawn()` and only want to know which extra options `execa` brings.

We could also fix `index.d.ts` to follow the same division.

If you think that's a good idea, I can submit a PR.

**Comment by sindresorhus** [comment]
Good point. Makes sense. 👍

**Comment by ehmicky** [comment]
Done at #256.
