### ISSUE TITLE
v2 release post and changelog

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#253]
I've created a [Medium article](https://medium.com/@ehmicky/execa-v2-20ffafeedfdf) for the upcoming major release (#191). Feel free to leave private notes on it if you think some sentences should be reworked or something is missing/wrong! It will remain in draft mode until `2.0.0` is published to npm, so please do not promote that link yet.

I'm also working on the changelog that we could include as the GitHub release description. I will update this post as new commits come in. Feel free to comment on it as well. Here it is:

<hr>

Thanks to @GMartigny, @BendingBender, @tomsotte, @ammarbinfaisal, @zokker13, @stroncium, @satyarohith, @bradfordlemley, @coreyfarrell, @brandon93s, @dtinth, @papb for the great features and bug fixes they've contributed!

Please check the [Medium article](https://medium.com/@ehmicky/execa-v2-20ffafeedfdf) about this release!

## Breaking changes

- Drop support for Node.js 6 ([dce22670](https://github.com/sindresorhus/execa/commit/dce226705cab370c828e99cbd6de5439c4c5c60f), #221)
- Remove `execa.shell()` and `execa.shellSync()`. The [`shell` option](https://github.com/sindresorhus/execa#shell) should be used instead. (#219)
- Remove `execa.stdout()` and `execa.stderr()`. [`childProcessResult.stdout`](https://github.com/sindresorhus/execa#stdout) and [`childProcessResult.stderr`](https://github.com/sindresorhus/execa#stderr) should be used instead (#234)
- Remove `error.code` (`number` or `string`) in favor of [`error.exitCode`](https://github.com/sindresorhus/execa#exitcode) (`number`) and [`error.exitCodeName`](https://github.com/sindresorhus/execa#exitcodename) (`string`) (#187, #250)
- Rename `stripeEof` option to [`stripFinalNewline`](https://github.com/sindresorhus/execa#stripfinalnewline) ([f8397ba9](https://github.com/sindresorhus/execa/commit/f8397ba9504b5fbba6cb6275b617fc5da6ced199), [4d0dc88a](https://github.com/sindresorhus/execa/commit/4d0dc88ae9d4870976050c60a53f8fefcfca922c), #238)
- Rename `cmd` (in `childProcessResult` and `error`) to [`command`](https://github.com/sindresorhus/execa#command) (#194)
- Default [`preferLocal` option](https://github.com/sindresorhus/execa#preferlocal) to `false`. If you are executing locally installed binaries, you'll need to manually specify `preferLocal: true` (#314)
- Ensure [`windowsHide` option](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) is always `true`, so that no window pops up on Windows. ([8c886452](https://github.com/sindresorhus/execa/commit/8c886452d4d69c4d020db1561b97335f37e999d7))
- [`error.signal`](https://github.com/sindresorhus/execa#signal) is now `undefined` instead of `null` when no signal was used (#193)
- Set [`error.killed`](https://github.com/sindresorhus/execa#killed) to `false` when child process timed out (#227)
- Make [`error.killed`](https://github.com/sindresorhus/execa#killed) always boolean (not `undefined`) (#229, #248)
- Ensure errors always have the same shape. (#276, #277, #283)
- [`error.stdout`](https://github.com/sindresorhus/execa#stdout) and [`error.stderr`](https://github.com/sindresorhus/execa#stderr) are now an empty string (instead of `null`) when the command failed. (#246)

## Features

- Add TypeScript definition (#188, [f2cb86ff](https://github.com/sindresorhus/execa/commit/f2cb86ff79657e5493f52f4a4b460d20a57fe1c5), [7702b8ef](https://github.com/sindresorhus/execa/commit/7702b8ef3f2f30dd3fbd281ae19a6f69c6ac4f95), [4692dcd4](https://github.com/sindresorhus/execa/commit/4692dcd4cec9097ded284ed6f9a71666bd560564), #251)
- Add [`execa.command()`](https://github.com/sindresorhus/execa#execacommandcommand-options) and [`execa.commandSync()`](https://github.com/sindresorhus/execa#execacommandsynccommand-options). Those are the same as [`execa()`](https://github.com/sindresorhus/execa#execafile-arguments-options) except both file and arguments are specified in a single string. For example, `execa('echo', ['unicorns'])` is the same as `execa.command('echo unicorns')` (#182, #261, #262, #278, #279, #282)
- Retrieve interleaved stdout and stderr with [`childProcess.all`](https://github.com/sindresorhus/execa#all) and [`childProcessResult.all`](https://github.com/sindresorhus/execa#all-1) (#171, #264)
- Add [`execa.node()`](https://github.com/sindresorhus/execa#execanodescriptpath-arguments-options) which (like [`child_process.fork()`](https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options)) allows you to execute a Node.js script as a child process (#200, #297, #299, #302, #303, #305, #306). 
- If [`childProcess.kill()`](https://github.com/sindresorhus/execa#killsignal-options) does not terminate a child process after 5 seconds, force it by sending `SIGKILL`. This can be configured using the [`forceKillAfterTimeout` option](https://github.com/sindresorhus/execa#optionsforcekillaftertimeout). (#208, #272, #273, #280, #284, #285)
- Add [`childProcess.cancel()`](https://github.com/sindresorhus/execa#cancel) and [`error.isCanceled`](https://github.com/sindresorhus/execa#iscanceled) (#189, [f24e7c72](https://github.com/sindresorhus/execa/commit/f24e7c7237de2c06f19903eecf3f04f0785c29d1), #226, #309)
- [`error.stdout`](https://github.com/sindresorhus/execa#stdout), [`error.stderr`](https://github.com/sindresorhus/execa#stderr) and [`error.all`](https://github.com/sindresorhus/execa#all) now contain the data that was sent before the child process exit. (#271) 
- Improve [`error.message`](https://github.com/sindresorhus/execa#childprocessresult) on child process failure (#180, #223, #230, #245, #269)
- Add `.finally()` to the [child process promise](https://github.com/sindresorhus/execa#childprocessresult) (#174, [65139849](https://github.com/sindresorhus/execa/commit/651398491b888bf5a51022aa3859152aacb4f796))
- Increase [`maxBuffer`](https://github.com/sindresorhus/execa#maxbuffer) option default value from `10 MB` to `100 MB` (#286)

## Bug fixes

- Fix [`timeout` option](https://github.com/sindresorhus/execa#timeout) not working as expected (#199)
- Fix [`error.timedOut`](https://github.com/sindresorhus/execa#timedout) not working with `execa.sync()` (#249)
- Fix [`maxBuffer`](https://github.com/sindresorhus/execa#maxbuffer) errors not using the same shape as the other errors (#266)
- Fix [`extendEnd` option](https://github.com/sindresorhus/execa#extendenv) not working with [`shell` option](https://github.com/sindresorhus/execa#shell) (#184)
- Fix [`stripFinalNewline` option](https://github.com/sindresorhus/execa#stripfinalnewline) not applied on error properties (#240)
- Fix `/q` parameter not added when using `cmd` instead of `cmd.exe` (#203)
- Fix uncaught exception when using [`input` option](https://github.com/sindresorhus/execa#input) with a non-executable file (#212, #258)
- Fix errors on child processes waiting for stdout/stderr to complete (#270)
- Fix validating that the [`stdio`](https://github.com/sindresorhus/execa#stdio) option cannot be used together with [`stdin: 0`](https://github.com/sindresorhus/execa#stdin) (#301).

## Documentation

- Improve documentation (#158, #235, #237, #239, #241, #256)

## Design

- Add a logo (#201)

## Tests

- Fix various tests ([f185a0e8](https://github.com/sindresorhus/execa/commit/f185a0e8bee153a67dc92a8477b33a659cc5274c), #185, #215, #216, #224, #218, #225, #231, #233, #247, #300)

## Maintainers

- Add @ehmicky as an additional maintainer.

**Comment by sindresorhus** [comment]
This looks great. Thanks for doing the work. I've added a couple of comment to the Medium draft, but it's already awesome.

> Migrate from AppVeyor to Travis CI for Windows (#167)

This is not really relevant to the user.

**Comment by ehmicky** [comment]
Thanks a lot! When we do the major release, could you please:
  - give me some heads up, so I can publish the Medium article at the same time. I will also promote it on social media (anyone involved in this release will be welcome/encouraged to do so as well!)
  - Copy/paste the CHANGELOG from the first comment (I update it on every new commit) to the Releases notes.

**Comment by sindresorhus** [comment]
@ehmicky Or better yet, you can do the release? ;) (You have publish access) When we're ready, just do [`np`](https://github.com/sindresorhus/np) and then choose `major`.

**Comment by ehmicky** [comment]
Do I have `npm` publish access? If I do, then yes I can do that :+1: 

We still have few items in the milestone though.

**Comment by sindresorhus** [comment]
> Do I have npm publish access?

Yes

**Comment by magicdawn** [comment]
The readme doc has changed but the new version has not been released 😞

**Comment by ehmicky** [comment]
@magicdawn hold on tight, we're working on that next release :)

**Comment by sindresorhus** [comment]
@magicdawn That is how most project on GitHub works. If you want docs for the latest version on npm, you go to the specific Git tag or the npm page.

**Comment by lolipop99** [comment]
> @magicdawn hold on tight, we're working on that next release :)

@ehmicky when will the new version be released。expecting... thx

**Comment by ehmicky** [comment]
@lolipop99 we don't have a deadline (like most open source projects). We have a list of items until the release though: you can follow this [milestone](https://github.com/sindresorhus/execa/milestone/1).

**Comment by magicdawn** [comment]
@sindresorhus 
I get the point. 
But I guess point out the readme is for the next version  like `got` do will be a great help to users.

![image](https://user-images.githubusercontent.com/4067115/59024597-cdb89f00-8884-11e9-9475-fd71bd2881d5.png)

**Comment by sindresorhus** [comment]
@magicdawn No. That's just enabling users to not know how things work. I added it to the Got readme because I knew it was going to come up, but I wish I hadn't. People should learn how GitHub works.

**Comment by ehmicky** [comment]
I agree with @sindresorhus that when I get on a GitHub repository which shows different documentation for different versions, I find it a little confusing. Instead I'm always assuming the documentation is of the latest version.

Now this assumes versions are released fast, which has not been the case for this major release. The problems is that:
  1) we are working on several breaking changes at once (those should be mostly solved now except for #271)
  2) we have few big PRs that have taken some time to review
  3) we have a hard-to-resolve issue at https://github.com/sindresorhus/npm-run-path/pull/5 that's in a deadlock at the moment

**Comment by DavidWells** [comment]
Awesome work on this!

Was trying to use `execa.command` and it wasn't working. Realized I was on v1.0.0 😅whoopsies

Ya'll rock! Excited for release on `npm`

**Comment by tunnckoCore** [comment]
Cool. Sounds like a big one! :tada: 

In the past 2-3 years, I was maintaining `execa-pro`/`@tunnckocore/execa` exactly because of the `.command` thingy and the ability to pass multiple commands as array of strings (meaning they will run in series - [example](https://github.com/tunnckoCoreLabs/execa#exec)), it was just [a thin wrapper around 30 lines](https://github.com/tunnckoCoreLabs/execa/blob/e92f69483d4f8a6334c976d1755ba656ee120a84/src/index.js#L93-L114).

Waiting for that release for sure! :taco:

**Comment by ehmicky** [comment]
@tunnckoCore great to hear! Feel free to checkout our implementation for `execa.command()` (it's only 15 lines of code [here](https://github.com/sindresorhus/execa/blob/master/index.js#L488)) and post an issue/PR if you think there's anything wrong with our current solution!

**Comment by tunnckoCore** [comment]
Yea, I've seen it, it looks like the same thing, I will try it.
I'm jumping around the `npm-run-path` problem now :)

**Comment by sindresorhus** [comment]
There's an alpha version of v2 out now: https://github.com/sindresorhus/execa/releases/tag/v2.0.0-alpha.0

Install it with `npm install execa@next`.

**Comment by tunnckoCore** [comment]
Sweeeet! :taco: :tada: 

Works great for now.

**Comment by ehmicky** [comment]
We just released `2.0.0`. Please check the [Medium article](https://medium.com/@ehmicky/execa-v2-20ffafeedfdf)!
