### ISSUE TITLE
Type definition not published to npm registry

### ISSUE THREAD

**Issue by c0un7-z3r0** [sindresorhus/execa#254]
The [type definition](https://github.com/sindresorhus/execa/blob/master/index.d.ts) is not published to npm yet. 
The [version](https://www.npmjs.com/package/execa/v/1.0.0)  that is published on npm just has a
```
  "files": [
      "index.js",
      "lib"
  ],
```

**Comment by ehmicky** [comment]
Hi @c0un7-z3r0,

We are on our way to do a major release, which includes TypeScript support. See #191 

TypeScript support will be added once this major release is published to npm.
