### ISSUE TITLE
New catchphrase for execa

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#255]
The current catchphrase of execa is: "A better `child_process`"

@sindresorhus suggested that we think if we could find a better catchphrase. I agree that this is not super catchy. 

I'm tagging everyone who has contributed to this project, as you might all have an idea: @SamVerschueren @jamestalmage @kevva @GMartigny @BendingBender @stroncium @coreyfarrell @satyarohith @ammarbinfaisal @tomsotte @bradfordlemley @brandon93s @dtinth @spalger @LinusU @sonicdoe @honzajavorek @also @satazor @addaleax @mickdekkers @acburdine @floatdrop @dignifiedquire @KnisterPeter @migg24 @lukehorvat @strikeentco @ntwb. I hope this does not feel spammy (feel free to unsubscribe to this issue if you think otherwise), I just think every past or present contributor deserves a voice :)

Because what constitutes a good catchphrase or not is very subjective, I think the final decision should be left to @sindresorhus, even if there is no consensus. Including keeping the current catchphrase.

I don't have any ideas yet, but I personally believe catchphrases should be:
  - descriptive. Most developers will just read through a catchphrase during a GitHub search. They need to understand what the project does in half a second.
  - catchy. Potentially making you smile. 
  - positive. Some people (like me) don't react well with negative words or telling developers "they should (not) do something" (like `You don't need ...`).

I also think we should not use the following words:
  - "shell": by default execa does not use any shell interpreter.
  - "console" or "terminal": execa does not need to be triggered via a console or terminal.
  - "Unix": execa works on `cmd.exe`

Please leave your suggestions, and I will update this first comment with them, for easy lookup. 

Please give thumbs up to suggestions (except for yours)!

## Suggestions

0) A better `child_process`
1) `child_process` from the future
2) The next generation `child_process`
3) Elegant EXecution of Child-processes Asynchronously
4) Process execution for humans
5) Command execution for humans
6) Command execution for earthlings
7) Sensible|Resilient [child] process execution|management [for humans] (brackets indicate "optional", pipe indicates "or")

**Comment by ammarbinfaisal** [comment]
How is this _`child_process` from the future_  
or 
 _the next generation `child_process`_

**Comment by GMartigny** [comment]
@ammarbinfaisal that's nice, but not very personalized.

I just though of:
**Elegant EXecution of Child-processes Asynchronously**
It's a bit of a stretch, but I find that making up an acronym could be fun.

**Comment by migg24** [comment]
Process execution for humans.

**Comment by ehmicky** [comment]
Variation on the ones from @ammarbinfaisal and @migg24:
Command execution for earthlings.

**Comment by brandon93s** [comment]
- Sensible process execution
- Sensible child process execution
- Sensible process management
- Sensible child process management
- Resilient process execution
- Resilient child process execution
- Resilient process management
- Resilient child process management
- _{any of the above}..._ for humans

**Comment by ehmicky** [comment]
@sindresorhus what do you think?

So far @migg24 catchphrase got the most upvotes.

**Comment by sindresorhus** [comment]
Alright, let's go with `Process execution for humans.`.

But I think we need a longer description in the readme, above `Why`.

**Comment by ehmicky** [comment]
Done at #291

**Comment by ehmicky** [comment]
Some people seem to have an interesting take on the new catchphrase:
  - https://www.reddit.com/r/javascript/comments/c5a8ep/execa_2_release_process_execution_for_humans/es0sdpd/ (Process execution for humans...uummm...a process to execute humans? Is that like “npm execute —JohnSmith”?)
  - https://www.reddit.com/r/javascript/comments/c5a8ep/execa_2_release_process_execution_for_humans/es0ucvt/ (I'm scared...)
