### ISSUE TITLE
Redirecting stdin/stdout/stderr from/to a file

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#257]
Would the following be a good feature?

```js
execa('echo hello world', {
  // The filenames 'pipe', 'ipc' and 'ignore' are not allowed 
  stdin: 'stdin.txt',
  stdout: 'stdout.txt', 
  stderr: 'stderr.txt', 
})
```

Which would be a shortcut for:

```js
execa('echo hello world', { 
  stdin: fs.createReadStream(path.normalize('stdin.txt')), 
  stdout: fs.createWriteStream(path.normalize('stdout.txt')), 
  stderr: fs.createWriteStream(path.normalize('stderr.txt')), 
})
```

**Comment by sindresorhus** [comment]
Is this really a common use-case? I've never needed this and it's quite simple to do it manually:

```js
const subprocess = execa('echo hello world');

subprocess.stdout.pipe(fs.createWriteStream('stdout.txt'));
```

Can you provide some real-world use-cases?

And how would the `stdin` option work for this?

---

FYI, the `path.normalize` call is moot as all the `fs` methods do that internally too.

**Comment by ehmicky** [comment]
Oh yes you're right about `path.normalize()`.

The use cases would be the same as when you would use `>`, `>>` or `<` in a console, such as:
  - when the output of a command needs to be persisted for later use. For example, a command that performs a database backup.
  - when the output of a command might be useful for debugging purpose, but too verbose to be shown in the console. For example, database logs.
  - a command meant to modify a file, or create a modified version of it. For example, using the Unix command `sort` to alphabetically sort a list of passwords.

This is valid only for commands that lack a `--output` flag, but it does happen.

Other things to consider:
  - this might discourage another possible usage of the `shell` option, where users might use it to use `>`, `>>` or `<`.
  - error messages might be a little better by providing extra context: `Command 'echo hello world' failed: stdout.txt is not writable` instead of only `stdout.txt is not writable`.

However I agree with you that this is already easily done by just doing `fs.createWriteStream('file')` instead of just `'file'`. So the extra logic, tests and documentation efforts might not be worth it. 

We could also just add documentation to the `st*` options on how to use `fs.createWriteStream()` and `fs.createReadStream()`?

**Comment by sindresorhus** [comment]
> An alternative could be just adding documentation to the st* options on how to use fs.createWriteStream() and fs.createReadStream()?

👍 Let's do this.

**Comment by ehmicky** [comment]
Now that I'm thinking about it, it feels a little silly to explain users how to use Node.js.

I'm closing this unless you do think we should add this in the documentation.

**Comment by sindresorhus** [comment]
Well, I think it could be useful as a Tip at the bottom of the readme.

**Comment by ehmicky** [comment]
Done at #292.
