### ISSUE TITLE
Can I fully ignore local installed programs?

### ISSUE THREAD

**Issue by muuvmuuv** [sindresorhus/execa#263]
I see there is an option to prefer global or local installed programs but in my case I need to ignore the local ones completely. 

Why? My program checks the npm package.json engines and tries to find a global installed program if none is found it throws an error to the user that he needs to install it first within the selected engine range.

**Comment by ammarbinfaisal** [comment]
won't changing [cwd](https://github.com/sindresorhus/execa#cwd) work?

**Comment by muuvmuuv** [comment]
No.. but I found out that this was just caused because I run the script via npm scripts so npm adds the bin path to PATH. Just needed to remove it from PATH:

```js
const oldPath = process.env.PATH
if (oldPath) {
  const closestNodeModules = findUp.sync('node_modules', {
    type: 'directory',
  })
  const pathToNodeModules = closestNodeModules
    ? closestNodeModules
    : path.resolve(process.cwd(), 'node_modules')
  const pathToBin = path.resolve(pathToNodeModules, '.bin')
  const binRegex = new RegExp(`:?${escapeRegExp(pathToBin)}:?`, 'i')
  const newPath = oldPath.replace(binRegex, '')
  process.env.PATH = newPath // override $PATH
}
```
