### ISSUE TITLE
Renaming `error.command`

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#265]
Should `error.command` be renamed to `error.file`, `error.script` or `error.program`? For two reasons:
  1) We now have `execa.command()` and having both is a little confusing both in the `README`.
  2) A command is technically an executable file + its arguments.

This applies also to `result.command`.

**Comment by sindresorhus** [comment]
Yes, I would go with `.file`.

**Comment by ehmicky** [comment]
It turns out `error.command` is in fact the file but also its arguments. So it should not be renamed to `.file`.

Since we both got confused, I've added two PRs to make both the code and the `README` clearer: #278 and #279.
