### ISSUE TITLE
Doesn't always return a ChildProcess

### ISSUE THREAD

**Issue by MartinKolarik** [sindresorhus/execa#275]
We get a `childP.on is not a function` error in our logs occasionally with code like this:

```js
let childP = execa(...);
childP.on('message', ...);
```

After checking execa's code, I quickly found [this](https://github.com/sindresorhus/execa/blob/6c0a40036ad602a64b4b50d9bf2638ec57c73fa3/index.js#L230-L233), which changes any synchronously thrown errors to promise rejections.

I guess this was done to make it easier to catch all errors via `.catch()` but it makes it impossible to rely on the returned value and it isn't documented. It's ok if execa extends the error with other properties, but it should be thrown synchronously in this case.

**Comment by ehmicky** [comment]
Yes @MartinKolarik you're correct, we should throw synchronously instead of returning a rejected promise there. I will submit a PR.

**Comment by ehmicky** [comment]
PR at #276.
