### ISSUE TITLE
[Feature idea] Execute current package's binary

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#281]
When `execa` is used in unit tests to test the current package's CLI, it might look like this:

```js
const PATH_TO_BINARY = `${__dirname}/../../bin/index.js`

test('should work', async t => {
  const output = await execa(PATH_TO_BINARY, ['arguments'])
  t.is(output, 'expected value')
})
```

To improve this use case, should we allow the following?

```js
test('should work', async t => {
  const output = await execa('binary-name', ['arguments'])
  t.is(output, 'expected value')
})
```

It could be implemented like this:
  - use [`readPkgUp[.sync]()`](https://github.com/sindresorhus/read-pkg-up). This could be cached.
  - get the `bin` field string or object
  - if the name matches the `file` passed to execa, use the binary path instead

This would be behind a `currentPackage: boolean` option. We could default it either to `false` or `true`.

Advantages:
  - it tests that the `bin` field in `package.json` is valid. This is something that is basically never checked in unit tests, but should.
  - it decouples the binary path from the tests, which allows moving the file without rewriting the tests.

Is this a good idea?

**Comment by revelt** [comment]
I tested the `readPkgUp`, bin is indeed recognised. Idea looks good!

**Comment by sindresorhus** [comment]
I feel like this is outside the scope of `execa`. I've been wanting to make child process assertion library to make it easier to assert certain stuff from child processes, especially for interactive processes. Would be cool to have child process mocking built-in too. I imagine your idea would fit better in such library. I have no time to make it though, so feel free to go with it if you have time.

**Comment by ehmicky** [comment]
If it's as a separate library, I would imagine to be restricted to this use case as:

```js
const path = await getBinPath('binary-name')
```

Like this it could be used outside of `execa` as well. And for `execa` it would be:

```js
import getBinPath from 'get-bin-path'

test('should work', async t => {
  const binPath = await getBinPath('binary-name')
  const output = await execa(binPath, ['arguments'])
  t.is(output, 'expected value')
})
```

**Comment by sindresorhus** [comment]
👍

**Comment by ehmicky** [comment]
Done by #339
