### ISSUE TITLE
Add a promise-getter to spawned child process objects

### ISSUE THREAD

**Issue by callumlocke** [sindresorhus/execa#29]
> *promoted from https://github.com/sindresorhus/execa/issues/6#issuecomment-207827425*

Sometimes you want to use `execa.spawn()` because you need an object representing the child process while it's running, so you can send signals or listen to events. But then you lose the convenience of a promise-based API (i.e. having a thing you can easily `await`, which will collect up the stdout/stderr for you).

Suggest adding a method to spawned child objects. This method would return a promise that resolves when the child process exits.

```js
const child = execa.spawn(...);

// do any necessary manual stuff with events/signals etc
child.on(...);

// await the final outcome
const { stdio, stderr, code } = await child.exited();
```

(I'm not sure about the name `exited` though.)

---

Possible extra feature: the method could take an optional parameter specifying the **expected** exit code, e.g. `.exited(0)`. If the child process exits with any other code, the promise rejects. If no exit code is specified, the promise will always resolve when the child process exits, no matter how.

**Comment by jamestalmage** [comment]
Good News!

We are already on that path (nearly). 

See #27 and #18  

We will actually be deprecating `execa.spawn`, you will just use `execa`.

Those changes will allow for this:

```js
const child = execa(...);

// do any necessary manual stuff with events/signals etc
child.on(...);

// await the final outcome
const { stdio, stderr, code } = await child;
```

Take a look at those PR's, and if there are additional features or information you would like passed to the promise resolution, comment on the open PR or open a new issue.

Thanks!
