### ISSUE TITLE
Make an alpha release for `2.0.0`

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#295]
We are getting closer to releasing `2.0.0`.

I am trying to use the latest commit of `execa`:

```json
"dependencies": {
    "execa": "sindresorhus/execa#be1d70ffafc0d6af62d2a1af723a317e20752842",
}
```

However `npm` seems to have several issues with using commit hashes:
  - some [users](https://github.com/ehmicky/gulp-execa/issues/2) are reporting it makes `npm install` fail
  - it makes `npm audit` [crash](https://npm.community/t/npm-audit-fails-when-installing-dependencies-via-commit-hash/7860)

Releasing `2.0.0-alpha.0` would solve this problem. As a side-effect, it could help us catch some bugs from early adopters before the major release.

**Comment by tunnckoCore** [comment]
Exactly what I came for today. Ship it. :) I'll use the master for now.

**Comment by ehmicky** [comment]
Fixed!
