### ISSUE TITLE
util.getSystemErrorName not available before Node v9.7.0

### ISSUE THREAD

**Issue by noise-machines** [sindresorhus/execa#318]
Hi folks,

Thanks for all the time and hard work you put into this package. I know open source is often thankless, so I want to take a second to say that I really appreciate what you do 😄

Okay, bug report time ‒ while running execa on Node v8.11.1, I ran into this error:
```
TypeError: util.getSystemErrorName is not a function
```

I did a little research and I think this is what's happening:

In error.js, you [make a call to `util.getSystemErrorName`](https://github.com/sindresorhus/execa/blob/master/lib/error.js#L11). According to the [Node docs](https://nodejs.org/api/util.html#util_util_getsystemerrorname_err), this function wasn't added until Node v9.7.0, but the [engines field in your package.json](https://github.com/sindresorhus/execa/blob/master/package.json#L13) specifies any Node version >= 8.

Hope this is clear! Let me know if I can provide more details or help with anything else.

Cheers,
Thomas

**Comment by ehmicky** [comment]
We support `>=8.12.0`.

See [here](https://github.com/sindresorhus/execa/pull/221#issue-276606756) on the discussion related to the `engines` field.

**Comment by noise-machines** [comment]
Okay, perfect. I figured there was something I was missing. (And thanks for the lightning fast response 😂).

Is it worth updating the engines field to indicate that only 8.12 and up are supported?

**Comment by ehmicky** [comment]
I think so (PR at #319) but I am not sure how @sindresorhus feels about this.
