### ISSUE TITLE
Execa fails to handle numeric error codes in Node 8

### ISSUE THREAD

**Issue by Lalem001** [sindresorhus/execa#320]
Per [node's docs](https://nodejs.org/api/util.html#util_util_getsystemerrorname_err), `util.getSystemErrorName` was added in Node 9.7.0.

`util.getSystemErrorName` appears in [Execa's lib/error.js#L11](https://github.com/sindresorhus/execa/blob/4dd258d062722e69317707da5c1b73ffa506d42a/lib/error.js#L10-L12).

I see the following error in Node 8.9.4,

```
TypeError {
  message: 'util.getSystemErrorName is not a function',
}
```

**Comment by sindresorhus** [comment]
You're on an ancient Node.js 8 version. You have to upgrade. There have been a lot of feature and security bug fixes since then.

https://github.com/sindresorhus/execa/pull/319

**Comment by Lalem001** [comment]
I wholeheartedly agree. Your opinion might just be enough to get my company to upgrade 😆 

Thanks for #319

**Comment by ehmicky** [comment]
@Lalem001 `util.getSystemErrorName()` was backported to Node `8.12.0`. I hope you are able to upgrade to that Node version in your company.

We just updated the `engines` field to make our supported Node versions clearer. Thanks for checking out the new release.
