### ISSUE TITLE
'stdio: inherit' option is not working

### ISSUE THREAD

**Issue by Zjaaspoer** [sindresorhus/execa#338]
If i would run:

```js
const execa = require('execa');

(async () => {
  await execa('echo', ['"hello world"'], { stdio: 'inherit' })
})()
```

I would expect the stdout (in this case `hello world`) to appear right? But it doesn't for me.

**Comment by ehmicky** [comment]
Hi @Zjaaspoer, thanks for reporting this.

I copied/pasted the code above (preceded by `const execa = require('execa');` in a `file.js` then:

```bash
$ node file.js
"hello world"
```

So it works for me. There's probably more about your setup that what you described. I suggest:
  - isolating it to a single small file
  - telling us the command that you run in the CLI (e.g. `node file.js`)
  - telling us your environment: Node, OS, execa. For me I run Node `12.4.0`, Ubuntu `19.04`, execa `2.0.0`.

**Comment by Zjaaspoer** [comment]
Thanks for the quick reply.

I followed your steps and indeed that way it worked.

After some debugging it appeared this behaviour only happened when running the node code through the Visual Studio Code debugger.

Any other way the code worked as expected.

So I guess this is a VSCode issue and has nothing to do with this library.

Thanks for the help!

**Comment by ehmicky** [comment]
Just as a side node: arguments with `execa` do not need escaping/quoting (unless you use the `shell` option). So unless you actually do want quotes to be printed on the console, you should do `execa('echo', ['hello world'])` instead of `execa('echo', ['"hello world"'])`.

**Comment by Zjaaspoer** [comment]
Yeah that was actually result of going back and forth between the `shell` option trying to figure out what was going on 😁

But thanks for the useful info!

**Comment by ehmicky** [comment]
We wrote a small description of the cons of using the `shell` option [here](https://codeburst.io/execa-v2-20ffafeedfdf#1025) if you are interested :)
