### ISSUE TITLE
`all` is missing on `ExecaChildProcess`

### ISSUE THREAD

**Issue by novemberborn** [sindresorhus/execa#342]
The `all` combined stream is missing on https://github.com/sindresorhus/execa/blob/c9b4d09cc70f80ed8423bd81fbd2c5849512c3e0/index.d.ts#L310

**Comment by ehmicky** [comment]
Thanks @novemberborn, we missed that one.

PR at #345.

**Comment by ehmicky** [comment]
Fixed and released in [`2.0.3`](https://github.com/sindresorhus/execa/releases/tag/v2.0.3).
