### ISSUE TITLE
The `all` stream and `stderr: 'inherit'`

### ISSUE THREAD

**Issue by novemberborn** [sindresorhus/execa#344]
I'm using `execa` to launch a child process that logs JSON to `stdout`. Each of these lines are parsed and consumed.

I've set `buffer` to `false`. I'm inheriting `stderr` since I do not need to parse it.

I now need to fully consume both `stdout`, which is fair enough, **and** `all`, even though it only contains the data from `stdout` which I've already consumed.

Is there a way of opting *out* of using `all`?

**Comment by ehmicky** [comment]
Would just consuming `stdout` and not consuming `all` be a problem? Is your problem that the `all` stream might take up memory under the hood?

Side question: you need to inherit `stderr`, using `ignore` is not possible, correct? I'm asking because `ignore` would be more efficient.

Note: if by any chance you do not call `result.then()` or `await result`, you do need to use `buffer: false` since buffering is never used then.

**Comment by novemberborn** [comment]
> Side question: you need to inherit `stderr`, using `ignore` is not possible, correct? I'm asking because `ignore` would be more efficient.

I'm using `execa` inside an AVA test process to launch the process I'm testing against. Its log output goes over `stdout` but inheriting `stderr` means I can still use `console.error()` inside the process for debugging purposes.

> Would this work for you if you consumed `stdout` and not `all`? Is your problem that the `all` stream might take up memory under the hood?

I don't care about memory. I think the solution may be to consume `all` instead of `stdout`, since it reads from `stdout` anyway. The stream promises wait for both streams to end, and `all` won't end if you don't read it…

Indeed I have another test which asserts against `stdout` and `stderr`. Awaiting the `ExecaChildProcess` does nothing unless I *also* fully consume the combined `all` stream.

**Comment by ehmicky** [comment]
Thanks for explaining this. Could you please provide with a code example so I can better understand your problem?

> Indeed I have another test which asserts against stdout and stderr. Awaiting the ExecaChildProcess does nothing unless I also fully consume the combined all stream.

Could you provide with a code example reproducing this? This would be a bug.

**Comment by tiagonapoli** [comment]
A workaround is to call `.all.resume()`:
```javascript
const proc = execa("echo", ["hello"], {
  buffer: false
});
proc.stderr.pipe(process.stderr);
proc.stdout.pipe(process.stdout);
proc.all.resume();
```

**Comment by tiagonapoli** [comment]
I think a workaround is to call `.all.resume()`:
```javascript
const proc = execa("echo", ["hello"], {
  buffer: false,
  stderr: "inherit"
});
proc.stdout.pipe(process.stdout);
proc.all.resume();
```

**Comment by ehmicky** [comment]
I am not fully understanding what the original problem of this issue nor the problem this workaround is fixing: @tiagonapoli could you please describe it?

For example taking your example, if I remove the `proc.all.resume()` line, then run the file, `hello` gets correctly printed on `stdout`.

**Comment by tiagonapoli** [comment]
This snippet shows the problem I was experiencing (which was the issue I #350):
```javascript
const execa = require("execa");

const go = async () => {
  try {
    const proc = execa("echo", ["hello"], {
      buffer: false,
      stderr: "inherit"
    });
    proc.stdout.pipe(process.stdout);
    // proc.all.resume();

    const procRes = await proc;
    console.log(procRes);
  } catch (err) {
    console.log("CAUGHT ERROR", err);
  }
  console.log("============= DONE ================");
};

go();
```
The output is correctly piped to `process.stdout`, but the `proc` promise doesn't resolves.

**Comment by ehmicky** [comment]
Great, thanks! That is a problem indeed!

Your example can be reduced to simply:

```js
const execa = require("execa");

(async () => {
  await execa("echo", { buffer: false });
  // This never gets printed
  console.log('Done');
})();
```

**Comment by ehmicky** [comment]
PR at #353.

**Comment by ehmicky** [comment]
This should now be fixed. Also `all` is now an opt-in feature (before the `all` boolean option).

This change will be released in the next major release.

**Comment by novemberborn** [comment]
Thanks for the update @ehmicky. Apologies for not having the time to investigate more deeply. Thanks for fixing this @tiagonapoli!
