### ISSUE TITLE
hide shell

### ISSUE THREAD

**Issue by rynz** [sindresorhus/execa#346]
**Operating System**
Windows 7/8/10

**Question**
When running `execa` with `shell: true` is it possible to optionally hide the `cmd` window?

Cheers!

**Comment by ehmicky** [comment]
Hi @rynz, thanks for reaching out.

I am assuming you are talking about the new window created by `cmd.exe` when spawning a command. This new window should always be hidden with execa because we force [`windowsHide`](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) to be `true`.

Is your problem:
  1) that you would like to see that window?
  2) that you don't want to see that window, but it does appear (which it should not)?

**Comment by rynz** [comment]
Hi @ehmicky, love this project. My problem is number 2.
```
await execa(cmd, args, { shell: true, detached: true })
```
and the new window created by `cmd.exe` appears using `electron`.

**Comment by ehmicky** [comment]
If an additional `cmd.exe` window pops up, this is a bug indeed.

Could you try the following?
  a) Run instead `child_process.spawn(cmd, args, { shell: true, detached: true, windowsHide: true })` and tell us if the window is still popping up. This would help us know if this is an issue with Node.js or Execa.
  b) Run the same code without `electron` (if that's possible). If this bug is Electron-related, this might be harder to reproduce and fix.

**Comment by rynz** [comment]
1. Yes, a window is still popping up.
2. Looks like it is a nodejs bug, this is the code I used to test on node v12.4.0
```
const path = require('path')
const { spawn } = require('child_process')

const run = (args) => {
  return new Promise((resolve) => {
    const cmd = path.resolve(__dirname, 'foo', 'bar.exe')
    const ls = spawn(cmd, args, { shell: true, detached: true, windowsHide: true })
    ls.on('close', () => {
      resolve()
    })
  })
}

run(['--test']).then(() => {
  console.log('Done')
})
```
Note: `bar.exe` runs with UAC, so a UAC prompt appears and after clicking "Yes" the `cmd.exe` window appears.

**Comment by ehmicky** [comment]
I think your code example might be reduced to:

```js
const { spawn } = require('child_process')
spawn('./foo/bar.exe', ['--test'], { shell: true, detached: true, windowsHide: true })
```

Am I correct? Does this still create a window?

Note: this assumes the current directory is the parent directory of `foo/`.

**Comment by rynz** [comment]
```
const { spawn } = require('child_process')
spawn('.\\foo\\bar.exe', ['--test'], { shell: true, detached: true, windowsHide: true })
```
On Windows, yes window still popping up after UAC prompt.

**Comment by ehmicky** [comment]
Does it still pop up after you remove `shell` and/or `detached`?

**Comment by rynz** [comment]
Removing `shell` it no longer pops up, however, I have to run `node test.js` with `cmd.exe` as Administrator due to the UAC. If I run it without Administrator then I get `EACCES` due to UAC not being triggered by the new `shell`.

**Comment by ehmicky** [comment]
To summarize (correct me if I got it wrong):
  - UAC appears if `shell: false` but not if `shell: true`
  - window pops up if `shell: true` but not if `shell: false`

What about `detached`?

**Comment by ehmicky** [comment]
Could this be due to this [Node bug](https://github.com/nodejs/node/issues/21825)?

**Comment by rynz** [comment]
To summarise

- run `cmd.exe` and execute `node test.js` with `shell: true`. UAC prompt appears, then new `cmd.exe` window pops up.
- run `cmd.exe` "Run as administrator" and execute `node test.js` with `shell: true`. UAC prompt no longer appears, then new `cmd.exe` window pops up.
- run `cmd.exe` and execute `node test.js` with `shell: false`. Throws an exception `EACCES` as it does not have privileges to execute `bar.exe`.
- run `cmd.exe` "Run as administrator" and execute `node test.js` with `shell: false`. UAC prompt no longer appears and no new `cmd.exe` window pops up (expected behavior).
- run `cmd.exe` and execute `node test.js` with `shell: true, detached: false`. UAC prompt appears, then new `cmd.exe` window pops up.
- run `cmd.exe` "Run as administrator" and execute `node test.js` with `shell: true, detached: false`. UAC prompt no longer appears and no new `cmd.exe` window pops up (expected behavior).

Therefore, when `detached: false` the new `cmd.exe` window pops up only when UAC prompt appears prior.

**Comment by ehmicky** [comment]
Could this be due to this [Node bug](https://github.com/nodejs/node/issues/21825)?

**Comment by rynz** [comment]
> Could this be due to this [Node bug](https://github.com/nodejs/node/issues/21825)?

Yes, looks related cheers! I'll follow up there. Thanks for taking the time to help! 👍
