### ISSUE TITLE
Arguments in quotes not handled correctly

### ISSUE THREAD

**Issue by agirorn** [sindresorhus/execa#354]
The command [execa.command](https://github.com/sindresorhus/execa#execacommandcommand-options) does not handle arguments in quotes correctly. It splits all strings by space and ignores arguments in quotes.

**What happend**
To test this I have this script
```js
#!/usr/bin/env node
console.log(process.argv);
```
That I run like this and it splits argument 2 *('arg 2')* into 2 arguments.
```js
> command("./test.js arg1 'arg 2'").then(console.log)
Promise { <pending> }
> {
  command: "./test.js arg1 'arg 2'",
  exitCode: 0,
  exitCodeName: 'SUCCESS',
  stdout: '[\n' +
    "  '/home/agirorn/.nvm/versions/node/v12.7.0/bin/node',\n" +
    "  '/home/agirorn/code/pontus/docs/test.js',\n" +
    "  'arg1',\n" +
    `  "'arg",\n` +
    `  "2'"\n` +
    ']',
  stderr: '',
  all: '[\n' +
    "  '/home/agirorn/.nvm/versions/node/v12.7.0/bin/node',\n" +
    "  '/home/agirorn/code/pontus/docs/test.js',\n" +
    "  'arg1',\n" +
    `  "'arg",\n` +
    `  "2'"\n` +
    ']',
  failed: false,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**What I expected**
I expected argument 2 *('arg 2')* not to be split into 2 arguments.
```js
> command("./test.js arg1 'arg 2'").then(console.log)
Promise { <pending> }
> {
  command: "./test.js arg1 'arg 2'",
  exitCode: 0,
  exitCodeName: 'SUCCESS',
  stdout: '[\n' +
    "  '/home/agirorn/.nvm/versions/node/v12.7.0/bin/node',\n" +
    "  '/home/agirorn/code/pontus/docs/test.js',\n" +
    "  'arg1',\n" +
    `  "'arg 2'"\n` +
    ']',
  stderr: '',
  all: '[\n' +
    "  '/home/agirorn/.nvm/versions/node/v12.7.0/bin/node',\n" +
    "  '/home/agirorn/code/pontus/docs/test.js',\n" +
    "  'arg1',\n" +
    `  "'arg 2'"\n` +
    ']',
  failed: false,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

Maybe something similar to [shell-parser](https://www.npmjs.com/package/shell-parser)could be used instead of the ["SPACES_REGEXP" string split](https://github.com/sindresorhus/execa/blob/master/lib/command.js#L31)

**Comment by ehmicky** [comment]
Quoting is shell-specific. `shell-parser` is for Unix only, Windows `cmd.exe` quoting is very different. We don't want to promote non-cross-platform code.

Instead you have three options:
  1) Escape the significant spaces with backslashes: `execa.command("./test.js arg1 arg\\ 2")`
  2) use `execa()` instead of `execa.command()`: `execa('./test.js', ['arg1', 'arg 2'])
  3) use the `shell` option in order to let your current shell handle it. That option has [many drawbacks](https://codeburst.io/execa-v2-20ffafeedfdf#1025) so I would not recommend it though.

**Comment by agirorn** [comment]
Thanks for the fast response to this issue.

**Comment by retueZe** [comment]
> We don't want to promote non-cross-platform code.

> 1. Escape the significant spaces with backslashes: execa.command('./test.js arg1 arg\\ 2')

You contradict yourself. `execa.command('./test.js arg1 arg\\ 2')` does not work in `cmd.exe`. The passed command to the terminal is going to be `./test.js arg1 arg\ 2`. First off, not every Windows NodeJS user makes `*.js` files executable in the *nix-like way. Better to use `node ./test.js arg1 arg\ 2`. Okay, but this code is not cross-platform either. Let's create a 'test.js' file with the following code:

```javascript
console.log(process.argv.slice(2))
```

Then execute the `node ./test.js arg1 arg\ 2` command. The output is going to be:

```plain
[ 'arg1', 'arg\\', '2' ]
```

Yes, it does work in BASH, but not in Batch. The only case where is not desirable to use the 2nd way is when you use `$`, and especially `$$`, where the 1st option is the only one available, and it just doesn't work at all default shells.

What did you mean by that:

> Quoting is shell-specific.

BASH has double-quotes, Batch has double-quotes, PowerShell has double-quotes. The only difference is escaping and variable substitution. The first one is solved by JS' escaping. The second one solved by either using interpolated strings (`$`, for example), or passing arguments by array. But as i said, you get completely stuck by using the `$` (the most laconic and pretty option so far).

So, is double-quoting really some kind of "non-cross-platform code"? Why can't this feature just be implemented? I really see no way to make some bad code out of double-quoting.
