### ISSUE TITLE
Unexpected EPERM

### ISSUE THREAD

**Issue by you-fail-me** [sindresorhus/execa#355]
I've noticed that sometimes I get really confusing `EPERM` errors saying `No such file or directory`. I had different cases, but the simplest to replicate is:

```js
const dir = '/Users/me/whatever';
const sp = await execa('ls', ['*.proto'], {cwd: dir}); // throws the mentioned EPERM
```
which throws:
```
{ Error: Command failed with exit code 1 (EPERM): ls *.proto
    at makeError (.../node_modules/execa/lib/error.js:58:11)
    at handlePromise (.../node_modules/execa/index.js:335:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  command: 'ls *.proto',
  exitCode: 1,
  exitCodeName: 'EPERM',
  stdout: '',
  stderr: 'ls: *.proto: No such file or directory',
  all: 'ls: *.proto: No such file or directory',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined }
```
(path to `node_modules` containing execa obfuscated by me before pasting)

I have a feeling it's just me doing something wrong or some sort of an edge case...

What could be the problem here? What should I try?

Interestingly, doing just
```js
const sp = await execa('ls', {cwd: dir});
```
or
```js
const sp = await execa('ls', [], {cwd: dir});
```
is ok and I get the good output in stdout. Goes without saying that executing the `ls *.proto` command just works without any EPERM if using plain terminal. The directory when I'm trying to run the command is not something special, requiring a permission, moreover, the same command without parameters works.

node v10.16.0 execa 2.0.0

**Comment by ehmicky** [comment]
By default `execa` does not use any shell. Globbing characters such as `*` are interpreted by a shell. Which means by default `execa('ls', ['*.proto'])` is the same as running `ls \*.proto` in a terminal, as opposed to `ls *.proto`. It will look for a name called `*.proto`, which does not exist.

You can fix this by using the [`shell` option](https://github.com/sindresorhus/execa#shell). However relying on a shell is generally a [bad idea](https://codeburst.io/execa-v2-20ffafeedfdf#1025). For your case, you should instead directly use [`fs.readdir()`](https://nodejs.org/api/fs.html#fs_fs_readdir_path_options_callback) or some higher-level library like [`readdirp`](https://github.com/paulmillr/readdirp).

**Comment by you-fail-me** [comment]
Thanks @ehmicky . For this use case with ls, using alternative APIs such as `readdir` would totally work for me.
However, I have another use case - I'm calling a binary and have to pass a globbing character to it in params, e.g.
```
execa('something', ['--param /someDir/*.extension'])
```
What would be the recommendation for such use cases?

**Comment by ehmicky** [comment]
First you should separate arguments like this:

```
execa('something', ['--param', '/someDir/*.extension'])
```

Otherwise you're escaping the space after `--param` instead of using it as a delimiter.

If you want to expand `*.extension` into several parameters passed to `something`, you should do globbing against actual files (as opposed to plain strings), you should use libraries like [`fast-glob`](https://github.com/mrmlnc/fast-glob) (there are many other libraries as well).

Many libraries will do globbing themselves, so you can also directly pass the globbing pattern to them without having to do it yourself.

**Comment by you-fail-me** [comment]
I need to just pass that character intact, as a string, I was getting same error when passing a params like `--param=/someDir/*.extension` (sorry for inaccurate example in previous comment, I do realize the problem with a space there), and it seems to me that the `*` was somehow processed in not the way I want then as well

**Comment by ehmicky** [comment]
If you run `binary --param=/someDir/*.extension`, `*` will be expanded by the shell because you're not escaping it. Depending on whether you want to escape it or not, any of the two solutions I suggested above should work.

**Comment by you-fail-me** [comment]
Ok, so I need to extend myself. Thanks!

**Comment by williscool** [comment]
> First you should separate arguments like this:
> 
> ```
> execa('something', ['--param', '/someDir/*.extension'])
> ```
> 
> Otherwise you're escaping the space after `--param` instead of using it as a delimiter.
> 
> If you want to expand `*.extension` into several parameters passed to `something`, you should do globbing against actual files (as opposed to plain strings), you should use libraries like [`fast-glob`](https://github.com/mrmlnc/fast-glob) (there are many other libraries as well).
> 
> Many libraries (like ESLint, Babel, nyc, etc.) will do globbing themselves, so you can also directly pass the globbing pattern to them without having to do it yourself.

@ehmicky this is a totally understandable design choice and likely the safest default.


But it comes as a surprise to the the uninitiated. 

Was also hard to search for I tried the word star but for the forgot the word glob and got lucky search the issues for "special characters"

Could use a mention in the readme that 

1. this is turned off by default
2. how to safely do it
3. how to unsafe do it if you really want but why its UNSAFE.

I would make a PR myself but have yet to figure out my usecase yet. I will if I have time once I get it working.

trying to do

```
ls -lt tmp/screenshots/*.jpg | awk '{print $9}' | head -n 1
```

with execa

**Comment by ehmicky** [comment]
Hi @williscool,

Thanks for your feedback.

> Could use a mention in the readme that
> - this is turned off by default
> - how to safely do it
> - how to unsafe do it if you really want but why its UNSAFE.

This is currently documented under [Shell syntax](https://github.com/sindresorhus/execa#shell-syntax):

> For all the [methods above](https://github.com/sindresorhus/execa#methods), no shell interpreter (Bash, cmd.exe, etc.) is used unless the [shell option](https://github.com/sindresorhus/execa#shell) is set. This means shell-specific characters and expressions ($variable, &&, ||, ;, |, etc.) have no special meaning and do not need to be escaped.

And the [`shell` option](https://github.com/sindresorhus/execa#shell):

> We recommend against using this option since it is:
> - not cross-platform, encouraging shell-specific syntax.
> - slower, because of the additional shell interpretation.
> - unsafe, potentially allowing command injection.
