### ISSUE TITLE
Update social preview with the Execa logo

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#356]
On GitHub the preview thumbnail shown in social media defaults to the repository's owner's profile picture. This [can be changed](https://help.github.com/en/articles/customizing-your-repositorys-social-media-preview) under Settings > Social preview.

Changing it to the Execa logo might be nice. [This website](https://metatags.io/) can be used to make sure it worked.

**Comment by sindresorhus** [comment]
Done
