### ISSUE TITLE
Mocking stdout on Execa using sinon

### ISSUE THREAD

**Issue by elbandito** [sindresorhus/execa#358]
Hi,

I'm trying to write some tests around `execa.command`, using sinon for mocking.  I'd specially like to create a stub/mock where I can dictate the value in `stdout`.

I can stub the call to `command` by doing something like the following:
```js
const execaStub = sandbox.stub(execa, 'command').withArgs(
  'docker login --username=_ --password-stdin my.registry.com',
  {input: 'DEADBEEF'})
```

However, I'm perplexed on how to go about mocking the `stdout` to some custom text.

For example, if I had some code like the following:
```js
let {stdout} = execa.command(`docker login --username=_ --password-stdin my.registry.com`, {input: this.registryPassword()})

```
And I wanted to parse different `stdout` values, how could I mock `stdout` to be whatever I want?

Anyway, if any of you have some suggestions or can point me in the right direction, I would be grateful. 

Regards,
Travis

**Comment by ehmicky** [comment]
Hi Travis, thanks for reaching out.

I think this is more a question about stubbing/Sinon that execa. If I understood your question correctly, you would need to stub the return value:

```js
const execaStub = sandbox.stub(execa, 'command')
  .withArgs('docker login --username=_ --password-stdin my.registry.com', {input: 'DEADBEEF'})
  .returns({ stdout: 'mockStdout' })
```

**Comment by elbandito** [comment]
Hi @ehmicky thanks for the direction.  I'll try approaching it from that angle.

Travis

**Comment by ehmicky** [comment]
Also please note `execa.command()` returns a `Promise`, so actually you might need to mock a `Promise<object>` not an `object`, depending on whether you want you test to be async or sync.
