### ISSUE TITLE
Error handling when outputing child process's output

### ISSUE THREAD

**Issue by ankitjena** [sindresorhus/execa#363]
I am using execa, to do a simple `npm start` command in cli-tool. I want the command to display the output of `npm start`. This can be done by using
```js
execa('npm', ['start']).stdout.pipe(process.stdout);
```
But I want to throw errors(if any) in the server. To do that docs say to use try catch. I did that, but when using stdout.pipe no error's are thrown and the command gets stuck.

How do I do both? This is my code.
```js
try {
    await execa('npm', ['run', 'start']).stdout.pipe(process.stdout)
  } catch({stderr, exitCode}) {
    logError(stderr)
    process.exit(exitCode)
  }
```

Thanks in advance.

**Comment by ehmicky** [comment]
Hi @ankitjena,

You need to `await` the promise returned by `execa()`, not the stream returned by `stdout.pipe()`.

```js
try {
    const subprocess = execa('npm', ['run', 'start'])
    subprocess.stdout.pipe(process.stdout)
    await subprocess
} catch({stderr, exitCode}) {
    logError(stderr)
    process.exit(exitCode)
}
```

**Comment by ankitjena** [comment]
@ehmicky This works, Thanks a lot.
