### ISSUE TITLE
Mocking stdout/stderr with jest

### ISSUE THREAD

**Issue by faustbrian** [sindresorhus/execa#368]
I am currently writing tests for some parts that decide how to proceed based on stdout, stderr and exitCode but I seem to be unable to mock them through jest.

```ts
import execa from "execa";

const spy = jest.spyOn(execa, "sync").mockReturnValue({
    command: "whoami",
    exitCode: 0,
    exitCodeName: "SUCCESS",
    stdout: "stdout",
    stderr: "stderr",
    failed: false,
    timedOut: false,
    isCanceled: false,
    killed: false,
});

someFunctionThatCallsExecaSync();

expect(spy).toHaveBeenCalled();
```

This way of doing it works if I apply it to `child_process` and a few other packages that can execute commands but with execa it doesn't seem to have any affect as the `execa.sync` call in `someFunctionThatCallsExecaSync` is executed and returns its real outcome.

What would be the right way of mocking the values of stdout, stderr and exitCode if it isn't possible through a spy? Any suggestions on how to properly mock those values are appreciated.

**Comment by ehmicky** [comment]
There should not be anything specific to execa there.

For example, if you were to wrap `execa.sync()` in an function:

```js
const execaSync = function(...args) {
  return execa.sync(...args)
}
```

Then spy on this, and it does not work, then it means there is something wrong with your jest/mocking setup, not with execa. In that case, you should ask on the `jest` repository.

Really, `execa.sync()` is just a regular function, we don't do anything specific there.

**Comment by faustbrian** [comment]
Alright, will try my luck there. Just seemed odd that the mock works for other packages and child_process. Thanks!
