### ISSUE TITLE
Not getting the actual error from child process

### ISSUE THREAD

**Issue by Izhaki** [sindresorhus/execa#369]
On my terminal:

```
$ nonesense
sh: nonesense: command not found
```

However when I use:

```js
execa.command('nonsense').catch(error => {
  console.log(error);
});
```

There is no mention to this `sh: nonesense: command not found`:

```
{ Error: Command failed with exit code 2 (ENOENT): nonsense
spawn nonsense ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
  errno: 'ENOENT',
  syscall: 'spawn nonsense',
  path: 'nonsense',
  spawnargs: [],
  command: 'nonsense',
  exitCode: 2,
  exitCodeName: 'ENOENT',
  stdout: '',
  stderr: '',
  all: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined }
```

**Comment by ehmicky** [comment]
`ENOENT` is short for "Error: no file entry".

**Comment by Izhaki** [comment]
I didn't explain myself well enough.

I'm trailing this library with the belief that it will help further down the line to deal with all sorts of windows / node issues related to `child_process`.

Thing is, I cannot change the output compared to what it would have been  by simply running these commands from the shell / makefile. It seems that by simply using `child_process.exec` you get the same output.

I can only guess, based on the answer, that this library does not support this.

**Comment by ehmicky** [comment]
> It seems that by simply using child_process.exec you get the same output.

You mean the same output as execa, am I correct?

At the low-level, child processes error exits do not give any other information than the exit code. My guess (I might be wrong) is that `sh` either:
  - translates each error code into a human-readable string
  - does not extra checks for common errors (such as command not found) to give better  error messages

In either case, this is not implemented in neither core Node.js nor execa. However a PR is welcome if you would like to improve this part :)

**Comment by Izhaki** [comment]
> You mean the same output as execa, am I correct?

No, the same output as if you ran the command on shell:

```js
const { exec } = require('child_process');

exec('nonesense', { encoding: 'utf8' }, (error, stdout) => {
  console.log(error);
});
```

Outputs:
```
{ Error: Command failed: nonesense
/bin/sh: nonesense: command not found

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12) killed: false, code: 127, signal: null, cmd: 'nonesense' }
```

And if you log `error.message` you get `/bin/sh: nonesense: command not found`.

**Comment by ehmicky** [comment]
`command not found` is printed on `stderr` by `sh`. It's an error message that is specific to `sh`. When `sh` executes it does several checks and throws errors accordingly, including when the command does not exist.

`child_process.exec()` implies the `shell: true` option, which means the command will be run with `sh` (if you're on Unix). `execa()` is based on `child_process.spawn()` so the `shell` option defaults to `false`. If you really need that specific error message, you should be able to get it by using `execa('nonsense', {shell: true})`. 

Please note that running a command through a shell (i.e. `shell: true`), whether from `execa()` or from `child_process.exec()`, has many [issues](https://github.com/sindresorhus/execa#shell). Make sure you check those because using it just to get that one error message.

**Comment by Izhaki** [comment]
That explains everything.

With `shell: true` everything works as expected.

As previously mentioned, the overall aim here is mimic current behaviour (which involves shell execution) - or at least to provide that option.

I'm not the one to call the shots on whether or not to use shell - the users will have to make that choice. But it's good to know they _can_ and can opt out using this lib.

Thank you so much!

---

**PS**

Yarn, as far as I can tell, is using shell when executing commands(see [this](https://github.com/yarnpkg/yarn/blob/9a8dd6e7d9daba9dace44223ef48228b31e117d3/src/util/child.js#L64) and [that](https://github.com/yarnpkg/yarn/blob/1a57117853afa2901feb541f6db7f064d9c0f8b9/src/cli/index.js#L620)) - so I guess what's good for yarn is good enough?

**Comment by ehmicky** [comment]
> Yarn, as far as I can tell, is using shell when executing commands(see this and that) - so I guess what's good for yarn is good enough?

It makes sense to use shell execution within Yarn and npm. Different projects with different requirements :)
