### ISSUE TITLE
Consider allowing windowsHide option

### ISSUE THREAD

**Issue by jabrown85** [sindresorhus/execa#371]
See nodejs/node#29837 for why this option can make a practical difference. I saw the previous discussion on #242 that was closed because there wasn't a known reason to allow it.

**Comment by ehmicky** [comment]
Yes that makes sense.

TLDR: without `windowsHide: false` on Windows, `CTRL-C` does not work. So we should still default it to `true` but allow users to override it to `false`.

@sindresorhus what do you think?

**Comment by sindresorhus** [comment]
Sure, as long as we clearly document in what specific scenarios it might be useful.

**Comment by ehmicky** [comment]
Done at #388.
