### ISSUE TITLE
.npmrc、.yarnrc  file ignored in child process ?

### ISSUE THREAD

**Issue by NexxLuo** [sindresorhus/execa#380]
I exec npm install or yarn add command in child process . But the command didn`t read the .npmrc file or .yarnrc file.  Why? How to do it?

I config a registry url in the .npmrc file , it is necessary.

**Comment by ehmicky** [comment]
Hi @nexx, thanks for reporting this issue.

In order to help you with this, could you please provide us with: 
  - exact steps to reproduce
  - expected output
  - OS version
  - Node.js version
  - `execa` version

Thanks!

**Comment by NexxLuo** [comment]
It's my fault.I set a wrong `cwd` value
