### ISSUE TITLE
Fails on Electron 7, Node 12 because of get-stream

### ISSUE THREAD

**Issue by momakes3** [sindresorhus/execa#389]
Using `do-not-disturb` module for example in Electron, does the action it's supposed to (toggle dnd), but then fails with the following error:
```
Cannot get property getBufferedValue of undefined
```
Or on success (in another module similar to do-not-disturb): 
```
Cannot read property 'on' of undefined
```
![image](https://user-images.githubusercontent.com/56743114/68541594-9eb7d380-03b6-11ea-9599-e625945064e7.png)
(could it from this line? https://github.com/sindresorhus/get-stream/blob/master/index.js#L43)

Which is likely from either the `get-stream` dependency or how its used. 

--- 
I replaced `execa` with `child_process.execFile` and it worked without the error.

**Note:** I know it's hard to pin down without a reproduction, but I figured to post this here so I don't forget until I can create a minimal repo.

**Comment by ehmicky** [comment]
Hi @momakes,

Thanks for reporting this issue.

I've checked the relevant lines of code and I could not see why that variable could become `undefined` at that point.

Based on this, I think we would need reproducible steps in order to address this issue. Thanks!

**Comment by sindresorhus** [comment]
This definitely looks like a bug in Electron, since it used to work in Electron and it works perfectly in Node.js.
