### ISSUE TITLE
Doesn't work with electron

### ISSUE THREAD

**Issue by davej** [sindresorhus/execa#39]
Feel free to close this as a `wontfix` but I wanted to log the issue anyway.

With standard exec:

```js
const exec = require('child_process').exec;
exec('networksetup', console.log.bind(console));
// 'networksetup Help Information...' Works OK
```

With execa:

```js
const execa = require('execa');
execa.shell('networksetup').then(console.log.bind(console));
// Error: Command failed: /bin/sh -c networksetup
```

**Comment by davej** [comment]
Scratch that. I was getting the error because `execa` was being run through webpack.

**Comment by DrSensor** [comment]
Hi @davej, dou you remember how you solve this issue? I hit the same problem and can figure out how to configure the webpack in electron to use execa :cry:
