### ISSUE TITLE
Electron app - showing output of execution in real time

### ISSUE THREAD

**Issue by maku** [sindresorhus/execa#393]
I have a longer running task (e.g. a build process). Now I would like to printout the log of the process in the console of an electron app while running.

How do I achieve this when using execa?

**Comment by ehmicky** [comment]
Hi @maku, thanks for reaching out.

When it comes to Execa (and the underlying `child_process` module), you can retrieve the process output with different modes described by the [`stdio`](https://nodejs.org/api/child_process.html#child_process_options_stdio), the two main ones being `inherit` (write to parent process output) and `pipe` (buffer and return as a string).

When it comes to redirecting this to the Electron console, I think this question relates more to Electron than to this project.
