### ISSUE TITLE
Include stdout/stderr in `error.message`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/execa#395]
We removed it in `execa` v2 for some reason, but it's very useful.

The lack of it leads to a lot of annoyance and makes it harder for users to see what actually went wrong...

It also makes it harder to do test assertions like this:

```js
test('missing file operands', async t => {
	await t.throwsAsync(execa('./cli.js'), /`source` and `destination` required/);
});
```

Open questions:
- Should we include `stdout` or only `stderr`?
- Should we truncate it at some length?

**Comment by ehmicky** [comment]
Following from some discussion with @sindresorhus, we thought of the following:
  - `error.message` should include prefixes (e.g. `Command failed with exit code`) and be appended with `stdout` and `stderr` (if they exist)
  - `error.shortMessage` should include prefixes but not `stdout`/`stderr`
  - `error.originalMessage` should include neither prefixes nor `stdout`/`stderr`

This would be a breaking change.
