### ISSUE TITLE
TypeError: spawnedPromise.finally is not a function

### ISSUE THREAD

**Issue by V1os** [sindresorhus/execa#412]
caught a bug after updating to a new version (4.0)

file: node_modules/execa/lib/kill.js:85

env: node -v
```
v10.14.1
```

**Comment by ehmicky** [comment]
Hi @V1os,

Thanks for reporting this.

Could you please share: 
  - the source code that triggered this error, so we can reproduce it
  - your OS or any additional relevant environment information (such as if you're using Electron)
  - whether you still encounter the bug when upgrading to `v10.19.0`

Thanks a lot!

**Comment by V1os** [comment]
@ehmicky hi.

1. 
```
const subProcess = execa('mongoexport', argumentsBy, optionsExeca);
```

> log params, 

```
[
  '--host=localhost:27017',
  '--db=data',
  '--query={"$or":[{"$and":[{"publish.prod":{"$eq":true},"deployed.prod":{"$eq":false}}]},{"$and":[{"publish.prod":{"$eq":false},"deployed.prod":{"$eq":true}}]},{"$where":"this._rv !== this._v && this.deployed.prod === true && this.publish.prod === this.deployed.prod\\n|| (this._le === \\"rel\\" && this.deployed.prod === true && this.publish.prod === this.deployed.prod) "}],"site":{"$oid":"REDACTET_PERSONAL"}}',
  '--jsonArray',
  '--collection=data_model',
  '--out=deploy/data_model.json'
] {
  shell: false,
  reject: false,
  cwd: '/private/var/vhost/cms-v3',
  timeout: 15000
}
```

2. > $ > cat /etc/os-release

```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
not use special app (only express.js, apollo server, redis-cli, mongodb tools)

3. Don't upgrade to `v10.19.0` now, but try soon. And for node greater than 12.* work fine

**Comment by ehmicky** [comment]
Thanks for the information @V1os.
If you replace `mongoexport` and its CLI arguments (but keep the Execa options) by `sleep` and `['30']`, do you get the same error message?

**Comment by V1os** [comment]
I will try to answer in the coming days
I need to simulate this locally (the same env stage etc.) since this error is in my production

**Comment by riddict** [comment]
Got the same error
Tried to execute adonis ace command in controller.
Using Windows 10 and NodeJS v9.3.0

**Comment by ehmicky** [comment]
Execa is not supporting Node `9.3.0`. The minimum Node.js version is [currently the latest `10.*.*`](https://github.com/sindresorhus/execa/blob/26d6b0d59588794173882f78609844ea71944463/package.json#L14).

**Comment by riddict** [comment]
Ahh sorry, just updated my node and it all worked now
