### ISSUE TITLE
Add `execa.stream()`

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#414]
Add a `execa.stream(...)` method. It behaves exactly like `execa(...)` except:
  - the return value is only a `childProcess` not a `Promise`
  - there is no [promise handling logic](https://github.com/sindresorhus/execa/blob/120230cade59099214905ac2a9136e406c0b6f3a/index.js#L107)

This is based on the discussion [here](https://github.com/sindresorhus/execa/pull/351#issuecomment-583041498) except using `execa.stream(...)` instead of `execa(...).stream()`.

What do you think @sindresorhus?

**Comment by sindresorhus** [comment]
Sounds good.

Maybe it could have a `.waitUntilFinished()` kinda property that you can then await to get the result too?

**Comment by ehmicky** [comment]
Yes we can do that. 
How should it be called? `waitUntilFinished()` might be a little verbose? Do you have any other names in mind?

**Comment by wesleytodd** [comment]
> Maybe it could have a .waitUntilFinished() kinda property that you can then await to get the result too?

The question I have is what use case there is for this when the typical stream handling method would be an event emitter interface with an `end` event.  Are you thinking it would provide the other api's like `.all`?

While it seems silly on face value, having `execa().stream().promise()` should not be out of the question.

**Comment by ehmicky** [comment]
> The question I have is what use case there is for this when the typical stream handling method would be an event emitter interface with an end event. Are you thinking it would provide the other api's like .all?

My understanding of @sindresorhus suggestion would be to first use `execa.stream()` to use the underlying `childProcess`, then call `.waitUntilFinished()` (or other name) to wait for the child process's result.

> While it seems silly on face value, having execa().stream().promise() should not be out of the question.

This would be `execa.stream(...).promise()` following the initial issue. This name would work for me :+1:

**Comment by wesleytodd** [comment]
> then call .waitUntilFinished() (or other name) to wait for the child process's result.

Right, sorry I was not super clear.  I mean that once you have the child process you can just do `cp.on('exit' () => { /* ... */})`.  What is the need to go back to a promise for the user if they have oped for the `stream` interface?  The thing I imagined was that it would be to provide the other additional API's `execa` adds in the promise case.

**Comment by ehmicky** [comment]
Some users might not want `childProcess` and `Promise` mixed together, but might want to use both for different reasons:
  - `childProcess` allows things like streaming
  - `Promise` allows receiving the full result at once, and is more convenient than `cp.on('exit' () => { /* ... */ })`

Calling `execa.stream(...)` then `.promise()` (or other name) is a way to achieve this.

**Comment by sindresorhus** [comment]
What @ehmicky said. It's not just about waiting for completion, it's also about easily gathering the result. For example, I want to display the child process stdout live in the terminal to the user, but at the end, I need to check that as certain thing was included in the stdout stream.

**Comment by wesleytodd** [comment]
Makes sense! As this module is more about developer experience around the core `child_process` api I agree it is good to have this api.

**Comment by wesleytodd** [comment]
Ok, one other idea, it is not technically just a `stream` interface we are doing here.  Technically we are saying "return me the unmodified child_process".  So would something like `.raw()` or `.childProcess` be more correct?  If we just had an accessor to get the actual `child_process` off the promise that would also be fine right?

**Comment by ehmicky** [comment]
Yes I agree: we added #413 for that use case.
So with `execa(...).child`, user would use the `Promise` interface, then the `childProcess`, while with `execa.stream(...).promise()` they would do the inverse.
@sindresorhus @wesleytodd Do you think it makes sense to have both, or should we simplify to only one of those two? I am fine with having both, I am just curious what you think.

**Comment by wesleytodd** [comment]
Cool, did not see that one!  Yeah for my use case that addition would serve just fine. Personally I think having one way is *much* preferred for simplicity and maintenance.  Also that api is a much more simple addition, so I might take a look at just PRing that one if you all are also fine with that direction.

**Comment by ehmicky** [comment]
Thanks @wesleytodd a PR for #413 would be great no matter what!

@sindresorhus What are your thoughts about my question above?

**Comment by sindresorhus** [comment]
Yeah, good point. Let's go with only `promise.child` then.

**Comment by ehmicky** [comment]
:+1: 
Closing this in favor of #413.
