### ISSUE TITLE
Feature Request: Support for multiline commands (sync)

### ISSUE THREAD

**Issue by a-y-u-s-h** [sindresorhus/execa#420]
### Feature Suggestion

Hey. I'm exporting `execa.commandSync` function and then importing it as `shell`, so that I can use it as: `shell("mkdir something")`. 

It would be awesome to have a function that could work with multiline (and multi-commands) (like a bash script) at once with one command. Not sure if suggested before.

```js
  shell(`
    mkdir ${foo}
    cd ${foo}
    touch ${foo}.txt
  `)
```

**Comment by ehmicky** [comment]
I think it would make more sense to use an array of strings:

```
execa.command([
  `mkdir ${foo}`,
  `cd ${foo}`,
  `touch ${foo}.txt`,
])
```

That being said, I think this is about orchestrating commands and Execa should focus on single command execution and let users build utilities on top of it instead. What do you think @sindresorhus?

**Comment by sindresorhus** [comment]
I think this is outside the scope of Execa.

You have two options here:

#### 1

```js
const commands = [
  `mkdir ${foo}`,
  `cd ${foo}`,
  `touch ${foo}.txt`,
];

for (const command of commands) {
	await execa.command(command);
}
```

#### 2

```js
execa.command([
  `mkdir ${foo}`,
  `cd ${foo}`,
  `touch ${foo}.txt`,
].join('&&'), {shell: true});
```

I would strongly recommend `1`.
