### ISSUE TITLE
Command inside Backticks or $() do not work

### ISSUE THREAD

**Issue by Rolanddoda** [sindresorhus/execa#421]
I am trying to run the following command:
`basename -s .git $(git config --get remote.origin.url)`.

I am trying to do it with execa:
- `execa.command('basename -s .git $(git config --get remote.origin.url)') // DOESN'T WORK`
- `execa('basename', ['-s', '.git', 'git config --get remote.origin.url']) // DOESN"T WORK`

As a workaround I am doing this:

```shell
  const { stdout } = await execa('git', ['config', '--get', 'remote.origin.url'])
  const {stdout: repoUrl} = await execa('basename', ['-s', '.git', stdout])
```

But is there any better way, by just using `execa.command` ?

**Comment by ehmicky** [comment]
Backticks and `$()` are Bash-specific features. By default, Execa does not use any shell, but you can opt-in with the [`shell: true` option](https://github.com/sindresorhus/execa/blob/master/readme.md#shell). 

```js
await execa('basename -s .git $(git config --get remote.origin.url)', {shell: true})
```

That being said, please check [the downsides](https://github.com/sindresorhus/execa/blob/master/readme.md#shell) of that option. Your workaround is actually the proper way of doing this: two separate calls to `execa`. It is faster, more cross-platform and safer. You could also do:

```js
const { stdout } = await execa.command('git config --get remote.origin.url')
const {stdout: repoUrl} = await execa.command(`basename -s .git ${stdout}`)
```

**Comment by Rolanddoda** [comment]
Yeah I checked the `shell: true` but I need the command to be cross-platform.
I don't have a problem using two separate calls to `execa` but wasn't sure it's a proper way.
Thanks for the answer :)

**Comment by ehmicky** [comment]
Bash is cross-platform but it not installed by default on Windows. Since `$()` and backticks are Bash-specific features, you should probably avoid them for cross-platform code.
