### ISSUE TITLE
Add `localNodeModules` option or document solution

### ISSUE THREAD

**Issue by TomerAberbach** [sindresorhus/execa#425]
Hey! Thanks for this package.

I was using `execa` today and needed to spawn a `node` process that could resolve modules from the `node_modules` directory under the directory where it was spawned rather than the directory where the `node` script was located.

I naively assumed that the `cwd` option defaulting to `process.cwd()` would achieve this, but that was not the case. I ultimately figured out that I could set the [`NODE_PATH`](https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders) environment variable to `path.join(process.cwd(), 'node_modules')` via the `env` option to make it work.

I was wondering whether you'd be interested in supporting this use case more directly via a `localNodeModules` option that defaults to `false`. When set to `true` we could use `find-up` to find the local `node_modules` directory, and then we could set `NODE_PATH` in `env` (or append if `NODE_PATH` is already set).

Alternatively, if you don't think this warrants its own option, then I think it would be helpful to document this solution in the readme (I was reading through the readme before, trying to find a solution).

In either case I'd be happy to write the pull request; just thought I'd get your thoughts first. Thanks in advance!

**Comment by sindresorhus** [comment]
I don't think this is a good idea. `NODE_PATH` is an anti-patterns, and also [not available for ESM](https://nodejs.org/api/esm.html#esm_no_node_path).

**Comment by ehmicky** [comment]
I think the option you might be looking for are [`preferLocal`](https://github.com/sindresorhus/execa#preferlocal) and [`localDir`](https://github.com/sindresorhus/execa#localdir).

**Comment by TomerAberbach** [comment]
@sindresorhus Thanks, didn't know it's not available for ESM. Will avoid using it.

@ehmicky Unfortunately, `preferLocal` and `localDir` don't solve my problem because they do not affect how `require` resolves modules (relative to the node script location).

Anyways, it sounds like what I'm trying to do is not well-supported or recommended so I'll change my approach.
