### ISSUE TITLE
4.0.1 causes problems with Bluebird

### ISSUE THREAD

**Issue by tprobinson** [sindresorhus/execa#426]
I've gotten an error from Bluebird when using execa at version `4.0.1`:
```
TypeError: this._then is not a function
    at Promise.then (~/.config/yarn/global/node_modules/bluebird/js/release/promise.js:154:17)
    at ChildProcess.then (~/.config/yarn/global/node_modules/execa/lib/promise.js:13:25)
```

This works fine if I downgrade execa to `4.0.0`.

**Comment by ehmicky** [comment]
Thanks for reporting this problem @tprobinson!

@fisker This appears to be related to #403, do you know what the problem might be?

**Comment by fisker** [comment]
I don't know, but I'll take a look.

**Comment by fisker** [comment]
I found the reason,  [here](https://github.com/sindresorhus/execa/blob/master/lib/promise.js#L5) we use `Promise.prototype`, which is `bluebird.protype` in this case, and [here](https://github.com/sindresorhus/execa/blob/e22252608647c72ced33190f1edee29375c30e57/index.js#L107) we use `async function` returns a native Promise, so we are calling `bluebird#then` on native Promise.

[Old version use `Promise#then` directly](https://github.com/sindresorhus/execa/pull/403/files#diff-6230eb7fbf1dd2186bf1be6042c27f55L5), so there is no problem.


I see possible solutions

1. use old logic, change it back to 

```js
(...args) => promise()[property](...args);
```

2. use this to get the nativePromise

```js
const nativePromise = (async () => {})().constructor;
```

3. wrap `async` function to return a `global.Promise`(bluebird in this case) instance, I think this is bad idea.

Which one do you prefer?

**Comment by ehmicky** [comment]
I think `1.` might be simpler. `2.` is a little more involved, but it works too.

**Comment by fisker** [comment]
I think `2` better, some old Promise lib may don't have `.finally`, or broken like I did in the test.
