### ISSUE TITLE
How to declare exitCodes (> 0) as none errors ?

### ISSUE THREAD

**Issue by arlac77** [sindresorhus/execa#432]
Some executables report state with none zero exit codes (those are no errors by the executable itself).

Is it possible to declare the none error exit codes somehow ?

if not, what about a callback like:
```js
execa('myExecutable',{ isErrorExitCode: (code) => code > 3 });
```

**Comment by ehmicky** [comment]
Using non-0 exit codes to communicate success information (as opposed to failure) is both unconventional and I believe it might be non-standard from a POSIX standpoint. I don't think this is something that should be encouraged by adding an option for it.

That being said, you could support this use case with a little extra code:

```js
const result = await execa('myExecutable', { reject: false })
if (result.failed && !notErrorExitCodes.includes(result.exitCode)) {
  throw result
} 
```

@sindresorhus What are your thoughts?

**Comment by sindresorhus** [comment]
Yeah, this is not something we want built-in.
