### ISSUE TITLE
does the execa('echo', ['unicorns']).stdout.pipe(process.stdout) example need { end: false }?

### ISSUE THREAD

**Issue by jedwards1211** [sindresorhus/execa#438]
or does execa inject magic to prevent the child stdout from piping the end event by default?

**Comment by ehmicky** [comment]
Execa does not override the `end` option nor inject any magic there.
However, I just tried:

```js
execa('echo', ['unicorns']).stdout.pipe(process.stdout)
```

And I can confirm `process.stdout.end()` is not called, so I don't think you need to specify the `end` option.

**Comment by jedwards1211** [comment]
Okay this is something I didn't realize about `stdout` and `stderr`:

> The process.stderr and process.stdout Writable streams are never closed until the Node.js process exits, regardless of the specified options.

(https://devdocs.io/node/stream#stream_readable_pipe_destination_options)
