### ISSUE TITLE
ENAMETOOLONG with long argument

### ISSUE THREAD

**Issue by ffMathy** [sindresorhus/execa#443]
I'm trying to start a process with a long argument on Windows with `execa`, and get an `ENAMETOOLONG`.

Is there a workaround to be able to support longer arguments? It's not the file path itself that is long - it's the argument. So I'm a bit confused as to why that gives such an error.

**Comment by ehmicky** [comment]
Hi @ffMathy,
This is not a behavior implemented by Execa, but by [Node.js itself](https://nodejs.org/api/os.html#os_posix_error_constants) so I would suggest asking in https://github.com/nodejs/node itself.
I am not 100% sure, but I actually believe Node.js inherits this limitation from the OS itself, so I am not sure there is any workaround, except for decreasing the size of the arguments list. Other IPC mechanisms such as using a file to pass the information are usually used to solve this type of problem.

**Comment by ffMathy** [comment]
@ehmicky thank you - can you elaborate on how to use such IPC mechanisms?

**Comment by ehmicky** [comment]
If a process A needs to pass a long list of argument to a process B, then process A could write this to a file, then pass the filepath as an argument to process B. Process B would then read the file's contents.

**Comment by ffMathy** [comment]
@ehmicky ah yes, but is there a way to do it if process B does not support specifying a filepath?

**Comment by ehmicky** [comment]
If process B supports reading the argument list from `stdin`, this could be used too.
Note: I think this discussion might not be related to this repository.

**Comment by ffMathy** [comment]
I see. Thank you for your kind help either way.
