### ISSUE TITLE
execa.command fails if path contains space.

### ISSUE THREAD

**Issue by reimertz** [sindresorhus/execa#444]
I am one of those idiots who symlink into my iCloud drive and therefore end up in the land of

```
/Users/r/Library/Mobile Documents/com~apple~CloudDocs/_/work/...
```

Notice the space in `/Mobile Documents/`.

I am trying to play around with [netlify/zip-it-and-ship-it](https://github.com/netlify/zip-it-and-ship-it) (read adding a new) feature and get these errors when running a freshly-cloned repo

```
  1 test failed

  bin › CLI | --version

  Rejected promise returned by test. Reason:

  Error {
    code: 'ENOENT',
    command: '"/Users/r/Library/Mobile Documents/com~apple~CloudDocs/_/repos.nosync/zip-it-and-ship-it/src/bin.js" --version',
    errno: 'ENOENT',
    exitCode: undefined,
    failed: true,
    isCanceled: false,
    killed: false,
    originalMessage: 'spawn "/Users/r/Library/Mobile ENOENT',
    path: '"/Users/r/Library/Mobile',
    signal: undefined,
    signalDescription: undefined,
    spawnargs: [
      'Documents/com~apple~CloudDocs/_/repos.nosync/zip-it-and-ship-it/src/bin.js"',
      '--version',
    ],
    stderr: '',
    stdout: '',
    syscall: 'spawn "/Users/r/Library/Mobile',
    timedOut: false,
    message: `Command failed with ENOENT: "/Users/r/Library/Mobile Documents/com~apple~CloudDocs/_/repos.nosync/zip-it-and-ship-it/src/bin.js" --version␊
    spawn "/Users/r/Library/Mobile ENOENT`,
  }
```

This is what the test is trying to do

```
const BINARY_PATH = `${__dirname}/bin.js`

test('CLI | --version', async t => {
  const { stdout } = await execa.command(`${BINARY_PATH} --version`)

  t.is(stdout, version)
})
```

I don't know if the handling in [command.js](https://github.com/sindresorhus/execa/blob/5aabbfb187d4bc9fdaf6bc77a62a9c4f4c7d36a1/lib/command.js#L13) is intentional and my errors would be considered self-inflicted harm or this is an actual bug.

**Comment by ehmicky** [comment]
Hi @reimertz,

`execa.command()` requires significant spaces to be escaped with a backslash. To fix your issue, you can either:
  - Use `execa()` instead, which does not have any issues with spaces
  - Use `__dirname.replace(/ /g, '\\ ')`

In the case of `@netlify/zip-it-and-ship-it`, I am one of the maintainers, so I just submitted [a PR](https://github.com/netlify/zip-it-and-ship-it/pull/236) to fix the problem.

**Comment by ehmicky** [comment]
This should be fixed now. Closing this issue. Thanks for reporting!
