### ISSUE TITLE
Bad file descriptor error on windows using execa.commad 

### ISSUE THREAD

**Issue by sandeep-paliwal** [sindresorhus/execa#448]
When using `execa.command()` to launch jest test I get following child process error on windows.
Here is the code being used 
`const child = execa.command('jest --passWithNoTests ./test', {
    stdio: ['inherit', 'inherit', 'inherit', 'ipc'],
    shell: true,
    cwd: process.cwd(),
    preferLocal: true
  })`

Following is the error I get (with shell option as true and false ) - 

" child_process.js:127
p.open(fd);
    ^

Error: EBADF: bad file descriptor, uv_pipe_open
    at Object._forkChild (child_process.js:127:5)
    at setupChildProcessIpcChannel (internal/bootstrap/pre_execution.js:334:30)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:57:3)
    at internal/main/run_main_module.js:7:1 {
  errno: -4083,
  code: 'EBADF',
  syscall: 'uv_pipe_open'
}
(node:2044) UnhandledPromiseRejectionWarning: Error: spawn jest ENOENT
    at notFoundError (D:\a\recheck-gh-actions\recheck-gh-actions\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (D:\a\recheck-gh-actions\recheck-gh-actions\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (D:\a\recheck-gh-actions\recheck-gh-actions\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12) "

System details
OS - Microsoft Windows Server 2019 10.0.17763
Node - V12
execa version - 4.0.0

**Comment by ehmicky** [comment]
Hi @sandeep-paliwal,

Could you try to upgrade to the latest version of Execa (`5.0.0` as of now)? 
Also, could you try without the `shell` option?
Finally, could you please show the output of `jest --version`?

**Comment by sandeep-paliwal** [comment]
jest@26.6.3
execa@5.0.0
Tried without shell option, still same error. 
I also tried running some different command via execa, while simple one like 'echo test' worked, npm list failed with same error. Here is the code sample - 
`const child = execa.command('npm list', {
    stdio: ['inherit', 'inherit', 'inherit', 'ipc'],
    cwd: process.cwd(),
    preferLocal: true
  })`

Note: this code is running as Github CI workflow.

**Comment by ehmicky** [comment]
If you replace `npm list` with `jest --version`, do you get the same error?
Also, the `cwd` option is probably not necessary (it already defaults to `process.cwd()`).

**Comment by sandeep-paliwal** [comment]
still getting the same error with `jest --version`

**Comment by ehmicky** [comment]
Trying to reduce this problem, little by little, since I cannot reproduce, please bear with me :)
Can you try the following commands?
  1. `execa('jest', ['--version'], { stdio: ['inherit', 'inherit', 'inherit', 'ipc'], preferLocal: true })`
  2. `execa('jest', ['--version'], { stdio: 'inherit', preferLocal: true })`
  3. `execa('jest', ['--version'], { preferLocal: true })`
