### ISSUE TITLE
Promisify spawn

### ISSUE THREAD

**Issue by cstruct** [sindresorhus/execa#45]
Is there any reason that `execa.spawn` isn't promisified as `execa`?

**Comment by SamVerschueren** [comment]
What do you mean? `execa.spawn()` (which is deprecated) is an alias for `execa()`  -> https://github.com/sindresorhus/execa/blob/master/index.js#L214

**Comment by cstruct** [comment]
The  the README is [incorrect](https://github.com/sindresorhus/execa/blame/master/readme.md#L86-L91).

**Comment by cstruct** [comment]
Herpaderp, this was an issue of my lacking reading comprehension. Sorry, closing.

**Comment by cstruct** [comment]
The code you referenced isn't published. The README still references `execFile`.

Reopening.

**Comment by kevva** [comment]
Why? The documentation that lives in `master` isn't a representation of what's published on `npm`. Read the one there instead.

**Comment by cstruct** [comment]
> Same options as child_process.execFile.
Is in master

**Comment by LinusU** [comment]
The documentation in the master branch says that `execa` takes the same arguments as `execFile`, but in the code it uses `spawn`. It also says `file` as the first argument, but that seems to also be based on it using `execFile` instead of `spawn`

**Comment by kevva** [comment]
We're planning on adding as many options from `execFile` while still using `spawn` underneath.

**Comment by LinusU** [comment]
If `execa` and `execa.spawn` is the same function, maybe it should have the same documentation in the readme?

**Comment by kevva** [comment]
Probably, later on. But as commented above, it's API and options are still not settled.
