### ISSUE TITLE
Problem using pipe

### ISSUE THREAD

**Issue by mikeerickson** [sindresorhus/execa#450]
I am using something very basic from examples

```js
const execa = require('execa')

const subprocess = execa('echo', ['foo'])
subprocess.stdout.pipe(process.stdout)
;(async () => {
  const { stdout } = await subprocess
  console.log('child output:', stdout)
})()
```

When I execute this script, it throws an error

```bash
/Users/mikee/Documents/code/tasks/test2.js:4
subprocess.stdout.pipe(process.stdout)
                  ^

TypeError: Cannot read property 'pipe' of undefined
    at Object.<anonymous> (/Users/mikee/Documents/code/tasks/test2.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

Ultimately, I will be calling mocha, and I need to pipe the output, but I cant get the simple example to work.

Something like

```js
const subprocess = execa('./node_modules/mocha/bin/mocha', ['test'])
```

**Comment by ehmicky** [comment]
Hi @mikeerickson,

Could you confirm whether shortening your example to the following would still reproduce this behavior?

```js
const execa = require('execa')

const subprocess = execa('echo', ['foo'])
subprocess.stdout.pipe(process.stdout)
```

**Comment by mikeerickson** [comment]
@ehmicky Unfortunately, this produces the same response

Using the following

```js
const execa = require('execa')

const subprocess = execa('echo', ['foo'])
subprocess.stdout.pipe(process.stdout)
```

produces the following error

```bash
/Users/mikee/Documents/code/tasks/test2.js:13
subprocess.stdout.pipe(process.stdout)
                  ^

TypeError: Cannot read property 'pipe' of undefined
    at Object.<anonymous> (/Users/mikee/Documents/code/tasks/test2.js:13:19)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```


To be clear, I have the following code

```js
const execa = require('execa')

const subprocess = execa('echo', ['foo'])
subprocess.stdout.pipe(process.stdout)
```

I am executing in terminal (using Node 14.5.0)


```bash
node tasks/test2.js
```

**Comment by ehmicky** [comment]
Which OS are you using?

Also, what do you get if you print `subprocess`?

```js
const execa = require('execa')

const subprocess = execa('echo', ['foo'])
console.log(subprocess)
subprocess.stdout.pipe(process.stdout)
```

**Comment by mikeerickson** [comment]
@ehmicky As expected, it returns 

```bash
Promise { <pending> }
```

**Comment by mikeerickson** [comment]
@ehmicky OK, so I refactored the original code (after the above lead) and result is now accurate

```js
const execa = require('execa')

const subprocess = execa('echo', ['foo'])
// subprocess.stdout.pipe(process.stdout)
;(async () => {
  const { stdout } = await subprocess
  console.log('child output:', stdout)
})()
```

I commented the 3rd line and it now produces accurate result.

```js
subprocess.stdout.pipe(process.stdout)
```

So, I expanded my original desire as follows and all is working now

```js
const execa = require('execa')

const subprocess = execa('./node_modules/mocha/bin/mocha', ['test'])
;(async () => {
  const { stdout, stderr } = await execa('./node_modules/mocha/bin/mocha', ['test'], { env: { FORCE_COLOR: 'true' } })
  stderr ? console.error(stderr) : console.log(stdout)
})()
```

**Comment by mikeerickson** [comment]
@ehmicky However, the above example is not using `.pipe` so the issue is not totally cleared.

**Comment by mikeerickson** [comment]
@ehmicky 

So, to recap, the following code throws the same error (this is pulled directly from example) and if I perform the console log as you suggested, it returns

```bash
Promise { <pending> }
```

```js
const execa = require('execa')

const subprocess = execa('echo', ['foo'])
subprocess.stdout.pipe(process.stdout)
;(async () => {
  const { stdout } = await subprocess
  console.log('child output:', stdout)
})()
```

I am thinking the use of `.pipe` would log mocha results as stream (as if I executed from CLI) but maybe my thinking is inaccurate.  

Using the following code, all is "working" but the output is not logged to console until the process is complete (as one would expect)

The following works as expected, no errors and console output is correct.  But again, it is only emitted when mocha test run is complete

```js
const execa = require('execa')

;(async () => {
  const { stdout, stderr } = await execa('./node_modules/mocha/bin/mocha', ['test'], { env: { FORCE_COLOR: 'true' } })
  stderr ? console.error(stderr) : console.log(stdout)
})()
```

**Comment by ehmicky** [comment]
> @ehmicky As expected, it returns 
> ```bash
> Promise { <pending> }
> ```

It should not. The return value is a `childProcess` with promise methods mixed in. In my machine, this prints as:

```
<ref *1> ChildProcess {
 ...
}
```

Which version of Execa are you using?
Also: which OS are you using?

**Comment by mikeerickson** [comment]
Wow, I am both embarrassed and surprised at the version installed.  I could sworn I had updated version, but alas I was using `0.2.2` 

After installing the latest version, all is working correctly as expected. 

I am terribly sorry for wasting your time on this issue and should have known better to check the installed version before raising the issue

I have learned a valuable lesson here 😬

**Comment by ehmicky** [comment]
No worries!
We're always happy to help out.
I think the real lesson here is to always include Node.js version, OS and library version in GitHub issues. Even when we think this cannot be related to the problem, you never know :)
