### ISSUE TITLE
The union command could not be executed

### ISSUE THREAD

**Issue by zq0904** [sindresorhus/execa#451]
The sample：
```ts
const execa = require('execa')
execa.command('pwd && pwd', {
  preferLocal: true,
  stdio: ['inherit', 'inherit', 'inherit', 'ipc'],
})
```
expect Output 2 times
This led to the command 'echo "packages/rn-template" >> .git/info/sparse-checkout'  It doesn't work

Just like this example
```ts
  const { spawn } = require('child_process')
  const runCommand = (command, args, options) => {
	return new Promise((resolve, reject) => {
		const executedCommand = spawn(command, args, {
			stdio: 'inherit',
			shell: true,
                         ...options
		})

		executedCommand.on('error', error => reject(error))

		executedCommand.on('exit', code => code === 0 ? resolve() : reject())
	})
  }
```
runCommand('pwd && pwd')

**Comment by sindresorhus** [comment]
> The shell option must be used if the command uses shell-specific features, as opposed to being a simple file followed by its arguments. - https://github.com/sindresorhus/execa#execacommandcommand-options

**Comment by zq0904** [comment]
Thank you for your answer
