### ISSUE TITLE
"Unknown system error -86" when building C components on Apple Silicon

### ISSUE THREAD

**Issue by lhazell** [sindresorhus/execa#452]
I keep getting the following error when building C components in npm:

```
npm ERR! code 1
npm ERR! path /[...]/node_modules/pngquant-bin
npm ERR! command failed
npm ERR! command sh -c node lib/install.js
npm ERR! ⚠ spawn Unknown system error -86
npm ERR!   ⚠ pngquant pre-build test failed
npm ERR!   ℹ compiling from source
npm ERR!   ✖ Error: pngquant failed to build, make sure that libpng is installed
npm ERR!     at /[...]/node_modules/execa/index.js:231:11
npm ERR!     at runMicrotasks (<anonymous>)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:94:5)
npm ERR!     at async Promise.all (index 0)
```

Note: native execution (not using Rosetta translation).

I keep getting the same error, from the same line in execa (index.js:231:11).

Packages like pngquant install fine with Homebrew so it seems like it's not an issue with Apple Silicon building C/C++ code, but rather me making a silly mistake.

All the same, this affects quite a few packages that depend on execa. I just got an Apple Silicon Mac, and I want to know if I can help.

**Comment by ehmicky** [comment]
Hi @lhazell,

Thanks for reporting this.

Could you please describe some steps to reproduce this?

Also, could you please show the lines of code where `execa()` is being executed?

**Comment by lhazell** [comment]
So far I have seen this with a few packages that rely on execa. imagemin-pngquant are two of them imagemin-optipng.

`npm install imagemin-pngquant/imagemin-optipng `will throw the error.

**Comment by ehmicky** [comment]
Hi @lhazell,

In order to reproduce the error, we would need some steps to reproduce this problem. In particular, the lines of code where `execa()` is being executed. I am unsure how running `npm install` with one of the above dependencies would throw any errors since they [do not include any `preinstall`/`postinstall` scripts](https://github.com/imagemin/imagemin-pngquant/blob/master/package.json).

**Comment by lhazell** [comment]
@ehmicky I looked into this. As you suspected, this is not an issue with execa, but the code being loaded by the packages themselves. I will submit an issue with the respective packages.

**Comment by ehmicky** [comment]
Thanks for following up @lhazell!
