### ISSUE TITLE
How to input subshell commands?

### ISSUE THREAD

**Issue by ericbiewener** [sindresorhus/execa#454]
How should we provide subshell commands like `$(git merge-base FETCH_HEAD main)` to `execa()`? I'm trying this:

```js
await execa(
  // "git diff --name-only $(git merge-base FETCH_HEAD main) $(git rev-parse HEAD)"
  "git", ["diff", "--name-only", "$(git merge-base FETCH_HEAD main)", "$(git rev-parse HEAD)"]
);
```

I have also tried splitting on every whitespace. Obviously, I can pull these out into separate commands and then provide the `stdout` back into the final command, but I'm hoping there's a way to just do this in a single `execa()` call.

**Comment by ehmicky** [comment]
Hi @ericbiewener,

`$()` is a shell-specific feature. This requires using the [`shell` option](https://github.com/sindresorhus/execa#shell).

```js
await execa(
  'git diff --name-only "$(git merge-base FETCH_HEAD main)" "$(git rev-parse HEAD)"',
  { shell: true }
);
```
