### ISSUE TITLE
Support `URL` where paths are supported?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/execa#458]
Node.js is adopting it for a lot of APIs.

- `file` argument.
- `cwd` option.
- `localDir` option.
- `execPath` option.
- `nodePath` option.

@ehmicky Thoughts?

---

If we decide to do this, we should probably open a Node.js issue about supporting `URL` for things in `childProcess` too.

**Comment by ehmicky** [comment]
Yes, this makes sense :+1:

**Comment by ehmicky** [comment]
Done for:
  - `cwd` option
  - `localDir` option 
  - `stdin`/`stdout`/`stderr` options

Not done for:
  - `execPath` option
  - `nodePath` option
  - `inputFile` option 
  - `file` argument

**Comment by ehmicky** [comment]
`inputFile` done at #630.

**Comment by ehmicky** [comment]
Only one missing: the `shell` option.
