### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by callumlocke** [sindresorhus/execa#46]
Could you release a new version with the `reject` option available?

**Comment by sindresorhus** [comment]
We need to reimplement some features that got lost (https://github.com/sindresorhus/execa/pull/27) when we stopped using the core `execFile` method:

- [ ] https://github.com/sindresorhus/execa/issues/30
- [ ] https://github.com/sindresorhus/execa/issues/32
- [ ] https://github.com/sindresorhus/execa/issues/34

Before that I'm not entirely confident we haven't broken stuff.

**Comment by jamestalmage** [comment]
Agreed.

We are still pre `1.0.0`, so as long as people are using sensible semver strings, a minor bump is basically a breaking one at this point anyways, but we are bound to get complaints if we upgrade before those are fixed.

**Comment by sindresorhus** [comment]
I still haven't had the time to look into the referenced issues and nobody has offered to help out. I've done a release now as we can't keep those issues holding up a release forever. Next time I won't merge such major changes before they're feature equal.
