### ISSUE TITLE
error from execFile is swallowed

### ISSUE THREAD

**Issue by KnisterPeter** [sindresorhus/execa#47]
If the file given to execFile is not executable the error result from execFile is swallowed.

**Comment by sindresorhus** [comment]
Can you provide minimal testcase? Can you try `master`? It has a lot of large changes.

**Comment by KnisterPeter** [comment]
I'll give it a try tomorrow and will provide even a PR if thats okay.

**Comment by kevva** [comment]
ping @KnisterPeter

**Comment by kevva** [comment]
I assume this is fixed?

> In master this does not fail anymore, but a test case if it may help to avoid regression

**Comment by sindresorhus** [comment]
A testcase was added in https://github.com/sindresorhus/execa/pull/49

**Comment by KnisterPeter** [comment]
Yes, my testcase is already merges. This could be closed.

Kevin Mårtensson <notifications@github.com> schrieb am Di., 6. Sep. 2016,
14:14:
