### ISSUE TITLE
Execa freezes when the child process using nodemon or process.on message listener

### ISSUE THREAD

**Issue by thetutlage** [sindresorhus/execa#471]
The issue is part of a bigger codebase, but I have been able to narrow it down and created this repo to help reproduce the issue https://github.com/thetutlage/execa-nodemon-freeze.

The README of the repo explains the issue in depth. But lemme also copy/paste it here.

---

The repo has a total of three files

- `index.js` just require the `nodemon` package
- `exec.js` runs the `node index.js` using the `execa` function.
- `exec-node.js` runs the `index.js` using `execa.node` function.

The `exec-node.js` freezes forever. I see that `nodemon` listens for `process.on('message')` event in `lib/utils/bus.js:28` file and if I remove this code form the `nodemon` source, then the `exec-node.js` script also dies successfully.

---

This may not be an issue and possible that I am missing some config/option needed to prevent the issue. But since, I am not able to get it working, I decided to report it as an issue

**Comment by sindresorhus** [comment]
You get the same hang if you replace `exec-node.js` with:

```js
const childProcess = require('child_process')

childProcess.fork('index', [])
```
