### ISSUE TITLE
Double quoting breaks command

### ISSUE THREAD

**Issue by mikestopcontinues** [sindresorhus/execa#472]
I'm trying to execute the following command:

```
cdk deploy -o .cdk --require-approval never --app "ts-node --files --require tsconfig-paths/register apps/workSitesCommon.ts" SitesCommon
```

But something's happening to the quotes so that that entire argument (`--app`) isn't being processed. Judging by the `escapedCommand` I can see from a (different) passing command, I believe the issue is that it's doubling the quotes (from `"` to `"\"...\""`). Running the command myself in the terminal does actually work.

**Comment by ehmicky** [comment]
Hi @mikestopcontinues,

Could you please copy the full line of code running `execa` (including which execa method is being used and which execa options are being passed)? Thanks.

**Comment by mikestopcontinues** [comment]
Sure, thanks! I tried it two ways. The former throws a shell error:

```ts
const cmd = `cdk deploy -o .cdk --require-approval never --app "ts-node --files --require tsconfig-paths/register apps/workSitesCommon.ts" SitesCommon`;

execa.command(cmd, {
    all: true,
    preferLocal: true,
    env,
  });
```

```
/bin/sh: -c: line 0: unexpected EOF while looking for matching ``'
/bin/sh: -c: line 1: syntax error: unexpected end of file
Subprocess exited with error 2
Error: Command failed with exit code 1: cdk deploy -o .cdk --require-approval never --app `ts-node --files --require tsconfig-paths/register apps/workSitesCommon.ts` SitesCommon
```

The latter ignores the `--app` arg.

```ts
const cmd = `cdk`;
const args =  [
  'deploy',
  '-o .cdk',
  '--require-approval never',
  '--app "ts-node --files --require tsconfig-paths/register apps/workSitesCommon.ts"',
  'SitesCommon',
];

execa(cmd, args, {
    all: true,
    preferLocal: true,
    env,
  });
```

**Comment by ehmicky** [comment]
Thanks.
You should try the following:

```js
const cmd = `cdk`;
const args =  [
  'deploy',
  '-o .cdk',
  '--require-approval never',
  '--app', 
  'ts-node --files --require tsconfig-paths/register apps/workSitesCommon.ts',
  'SitesCommon',
];

execa(cmd, args, {
    all: true,
    preferLocal: true,
    env, // Record<string, string>
  });
```

**Comment by mikestopcontinues** [comment]
Worked like a charm. Thanks!

**Comment by ehmicky** [comment]
More details on what the problem was, if you are curious.

Some characters have special meaning in shells. For examples, spaces are used to delimit arguments. To remove this special meaning, they must be escaped using shell-specific syntax, such as the double quotes around the `--app` value here.

However, this does not apply when executing a process outside of a shell. Without a shell, no escaping is needed. Therefore, the double quotes were interpreted as part of the `--app` value instead of being considered escaping characters. Same with the space between `--app` and its value.

**Comment by mikestopcontinues** [comment]
Thanks, that does help. With this particular project, I need to run a lot more commands via `execa`, so that get me through it. :)
