### ISSUE TITLE
Add silent support

### ISSUE THREAD

**Issue by Kikobeats** [sindresorhus/execa#475]
Hello,

I noted kill by timeout throws an error:

https://github.com/sindresorhus/execa/blob/9216ec8035f55a3ddcbf07de8667f9d9d5c40c84/lib/kill.js#L65

I wanted to ask if you will accept a PR to avoid throwing an error if `silent: true`. 

They are some use case scenarios (like force cleanup actions) where you don't want to throw an error.

That is an already thing used for other of your modules, e.g.,

https://github.com/sindresorhus/fkill-cli/blob/main/cli.js#L59

so does make sense for you to move that flag to live inside `execa`, so anybody that uses the library can take advantage of the flag?

**Comment by ehmicky** [comment]
Hi @Kikobeats,

I believe the [`reject: false` option](https://github.com/sindresorhus/execa#reject) might solve this problem. It is possible to differentiate timeouts from other error types by using the [`timedOut` property](https://github.com/sindresorhus/execa#timedout).

**Comment by Kikobeats** [comment]
Oh, I think it's enough for what I need. Thanks!
