### ISSUE TITLE
Spawn E2 BIG from a very large command.

### ISSUE THREAD

**Issue by TrofinSorin** [sindresorhus/execa#479]
I have a issue in spawning a big ffmpeg command with execa but the command has over 100.000 chars and i get E2 BIG. I looked into options and tried maxBuffer and other commands but didn't worked. What else can i do? I'm curious if it can be done with execa, if not i will split into multiple commands.

**Comment by ehmicky** [comment]
Hi @TrofinSorin,

Could you try by replacing Execa with [`child_process.spawn()`](https://nodejs.org/api/child_process.html#child_processspawncommand-args-options) and report if you're still experiencing this problem? Thanks!
