### ISSUE TITLE
Cannot work with typescript/ts-node at execa@6

### ISSUE THREAD

**Issue by moonrailgun** [sindresorhus/execa#481]
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

![image](https://user-images.githubusercontent.com/6964737/143010761-79907573-ef7c-4e4f-ae0c-0059145367f1.png)

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
