### ISSUE TITLE
caching output?

### ISSUE THREAD

**Issue by loynoir** [sindresorhus/execa#483]
If there's a time consuming command,
- want real time output to console
- want capture final output

Something similar to shell
```sh
ret=$(bash -c 'echo 1; sleep 2; echo 2'|tee /dev/stderr)
```

Currently I use
```js
    p.stdout?.pipe(process.stdout)
    p.stderr?.pipe(process.stderr)
    await p.then(p => ret = p)
```

**Comment by ehmicky** [comment]
Hi @loynoir,

Yes, this is the recommended way. The [following documentation](https://github.com/sindresorhus/execa#save-and-pipe-output-from-a-child-process) section describes it. 
Please note the last line of your example can be reduced to `const ret  = await p`.

**Comment by loynoir** [comment]
Oh, I know why, I tried it first in REPL, and use a small gap.

Seems `execa` is not caching output.
```js
> p=execa('bash',['-c','echo a; sleep 2; echo b']);void p.stdout.pipe(process.stdout)
... 3 seconds later ...
> ret=await p
> ret.stdout
''
```
