### ISSUE TITLE
About webpack-dev-server

### ISSUE THREAD

**Issue by qiYuei** [sindresorhus/execa#488]
I have a scenario where I need to start multiple VUE projects, and when one project runs with an error and the process exits, I want to terminate the other off-ramp processes that are running. I tried terminating the main process with process.exit(), but found that the asynchronous processes were still running

```js
const  scripts = [{path:'absolute path1',command:'run serve'},{path:'absolute path2',command:'run serve'}];

(async ()=>{
  for(let script of scripts ){
    try{
         await execa('npm', ['run', 'serve'],{ cwd:script.path, stdio: 'inherit'})
    }catch(e){
       process.exit()
    }
}
})()
```

What am I doing wrong?

![image](https://user-images.githubusercontent.com/48666945/148323084-322760e0-b437-45c2-8714-1a96689da515.png)

**Comment by ehmicky** [comment]
Hi @qiYuei,

Execa terminates child processes when the parent process exits, but not the "grandchildren" processes. In your case, `npm` is the child process, but it spawns its own "grandchildren" processes. 

Being able to terminate all descendants of a child process is being tracked in the following issue: https://github.com/sindresorhus/execa/issues/96
