### ISSUE TITLE
Version 6 is ESM only

### ISSUE THREAD

**Issue by soundstep** [sindresorhus/execa#489]
I guess there is no way to use execa `>= 6` in nodejs CommonJS projects?
I'm in a project where I can't add "type: module" in my package.json, that would be too big of a change.

This is a drastic change, why not export for both? Especially with all the drawbacks NodeJS ESM can have (file system, __dirname, path resolving, etc).

The error I got:

```
internal/modules/cjs/loader.js:1102
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module:app/node_modules/.pnpm/execa@6.0.0/node_modules/execa/index.js
require() of ES modules is not supported.
require() of app/node_modules/.pnpm/execa@6.0.0/node_modules/execa/index.js from app/scripts/check-version.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from app/node_modules/.pnpm/execa@6.0.0/node_modules/execa/package.json.
```

**Comment by sindresorhus** [comment]
You can use `await import()` to import it from CommonJS: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by soundstep** [comment]
Amazing working, thanks for the doc!

For others, in a NodeJS (14.x) CommonJS script:

```
(async () => {
        const execaCommand = (await import('execa')).execaCommand;
})();
```

**Comment by michaelgwelch** [comment]
> Amazing, working, thanks for the doc!
> 
> For others, in a NodeJS (14.x) CommonJS script:
> 
> ```
> (async () => {
>         const execaCommand = (await import('execa')).execaCommand;
> })();
> ```

I don't understand. You mean do this and then put your whole app inside of the closure? after the import of `execa`?

**Comment by michaelgwelch** [comment]
Sure thanks @ehmicky, I'm one of those trying to figure out how to consume in a CommonJS script. I have no experience with ESM at all. I'll be researching how to convert in the near future, I guess.

**Comment by seanmorrisonit** [comment]
Just been wrangling this one as well. Here's where we go to but am getting the error **A dynamic import callback was not specified.**

So for now we will stick with 5.1.1.

Source for this code: https://stackoverflow.com/questions/70545129/compile-a-package-that-depends-on-esm-only-library-into-a-commonjs-package
```
    let execa: typeof t_execa | undefined
    if (typeof execa == 'undefined') {
        const mod = await (eval(`import('execa')`) as Promise<
            typeof import('execa')
        >)
        ;({ execa } = mod)
    }
```

**Comment by waynebloss** [comment]
Does anyone know an alternative to this package that is not ESM only and that does support the AbortController?

**Comment by waynebloss** [comment]
Nevermind, thanks - I found the fork with the CJS version, published at https://www.npmjs.com/package/@esm2cjs/execa

**Comment by rashil-gopee** [comment]
This worked for me
`import execa = require('execa')`

**Comment by abejfehr** [comment]
I'm not able to use a top level await in node 20, I'm told that:
```
SyntaxError: await is only valid in async functions and the top level bodies of modules
```

**Comment by ehmicky** [comment]
Hi @abejfehr,

You need to use ES modules. Please see the [following instructions](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-move-my-commonjs-project-to-esm).
