### ISSUE TITLE
node Expected version "^12.20.0 || ^14.13.1 || >=16.0.0". Got "14.5.0"

### ISSUE THREAD

**Issue by srchulo** [sindresorhus/execa#495]
I'm getting the below error when installing:

`error execa@6.1.0: The engine "node" is incompatible with this module. Expected version "^12.20.0 || ^14.13.1 || >=16.0.0". Got "14.5.0"`

However, I have 14.5.0, which I believe is included in the ^14.13.1 listed above?

**Comment by sindresorhus** [comment]
`14.5.0` is lower than `14.13.1`.
