### ISSUE TITLE
Running a command in execa behaves differently from running the command manually in a shell

### ISSUE THREAD

**Issue by truesteps** [sindresorhus/execa#499]
Heya!

I've been trying to search some solutions to my issue all day... I'm using [oclif](https://oclif.io/) to create a CLI application, I wanted to simplify the publication process since it's multiple steps and I created a micro-cli app, which builds all distributions, uploads them to S3 and then publishes selected version on the stable channel.

I was wondering what's different in executing through execa and the native shell?

```JavaScript
const options = {
	shell: '/bin/zsh',
	cwd,
	env: process.env,
	preferLocal: true,
	localDir: cwd,
};
```

As you can see, I set the shell variable, set the CWD to the target directory but whenever I run the oclif command `oclif pack tarballs`, typescript or node or whatever seems to be unable to locate the submodules of my CLI application. If I run the same command manually in the workdir, it works perfectly.

I'm not sure where the issue lies, whether it's a typescript issue, oclif issue or the execution environment is just too different in `child_process.exec`, so it will never work.

Any help is appreciated, thank you <3!

// EDIT:
The error returned is `[MODULE_NOT_FOUND] ModuleLoadError Plugin: cli-app: [MODULE_NOT_FOUND] require failed to load {module_path}`.

The {module_path} is rewritten path to module by me to censor the error.

**Comment by ehmicky** [comment]
Hi @truesteps,

Do you manage to reproduce this problem using `child_process.exec()` instead? Since it does not have any `preferLocal` nor `localDir` option, you would need to use the absolute path of the binary (`oclif`) instead. Or, alternatively, installing `oclif` globally just for testing purpose.

**Comment by truesteps** [comment]
@ehmicky heya! I have oclif installed globally, I tried with full path and everything, I actually moved from `child_process.exec()` to `execa` in hopes of fixing this issue.

I tried supplying full path to binary oclif, locally build dev mode of oclif, and everything seems to crash on the ModuleLoader. If I call the same command I execute in `execa` or `child_process.exec()` manually in the zsh shell, everything passes as it should. I was thinking that path resolutions or whatever might be wrong but I set the process working dir, I set the environment variables but nothing seems to help. It got to a point at which I'm not sure what to debug even.

I'm thinking if there is some magic going on that the exec or execa dont have enough permissions or something so I tried to sed uid and gid but that didn't help either... I'm just at a loss

**Comment by truesteps** [comment]
update: I figured out that the `oclif manifest` command is the source of the issue.

**Comment by ehmicky** [comment]
Hi @truesteps,

I had a hint this was more of a Oclif issue indeed, which is what my initial question was aimed at confirming. :)
I'm glad you solved it, and thanks for sharing your solution!

**Comment by truesteps** [comment]
Yeah, i was desperate for any hints, that's why I posted here, since I assumed the runtime environment was different running something in a child_process that was something I thought is going on but that was totally misleading thinking from my part.
