### ISSUE TITLE
Release version w/ cross-spawn

### ISSUE THREAD

**Issue by albinekb** [sindresorhus/execa#50]
#42 
Could this one possibly be released? 0.4.1? 
So that we don't get the annoying warning in all packages using execa 👼 

Thanks!

**Comment by gerard2p** [comment]
I agree this would be great.

**Comment by zhuangya** [comment]
currently:

```
→ npm install execa
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
/Users/nos
└─┬ execa@0.4.0
  ├─┬ cross-spawn-async@2.2.4
  │ ├─┬ lru-cache@4.0.1
  │ │ ├── pseudomap@1.0.2
  │ │ └── yallist@2.0.0
  │ └─┬ which@1.2.10
  │   └── isexe@1.1.2
  ├── is-stream@1.1.0
  ├── npm-run-path@1.0.0
  ├── object-assign@4.1.0
  ├── path-key@1.0.0
  └── strip-eof@1.0.0
```

**Comment by zhuangya** [comment]
#46 related?

**Comment by dvmorris** [comment]
Any update on this? I am using a package that references execa through exec-buffer, and I keep getting this warning message.

**Comment by thisconnect** [comment]
I believe it was fixed in https://github.com/sindresorhus/execa/commit/345dc98186f27ece3d14a26a7ebc7233058569b6 but is not yet on npm

**Comment by dvmorris** [comment]
Can I do anything to help get it published?

**Comment by kevva** [comment]
https://github.com/sindresorhus/execa/issues/46#issuecomment-229478914
