### ISSUE TITLE
Using double quotes as part of the arguments

### ISSUE THREAD

**Issue by jjtang1985** [sindresorhus/execa#501]
Hi execa experts,

I would like to run the following command via `execa`:

``` shell
npm deprecate my-package@"< 1.20.0"
```

But I got an error below:
` Invalid tag name ""<1.20.0"": Tags may not have any characters that encodeURIComponent encodes.`

It seems the command with double quotes is handled differently.
Could you please share the best practice in my case?

Here is my code snippets:
```
// example 1
execa('npm', ['deprecate', `my-package@"< 1.20.0"`]);
// example 2
execa.commandSync(`npm deprecate my-package@"< 1.20.0"`);
```

Thank you very much in advance.

**Comment by ehmicky** [comment]
Hi @jjtang1985,

Unless you're using the `shell: true` option, there is no need to quote/escape. Quote characters, spaces, etc. are left as is. Please note this is not specific to Execa, and you would experience the same issue using `child_process.spawn()` instead.

In your case, I believe the following might work:

```js
execa('npm', ['deprecate', 'my-package@< 1.20.0']);
```

Or:

```js
execa('npm', ['deprecate', 'my-package@<1.20.0']);
```

**Comment by jjtang1985** [comment]
Hi @ehmicky ,

Thank you for your quick response.

I tried your suggestion `execa('npm', ['deprecate', 'my-package@< 1.20.0'])` before actually and here is the error.
```
'my-package@< 1.20.0' is not in the npm registry.
```

I guess the double quotes are needed for this specific npm command.
Here is one example below, where you can find in the npm [doc](https://docs.npmjs.com/cli/v7/commands/npm-deprecate):
```
npm deprecate my-thing@"< 0.2.3" "critical bug fixed in v0.2.3"
```

**Comment by ehmicky** [comment]
The npm doc is showing a command that's to be executed in a shell. However, in this case, `execa()` does not use a shell, so the quotes will be left as is.

What output do you get with the second suggestion?

```js
execa('npm', ['deprecate', 'my-package@<1.20.0'])
```

Also, what do you get when using `child_process.spawn()` instead?

```js
child_process.spawn('npm', ['deprecate', 'my-package@<1.20.0']))
```

**Comment by jjtang1985** [comment]
For the second suggestion,
```
execa('npm', ['deprecate', 'my-package@<1.20.0'])
```
it showed me the the same error message.

If I switch to `spawn`, there will not be any errors anymore.
Unfortunately, the command did nothing, as the package was not deprecated.

**Comment by jjtang1985** [comment]
@ehmicky ,

I solved the issue by the following steps:
1. update npm to v8 from v6, as it seems v6 has authentication issues.
2. npm login (again after updating)

After that, both of your suggestions worked fine.

I'll close the ticket.
Thank you.
