### ISSUE TITLE
Getting output from cmd live (uploadbar)

### ISSUE THREAD

**Issue by ramonbrooks456** [sindresorhus/execa#504]
I have a cmd script that uploads a file to cloud drive(mega). when i run the file using command prompt i can get upload status a bar,file size uploaded,file size remaining etc. I ran the same command using execa it uploads the file and gets final output like upload finished but not the progress bar.

Is there any way to get progress bar in terminal when i run the script in node?

the code i used is this

```javascript
const data = await execa("file-name",{shell:true,all:true}).stdout.pipe(process.stdout);
```

**Comment by ehmicky** [comment]
Hi @ramonbrooks456,

The `await` execution should be this instead ([see example](https://github.com/sindresorhus/execa#save-and-pipe-output-from-a-child-process)):

```js
const childProcess = execa("file-name", { shell:true, all:true })
childProcess.stdout.pipe(process.stdout)
const result = await childProcess
```

Also, if you want to redirect both `stdout` and `stderr`, you should use `childProcess.all` and `result.all`:

```js
const childProcess = execa("file-name", { shell:true, all:true })
childProcess.all.pipe(process.stdout)
const {all: data } = await childProcess
```
