### ISSUE TITLE
why unref 

### ISSUE THREAD

**Issue by hwen** [sindresorhus/execa#508]
Hey guys, Got confused while reading the code. 
Why need to unref the timeout? If parent process exited then spawned child process would't send SIGKILL. Then if may not guarantee the SIGKILL signal sent.
Thank you for solving my confusion.

```js
const setKillTimeout = (kill, signal, options, killResult) => {
	if (!shouldForceKill(signal, options, killResult)) {
		return;
	}

	const timeout = getForceKillAfterTimeout(options);
	const t = setTimeout(() => {
		kill('SIGKILL');
	}, timeout);

	// Guarded because there's no `.unref()` when `execa` is used in the renderer
	// process in Electron. This cannot be tested since we don't run tests in
	// Electron.
	// istanbul ignore else
	if (t.unref) {
		t.unref();
	}
};
```

**Comment by ehmicky** [comment]
Hi @hwen,

If the child process was run in the background (see [`detached` option](https://github.com/sindresorhus/execa#detached)), the parent process might exit before its child. If the parent process has called `.kill()` right before exiting, without this `unref()` call, it would wait 5 seconds before exiting (even if the child process already exited with the `SIGTERM`).
