### ISSUE TITLE
Command was killed with SIGSEGV

### ISSUE THREAD

**Issue by azickri** [sindresorhus/execa#514]
Hello, i was trying execa with ffprobe for get video meta data.
And i get response error **Command was killed with SIGSEGV**. Like in image.

Any solving from this error?

![image](https://user-images.githubusercontent.com/45684749/208244526-d4ddfb87-9e1b-487c-ae7b-bc0306585d91.png)

-------

Spec VM:
- Ubuntu 22.04 LTS
- RAM 4GB
- Disk 20GB
- Node 14.18.2

-------

My Code:

```ts
import * as execa from 'execa';
import * as ffprobe from '@ffprobe-installer/ffprobe';

private async isValidDuration(videoUrl: string) {
  try {
    if (!videoUrl) return true;

    const params = ['-v', 'error', '-show_format', '-show_streams'];
    const { stdout } = await execa(ffprobe.path, [...params, videoUrl]);

    const duration = stdout.match(/duration="?(\d*\.\d*)"?/)[1];

    if (Number(duration) > 60) {
      return false;
    }

    return true;
  } catch (_) {
    return true;
  }
}
```

**Comment by ehmicky** [comment]
Hi @azickri,

What happens if you replace the `execa()` call with `child_process.execFile()` instead?

```ts
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import * as ffprobe from '@ffprobe-installer/ffprobe';

const pExecFile = promisify(execFile);

private async isValidDuration(videoUrl: string) {
  try {
    if (!videoUrl) return true;

    const params = ['-v', 'error', '-show_format', '-show_streams'];
    const { stdout } = await pExecFile(ffprobe.path, [...params, videoUrl]);

    const duration = stdout.match(/duration="?(\d*\.\d*)"?/)[1];

    if (Number(duration) > 60) {
      return false;
    }

    return true;
  } catch (_) {
    return true;
  }
}
```

**Comment by azickri** [comment]
I will try that..

**Comment by azickri** [comment]
![image](https://user-images.githubusercontent.com/45684749/208245855-baa8ffa5-3be0-4124-9a18-0fb960a745b3.png)

Still same response.. Buts, in local computer work normally but in this VM cant work

**Comment by azickri** [comment]
I Think, this issue from package ffprobe, right?

**Comment by ehmicky** [comment]
If the response is the same when using `child_process` instead of Execa, this problem is unrelated to Execa.
This seems to be an issue with [`node-ffprobe`](https://github.com/ListenerApproved/node-ffprobe), where you might want to be create an issue instead.

**Comment by azickri** [comment]
Okay, thanks for your time.
