### ISSUE TITLE
Make `.killed === true` regardless of how it was killed

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/execa#52]
See: https://github.com/sindresorhus/execa/pull/48/files#r71061011

**Comment by SamVerschueren** [comment]
I was looking into implementing this but I need some help first. In the `spawned.on('exit')` handler I wanted to set `spawned.killed` to `true` if the signal indicates that it was killed. But what signals indicate a kill? Or can we check it in a different way?

I was now checking for `SIGTERM` and `SIGINT` but don't think that's enough.

**Comment by okonet** [comment]
@SamVerschueren I think https://github.com/Tapppi/async-exit-hook/blob/master/index.js#L89-L94 is a good enough list

**Comment by ehmicky** [comment]
I've opened [an issue with Node.js](https://github.com/nodejs/node/issues/27490) to make `childProcess.killed` `true` even when the child process was killed through `process.kill()` or `kill` in the terminal (as opposed to `childProcess.kill()`).

**Comment by bnoordhuis** [comment]
> But what signals indicate a kill?

If `signal != null` in `proc.on('exit', (code, signal) => { /* ... */ })`, then that's the signal that terminated the process.

If your question is "how do I determine whether it's sent by kill(2)", the answer is "you don't." :-)

**Comment by ehmicky** [comment]
Yes I think @bnoordhuis fix for it (checking `signal` on `exit`) is the correct one. However I still think that providing this as part of Node.js might be a good idea (as opposed to `execa`).

**Comment by ehmicky** [comment]
From the discussion at https://github.com/nodejs/node/issues/27490, it appears `childProcess.killed` just means "childProcess.kill()" was called. Regardless of whether it terminated the process. For example `childProcess.kill(0)` sets `.killed` as `true`. The purpose of `.killed` seems to be mostly about idempotency, e.g. preventing calling `.kill()` multiple times.

Instead, that discussion highlights that the best way to check this is to look at the `signal` that is passed as a second argument to the `exit` event of the child process.

In other words, we might want to replace:

https://github.com/sindresorhus/execa/blob/fcf648e21b6ccc9ec279fb758318ed7581f02fc6/lib/error.js#L84

By:

```js
error.killed = error.signal !== undefined;
```

The [documentation](https://nodejs.org/api/child_process.html#event-exit) says:

| signal [<string>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) The signal by which the child process was terminated.

So, we can assume that if a signal is passed, it was the one that terminated the child process.

What do you think?

**Comment by sindresorhus** [comment]
👍

We should document that it differs from the one in Node.js.

**Comment by ehmicky** [comment]
`childProcess.killed` is actually left as is by Execa. It is `execaError.killed` which should be fixed.

I also got confused between those two properties while checking this issue. I am wondering whether we should rename `execaError.killed` to avoid that confusion? For example `execaError.aborted`, `execaError.terminated`, or anything else?

**Comment by ehmicky** [comment]
Sounds good. Done at #625.
