### ISSUE TITLE
Help for sophisticated command

### ISSUE THREAD

**Issue by ttxtosca** [sindresorhus/execa#521]
Hello,

I've used execa successfully many times. But I struggle for a command like this : 

```bash
ffmpeg -ss 5 -i input.mp4 -t 1 -vf cropdetect -f null - 2>&1 | awk '/crop/ {print $NF}' | tail -1
```

Can anyone help me to deal with this kind of command with execa ? Difficulty come with dash between 'null' {dash} and the rest of that line after the pipe. By the way, command is totally valid on any unix shell having ffmpeg available.

Thank you

**Comment by ehmicky** [comment]
Hi @ttxtosca,

Side note: Bash allows using `|&`, which is a shortcut for `2>&1 |`.

```bash
ffmpeg -ss 5 -i input.mp4 -t 1 -vf cropdetect -f null - |& awk '/crop/ {print $NF}' | tail -1
```

You can use this:

```js
const ffmpegProcess = execa('ffmpeg', ['-ss', '5', '-i', 'input.mp4', '-t', '1', '-vf', 'cropdetect', '-f', 'null', '-'])
const awkProcess = execa('awk', ['/crop/ {print $NF}'])
const tailProcess = execa('tail', ['-1'], { stdout: 'inherit' })

ffmpegProcess.stderr.pipe(awkProcess.stdin)
awkProcess.stdout.pipe(tailProcess.stdin)
```

However, you might not need `awk` and `tail`, as you can implement both in Node.js, which is faster, requires less memory and more cross-platform.

```js
const { stderr } = await execa('ffmpeg', ['-ss', '5', '-i', 'input.mp4', '-t', '1', '-vf', 'cropdetect', '-f', 'null', '-'])
const cropField = stderr
  .split('\n')
  .find(line => line.includes('crop='))
  .split(' ')
  .at(-1)
console.log(cropField)
```

Please note this question is not quite specific to Execa, but to Node.js `child_process` execution in general. :)

**Comment by ttxtosca** [comment]
Hello @ehmicky,

Thank you for this fast and complete answer. Indeed, this question refers a bit to another field than execa. But I know the level of precision we can found around here :)

The first solution seems ok, I'll try it soon ; the second one makes sense too and is what I would have end if still struggling.

Anyway, sorry for my rusted english and thanks again for the answer.

**Comment by ehmicky** [comment]
Great!
Your English is very good @ttxtosca :)
