### ISSUE TITLE
Default `preferLocal` to `true` when using `$`

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#522]
The default value for [`preferLocal`](https://github.com/sindresorhus/execa#preferlocal) used to be `true`. We changed it to `false` in #314 because it conflicted with some uncommon setups (#196, #153). IMHO `preferLocal` is still a very helpful option for most users, and it's too bad we cannot enable it by default due to the above.

Now, I am wondering whether the default value should be `true` with the new `$` methods we just introduced? The reasons for this is:
  - It is easier for users with the uncommon setups mentioned above to change the default value thanks to the options binding method: `const $$ = $({ preferLocal: false })`
  - `$()` is more likely than `execa()` to be used in a script with many commands to execute. This increases the chance of at least one of them to be a local binary.

What do you think @sindresorhus and @aaronccasanova?

**Comment by sindresorhus** [comment]
I agree. `true` is a better default for scripting. We need to clearly document the behavior though.

**Comment by ehmicky** [comment]
Great, let's do this then!
@aaronccasanova Woud you like to take this up, as this relates to the `$` API? Otherwise, I'm also happy to do it.

**Comment by aaronccasanova** [comment]
I like it 👍 Feel free to pick this one up @ehmicky!

If I'm not mistaken it should be a quick update to `export const $ = create$({preferLocal: true});` here:
https://github.com/sindresorhus/execa/blob/eae327cc0a49f61b17f699b9199c7953e1497c1a/index.js#L245

**Comment by ehmicky** [comment]
Done at #529. :+1:
