### ISSUE TITLE
`${childProcessResult}` shortcut notation

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#523]
[zx](https://github.com/google/zx/) has a `${childProcessResult}` shortcut notation:

```js
const branch = await $`git branch --show-current`
await $`dep deploy --branch=${branch}`
```

This is equivalent to:

```js
const branch = await $`git branch --show-current`
await $`dep deploy --branch=${branch.stdout.replace(/\n$/, '')}`
```

This is quite handy and would be minimal to implement for us as part of the new `$` API. 
What do you think @sindresorhus @aaronccasanova?

**Comment by aaronccasanova** [comment]
Agreed, this would be a nice and subtle DX improvement. Two initial thoughts:
1. Is there currently anything to key off of and identify the return value is a `childProcessResult`?
2. Would this only work for string encodings? e.g.
```js
const branch = await $({encoding: null})`git branch --show-current`
await $`dep deploy --branch=${branch}` // <- Would parseTemplates convert the buffer to a string?
```

**Comment by ehmicky** [comment]
> 1. Is there currently anything to key off of and identify the return value is a childProcessResult?

It is a plain object:

https://github.com/sindresorhus/execa/blob/eae327cc0a49f61b17f699b9199c7953e1497c1a/index.js#L141-L152

I think just checking if the value is a plain object with a `stdout` key might be enough?

> 2. Would this only work for string encodings?

That's a great question! Considering the arguments are escaped and passed as is, I think we might allow buffer encodings? I.e. if `Buffer.isBuffer(stdout)`, we would use `stdout.toString()`. One thing to note though is that `child_process.spawn()` throws if any argument contains a null byte.

However, if `options.stdout` is `inherit`, `childProcessResult.stdout` will be `undefined`. In that case, we might want to throw an error, as this mostly likely indicates a user error.

**Comment by sindresorhus** [comment]
> I think just checking if the value is a plain object with a stdout key might be enough?

That sounds fine. If we really want to ensure users don't pass in something incorrect, we can add an internal `Symbol` to the returned object and check for that.

**Comment by sindresorhus** [comment]
I like it 👍

**Comment by ehmicky** [comment]
@aaronccasanova Would you be interesting in implementing it? If not, no worries! :)

**Comment by aaronccasanova** [comment]
I have bandwidth to help out with this update 👍 I'll likely need some assistance dialing in the right test cases, but I'll push up a draft implementation and we can go from there!
