### ISSUE TITLE
If the `env` option is omitted, the `extendEnv` option will not work

### ISSUE THREAD

**Issue by sounisi5011** [sindresorhus/execa#527]
The `extendEnv` option will not work if the `env` option is an `undefined` value.

For example, this code does not extend the environment variable:

```js
import { execa } from 'execa';

const { stdout } = await execa('/bin/sh', ['-c', 'echo $LANG'], {
  extendEnv: false,
  env: {},
});
console.log(stdout);
// => ''
```

This works as expected.

However, if the `env` option is omitted, the environment variable will be extended unintentionally:

```js
import { execa } from 'execa';

const { stdout } = await execa('/bin/sh', ['-c', 'echo $LANG'], {
  extendEnv: false,
  // env: {},
});
console.log(stdout);
// => 'ja_JP.UTF-8'
```

This behavior is also the case when `null`, `false`, `0`, `NaN`, `""`, etc. are passed for `env` options.

```js
import { execa } from 'execa';

const { stdout } = await execa('/bin/sh', ['-c', 'echo $LANG'], {
  extendEnv: false,
  env: NaN, // Same for all falsy values, not just `undefined` and `null`
});
console.log(stdout);
// => 'ja_JP.UTF-8'
```

This is caused by the `child_process` module replacing the `env` option with `process.env` when [a falsy value](https://developer.mozilla.org/docs/Glossary/Falsy) is passed.

https://github.com/nodejs/node/blob/v14.18.0/lib/child_process.js#L586

Therefore, I think [the `getEnv` function](https://github.com/sindresorhus/execa/blob/eae327cc0a49f61b17f699b9199c7953e1497c1a/index.js#L18-L26) needs to be fixed.

```diff
 const getEnv = ({env: envOption, extendEnv, preferLocal, localDir, execPath}) => {
-	const env = extendEnv ? {...process.env, ...envOption} : envOption;
+	const env = extendEnv ? {...process.env, ...envOption} : (envOption || {});

 	if (preferLocal) {
 		return npmRunPathEnv({env, cwd: localDir, execPath});
 	}

 	return env;
 };
```

**Comment by ehmicky** [comment]
Hi @sounisi5011,

Thanks for reaching out, that's an interesting question.

I think it depends on what `extendEnv: false` means. It can be either:
  1. Do not use `process.env`
  2. If `env` is specified (with a correct type), do not use `process.env`

At the moment, the behavior is matching `2.`, while you are expecting `1.`.

Some users might expect `1.`. For example, a library might allow its users to optionally pass some environment variables, which would override `process.env`. It might then use `extendEnv: false`, but let `env` be optionally `undefined`. In that case, they would expect `extendEnv: false` + `env: undefined` to result in `process.env` being used.

Also, changing the behavior from `2.` to `1.` would be a breaking change. Based on this, I would lean towards fixing the documentation instead, although it currently is already hinting at the current behavior:

> Set to `false` if you don't want to extend the environment variables **when providing** the `env` property.

**Comment by sounisi5011** [comment]
I had not thought of the `2.` possibilities.
I thought this was a bug, but apparently this is an intentional behavior.
