### ISSUE TITLE
Add `pipeStdin()` method

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#534]
#531 added `pipeStdout()`, `pipeStderr()` and `pipeAll()` to redirect a child process's `stdout`/`stderr` to another process, a stream or a file.

For completeness and convenience, we should add a similar `pipeStdin()` which would redirect another process `stdout`, stream or file to a child process `stdin`.

This pattern is currently already documented in [our Tips section](https://github.com/sindresorhus/execa#redirect-input-from-a-file).

```js
const subprocess = execa('cat')
fs.createReadStream('stdin.txt').pipe(subprocess.stdin)
await subprocess
```

This would simplify it to:

```js
await execa('cat').pipeStdin('stdin.txt')
```

**Comment by sindresorhus** [comment]
`await execa('cat').pipeStdin('stdin.txt')` reads to me as we are piping `cat` into `stdin.txt`, but we are doing the reverse.

Maybe:

```js
await execa('cat').pipeToStdinFrom('stdin.txt')
```

**Comment by ehmicky** [comment]
Yes, I was also thinking users might not realize things are done from a reverse direction than `pipeStdout()` and the likes. `pipeToStdinFrom()` sounds good :+1:

**Comment by ehmicky** [comment]
I implemented it but it feels like this method is not as useful as `pipeStdout()`/`pipeStderr()`/`pipeAll()`:
  - Users might be confused about the direction being reversed from `pipeStdout()`
  - Unlike `pipeStdout()`, the flow of data is different from the flow of the code. It makes more sense for processes that are later in the pipe order to come last in the code itself. The current pattern `` $({ input: process.stdin })`cat` `` follows that order, but not `` $`cat`.pipeToStdinFrom(process.stdin) ``
  - The `input` option already fills this feature for streams and raw data. When it comes to processes, `pipeStdout()` can be used, after flipping the processes in the code. 

So the only thing that `pipeToStdinFrom()` would facilitate is to be a shortcut when reading from a file, allowing to specify `'input.txt'` instead of `fs.createReadStream('input.txt')`. 

Based on this, I do not think it is worth the additional complexity.

On the other hand, we could improve the documentation to highlight the above patterns.

**Comment by sindresorhus** [comment]
I agree with your assessment.

**Comment by sindresorhus** [comment]
Do you think a `` `$({inputFromFile: 'input.txt'})`cat` `` option would be useful as a shortcut? Piping from a file is quite a common use-case.

**Comment by ehmicky** [comment]
Yes, I agree it would. 

Naming-wise, would `inputFile` be good too? I am wondering whether it might shorter yet clear enough. :thinking:

**Comment by sindresorhus** [comment]
`inputFile` is good 👍

**Comment by ehmicky** [comment]
Done in #542.
