### ISSUE TITLE
execa.shell(cmd, {shell: '/bin/bash'}) only runs the first word of command

### ISSUE THREAD

**Issue by jatins** [sindresorhus/execa#54]
Let's say that I have to run `man ls` command.

```js
// runs correctly, with man page of 'ls' in stdout
execa.shell('man ls')
  .then(function (result) {
    console.log(`stdout: ${result.stdout}`)
    console.log(`stderr: ${result.stderr}`)
  })
```

but 

```js
// this just runs 'man'
execa.shell('man ls', {shell: '/bin/bash'})
  .then(function (result) {
    console.log(`stdout: ${result.stdout}`)
    console.log(`stderr: ${result.stderr}`)
  })
```

**Output**
```
stdout: 
stderr: What manual page do you want?
```

**Comment by sindresorhus** [comment]
What OS and Node.js version are you on? Works fine for me.

**Comment by sindresorhus** [comment]
`execa.shell('man ls', {shell: '/bin/bash'}, (error, stdout, stderr) => {` is also invalid. This module has a Promise interface.

**Comment by jatins** [comment]
Ah, sorry about that code. I pasted parts of some child_process code I was experimenting with. But I am still seeing the issue. Updated the code.

```sh
$ node -v 
v6.3.0
```

execa version 0.4.0

OS: OSX El Capitan (10.11.5)
