### ISSUE TITLE
$ hangs forever when using grep or ripgrep commands

### ISSUE THREAD

**Issue by acheronfail** [sindresorhus/execa#548]
#### Steps to reproduce

1. `echo '{"type":"module","dependencies":{"execa":"7.1.0"}}' > package.json`
2. `yarn` or `npm install`
3. ``echo 'import {$} from "execa"; const result = await $`rg foobar`; console.log(result);' > index.js``
4. `node index.js`

#### Expected behaviour

The command is run, and when complete, the `result` variable is logged to the console.

#### Actual behaviour

It hangs forever, and I don't know why. Here's the output even with debug environment variables:

```
❯ NODE_DEBUG=execa node index.js
[20:24:55.414] rg foobar
```

(hangs forever after that).

I've also confirmed that running `rg foobar` by itself in the console returns almost immediately, so it's not a long-running search or anything like that.

#### Other comments

* I initially saw this with `rg`, but it also does the same things with `grep`.
* Using Linux `6.1.15-1-lts` (Arch)
* Using Node `v18.15.0` (lts)

**Comment by ehmicky** [comment]
Hi @acheronfail,

This seems to be due to this (from the `ripgrep` man page):

> ripgrep will automatically detect if stdin exists and search stdin for a regex pattern, e.g. ls | rg foo. In some environments, stdin may exist when it shouldn’t. To turn off stdin detection explicitly specify the directory to search, e.g. rg foo .

By default, Execa's [`stdin` option](https://github.com/sindresorhus/execa#stdin) is `inherit`, which means it is waiting for input forever. You can fix this using either: 

```js
const result = await $({ stdin: 'ignore' })`rg foobar`
```

Or:

```js
const result = await $`rg foobar .`
```

**Comment by ehmicky** [comment]
[`7.1.1`](https://github.com/sindresorhus/execa/releases/tag/v7.1.1) was released where the default value for `stdin` is now `inherit`, so you should now be able to just do:

```js
const result = await $`rg foobar`
```
