### ISSUE TITLE
Default `stdin` to `inherit` with `$`

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#549]
By default, `stdin` is `pipe` for all Execa methods, including `$`. This allows `childProcess.stdin.pipe()` to be used, and is also a requirement when using the `input` or `inputFile` option.

However, some commands detect this as "stdin is being piped/used", and hang forever. This was reported for example in https://github.com/sindresorhus/execa/issues/548 for ripgrep. 

Also, requesting user input is not uncommon in shell scripts.

zx fixed that by making `stdin` default to `inherit`, while keeping `stdout`/`stderr` default to `pipe`. 

https://github.com/google/zx/blob/main/src/core.ts#L146

I think we should do the same, with the following exceptions: 
  - Only for `$`, since it makes more sense in "shell-like" scripts. Also to avoid breaking every `execa()` user currently using `childProcess.stdin.pipe()` (which fails when `stdin` is `inherit`).
  - Not if the `input` or `inputFile` option is used.

Note: since `$` just got released, I am not sure whether this would be technically a breaking change or a bug fix. :thinking: 

What do you think?

**Comment by aaronccasanova** [comment]
Initially, my intention for `$` was to create a thin wrapper around the main `execa()` API that would allow users to use familiar options and defaults with a new syntax. However, as the implementation progressed and we began documenting `$`, it became clear that the story and application of this API was best framed around shell-like scripting, as opposed to being a drop-in replacement for `execa()` (which I fully supported).

This shift in intention resulted in the first divergence from the `execa()` default options. The `preferLocal` option was set to `true` on the `$` API, as it's a more sensible default option for scripting (another decision I fully supported).

With that in mind, I believe changing the default `stdin` option to `inherit` aligns well with the vision for `$` to be a powerful tool for shell-like scripting.
