### ISSUE TITLE
Idea: Use cancelable promise

### ISSUE THREAD

**Issue by andywer** [sindresorhus/execa#55]
First of all thank you for this cool package! :)

I think one rather basic feature is still missing: Being able to cancel the child process easily. Using a cancelable promise (https://www.npmjs.com/package/cancellable or similar) seems like a good idea.

But maybe there is already another way?

**Comment by sindresorhus** [comment]
There already is an easy way to do it:

```js
const cp = execa('sleep', ['5']);
cp.kill();
```

**Comment by jamestalmage** [comment]
Has that been released yet?

**Comment by sindresorhus** [comment]
@jamestalmage Yes, that was already part of the interface even before the rewrite.

**Comment by andywer** [comment]
@sindresorhus Is it an undocumented feature? At least I was not able to find this information ;)

**Comment by sindresorhus** [comment]
It's documented. Although indirectly.

**Comment by SamVerschueren** [comment]
I think we can close this?
