### ISSUE TITLE
bug: Incorrect Execution of command with Script API

### ISSUE THREAD

**Issue by davbrito** [sindresorhus/execa#554]
The docs currently states that you can do this:
![image](https://user-images.githubusercontent.com/39559632/225432649-01d100a7-2e90-465c-b925-8ede4b4040ec.png)

But doing that currently results in an incorrect command:
![Exampla using the node REPL](https://user-images.githubusercontent.com/39559632/225433079-833713ef-2b91-4ce2-ad90-d7e5b9655fb4.png)

**Comment by ehmicky** [comment]
Hi @davbrito,

I believe this bug must have been fixed with [Execa `7.1.1`](https://github.com/sindresorhus/execa/releases/tag/v7.1.1), specifically by #553. Can you check with that version?

**Comment by davbrito** [comment]
> Hi @davbrito,
> 
> This bug has been fixed with [Execa `7.1.1`](https://github.com/sindresorhus/execa/releases/tag/v7.1.1) which was released yesterday, specifically by #553. Can you check with that version?

Oh, thanks. I didn't notice that new release. 
It woks perfect now. 🚀
