### ISSUE TITLE
With solidjs

### ISSUE THREAD

**Issue by kamalkech** [sindresorhus/execa#558]
with a simple usage i get error this code in solidjs

```typescript
import type { Component } from 'solid-js';
import {execa} from 'execa';

const App: Component = () => {
  const search = async () => {
    console.log(1)
    const {stdout} = await execa('echo', ['unicorns']);
    console.log(stdout);
  }

  return (
    <>
      <h1>Open browser</h1>
      <button type="button" onClick={search}>Open</button>
    </>
  );
};

export default App;
```

the error: ```caught ReferenceError: process is not defined```

**Comment by ehmicky** [comment]
Hi @kamalkech,

Thanks for reaching out. However, this issue would be better answered on https://github.com/solidjs/solid than on Execa, since you would encounter the same issue when using `child_process` directly instead of `execa`.

**Comment by kamalkech** [comment]
@ehmicky the same issue with reactjs / nextjs !!! i will check sveltejs and i see

**Comment by ehmicky** [comment]
What do you get when calling `console.log(process)` before the Execa statement?

**Comment by kamalkech** [comment]
@ehmicky i get any thing because the app crashed with the error: ```caught ReferenceError: process is not defined```

**Comment by ehmicky** [comment]
You would first need to remove the execa import statement and call, then call `console.log(process)`.

**Comment by kamalkech** [comment]
@ehmicky the same error, can you share any example using reactjs, sveltejs or solidjs ?? thank u

**Comment by ehmicky** [comment]
If the error is the same, but Execa was completely removed from the code, it means your file is not run with Node.js. `process` is a global variable available in Node.js environment. Execa is a Node.js library, therefore it needs to run with Node.js.

In other words, this problem is not related to Execa itself: you would get the same error using any other library that can run only on Node.js with your specific setup.

**Comment by kamalkech** [comment]
@ehmicky first of all thank for ur time and answer to all my question, i found one thing that s u can use execa just in server mode not in client mode, when i move my code to the api of nextjs it s works good
