### ISSUE TITLE
Fix `shell` option in `execa.shell()` on Windows

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/execa#56]
Added in https://github.com/sindresorhus/execa/commit/a80487b106e1427fc927521b52e113adb8016512, but seems tests on Windows were failing then.

**Comment by jamestalmage** [comment]
Windows tests are passing. Is this still an issue?

**Comment by sindresorhus** [comment]
@jamestalmage Still failing: https://github.com/sindresorhus/execa/blob/9cd5e2a39105fe3a366a0dc83ccac4ed2146f585/test.js#L394-L401
