### ISSUE TITLE
feature request: allow node 17

### ISSUE THREAD

**Issue by silence48** [sindresorhus/execa#561]
Cloudflare workers supports at latest node 17.9.1 but I get an error using your package version 7.1.1 because it seems to exclude node 17.
<html>
<body>

15:14:49.686 | error execa@7.1.1: The engine "node" is incompatible with this module. Expected version "^14.18.0 \|\| ^16.14.0 \|\| >=18.0.0". Got "17.9.1"
-- | --
15:14:49.699 | error Found incompatible module.

</body>
</html>

**Comment by ehmicky** [comment]
Hi @silence48,

Node 17 is [not officially supported anymore](https://github.com/nodejs/Release) by Node.js. Unfortunately, we do not support Node.js versions that are not officially supported anymore.

**Comment by silence48** [comment]
Thanks for the reply. I fixed it with yarn and a .yarnrc to ignore the
requirement. Leaving this comment in case it helps the next person
