### ISSUE TITLE
[Docs]: Release 8.0.0 lists Breaking Change to require node 16.7+, but package.json requires node 16.17+

### ISSUE THREAD

**Issue by kdecelle** [sindresorhus/execa#573]
Release notes for 8.0.0 specify a Breaking Change, requiring node version 16.7.0 or greater: https://github.com/sindresorhus/execa/releases/tag/v8.0.0

The package.json file specifies 16.17.0 or greater: https://github.com/sindresorhus/execa/blob/f4b8b3ab601c94d1503f1010822952758dcc6350/package.json#L19

If the package.json code is accurate, the release notes need to be updated with the correct version.

**Comment by ehmicky** [comment]
Thanks @kdecelle, great catch!
I just fixed the release notes for `8.0.0`.
