### ISSUE TITLE
Undefined and null argument variables are passed as strings

### ISSUE THREAD

**Issue by stigok** [sindresorhus/execa#59]
Undefined and null variables are passed to child process as their string representations, `"undefined"` and `"null"`. I'm not sure what the *expected* behavior is, but when working with shell scripts, I expect the undefined or null arguments to be passed as empty strings.

**Comment by sindresorhus** [comment]
This is how built-in `child_process` works too:


```js
console.log(process.argv.join(' '));
```

```
> require('child_process').execFileSync('node', ['t.js', undefined, null]).toString()
'/usr/local/bin/node /Users/sindresorhus/Downloads/t.js undefined null\n'
```

**Comment by schnittstabil** [comment]
The current behavior seems reasonable to me, AFAIK `null` and `undefined` are always treated that way:
```js
> null + ''
'null'
> undefined + ''
'undefined'

> String(null)
'null'
> String(undefined)
'undefined'
```

**Comment by stigok** [comment]
Ok. Thanks for the feedback :+1:
