### ISSUE TITLE
Add `stdin: Iterable` option

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#593]
We could allow the `stdin` option to be a sync/async iterable (of strings or byte integers).

This would replace the `input` option, since `stdin: [string]` could be used instead.

Augmenting the `stdin` option instead of having a separate `input` option is more in line with the designs proposed in #591 and #592.

Also, being able to pass any iterable to `stdin` can have multiple use cases. For example, this would allow using a `function *()` generator to pass inputs to a process.

**Comment by sindresorhus** [comment]
Sounds good. I think it would also be useful to make `stdin` support a `ReadableStream` (web stream).

I don't think it's worth deprecating `input` yet though. It would be a huge breaking change. We can rather just recommend `stdin` in the `input` docs for now.

**Comment by ehmicky** [comment]
Sounds good. :+1: 

I added another issues for web streams, sounds good too: https://github.com/sindresorhus/execa/issues/603

While we keep supporting the `input`, should we remove it from the documentation instead of adding a deprecation note? It might make the documentation simpler. Which do you think would be better?

**Comment by sindresorhus** [comment]
I prefer to keep the docs for now. I don't even think we should doc deprecate `input` until we have proven that `stdin` option is a good replacement. `stdin: [string]` feels a bit weird to be and is bound for typos like `stdin: string` which does something completely different.

**Comment by ehmicky** [comment]
Done at #604.
