### ISSUE TITLE
Ideas?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/execa#6]
Are there any annoyances you've had with child processes that could potentially be fixed in execa? Anything that could be done better? I'm open for any kind of suggestions.

**Comment by callumlocke** [comment]
I often want `stdio: 'inherit'` behaviour (which is normally only an option with `cp.spawn()` or `execa.spawn()`, I think) but with the simple promise-returning API of `execa()`.

The `stdio: 'inherit'` option lets you watch logs coming from the child process live and incrementally (and in colour!), which is what I want 50% of the time. But it means I have to use spawn, and therefore have to manually hook up event listeners to handle the child process ending or erroring.

I often find myself writing a wrapper like this:

```js
function run(file, args, options = {}) {
  return new Promise((resolve, reject) => {
    const child = execa.spawn.call(
      file, args, Object.assign({ stdio: 'inherit' }, options)
    );

    child.on('error', reject);
    child.on('exit', code => {
      if (code === 0) resolve();
      else reject();
    });
  });
}
```

It would be great if `execa()` could introduce an option like this.

Even better would be if there was some nice way to visually distinguish the child logs as being from the child process, like prefixing each line with `> ` or something (but still retaining ANSI colour codes in the child logs).

**Comment by sindresorhus** [comment]
@callumlocke I really like the idea! I've had similar needs. Would you mind moving this into a new issue?

**Comment by zealoushacker** [comment]
IPC support like in [ `child_process.spawn`](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options)'s [`options.stdio`](https://nodejs.org/api/child_process.html#child_process_options_stdio) would be awesome.

**Comment by sindresorhus** [comment]
@zealoushacker Should already be supported, since we use `child_process.spawn()` internally, but needs to be tested and documented.

**Comment by tpetry** [comment]
Automatic handling of timeout by execa for executed processes would be nice. You define a max running time of e.g. 15000ms and the executed process has to finish within this time limit or will be killed. This is very useful for any application which has to fulfill QoS criterias.

**Comment by sindresorhus** [comment]
@tpetry `execa` already has a `timeout` option:

> 
### execa(file, [arguments], [options])

> **Same options as [`child_process.execFile`](https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback).**

**Comment by tpetry** [comment]
My fault, you're right. Didn't look up the options because i expected the same options as child_process.spawn

**Comment by revelt** [comment]
Is there a way to make it so that the output of the commands run via `execa` is coloured in the terminal?

I'm running it this way:

```js
execa(commandApp, commandAttributes).stdout.pipe(process.stdout)
```

but everything in the terminal (tested on both hyper.js and iTerm) is black and white.

To give some context, I'm using `execa` in [fol](https://www.npmjs.com/package/fol) to allow people to input a folder name, then let them pick a subfolder from a list, then place that choice into user's chosen terminal command. I need this, for example, to call gulp with a flag and a name of a subfolder, like `gulp -t vip_template_64`. That subfolder name varies, it's the different template I pick each time.

I got it wired and working, just the `stdout` output is uncoloured.

Thanks in advance.

**Comment by sindresorhus** [comment]
@revelt Either `execa(commandApp, commandAttributes, {stdio: 'inherit'})` or use the `--color` flag to force colors.

**Comment by revelt** [comment]
@sindresorhus it worked! thanks a lot.
