### ISSUE TITLE
Add `stdin: ReadableStream` and `stdout|stderr: WritableStream` options

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#603]
As discussed in https://github.com/sindresorhus/execa/issues/593#issuecomment-1856839994

We should support web streams for the `stdin`/`stdout`/`stderr` options.

We can implement this by converting them to Node.js streams using [`stream.Readable.fromWeb()`](https://nodejs.org/api/stream.html#streamreadablefromwebreadablestream-options) and [`stream.Writable.fromWeb()`](https://nodejs.org/api/stream.html#streamwritablefromwebwritablestream-options)

**Comment by aaronccasanova** [comment]
Definitely a feature I would leverage!

> We can implement this by converting them to Node.js streams using [stream.Readable.fromWeb()](https://nodejs.org/api/stream.html#streamreadablefromwebreadablestream-options) and [stream.Writable.fromWeb()](https://nodejs.org/api/stream.html#streamwritablefromwebwritablestream-options)

Is [Stability: 1 - Experimental](https://nodejs.org/api/documentation.html#stability-index) a concern? I haven't been using the Web Stream utils in production for that reason. Might be worth opening a request in Node.js to mark as stable. (At least that's the process I'm familiar with following along [with the util.parseArgs stability](https://github.com/nodejs/node/issues/46640))

**Comment by ehmicky** [comment]
That's a very good point @aaronccasanova.

My concern would be to end up re-implementing the same logic, but without all the tests and insight knowledge that James Snell has (see original PR in https://github.com/nodejs/node/pull/39134). From checking the [history](https://github.com/nodejs/node/commits/main/lib/internal/webstreams/adapters.js), it seems rather stable.

For reference, links to the code of [`stream.Writable.fromWeb()`](https://github.com/nodejs/node/blob/2aff5cf638dcfbf89cf82eb42e6fe6d03cf75000/lib/internal/webstreams/adapters.js#L138) and [`stream.Readable.fromWeb()`](https://github.com/nodejs/node/blob/2aff5cf638dcfbf89cf82eb42e6fe6d03cf75000/lib/internal/webstreams/adapters.js#L423).

We could also wait until those APIs become stable.

What are your thoughts on this @sindresorhus?

**Comment by sindresorhus** [comment]
I think we should do it and use the built-in APIs, but we can mention in our docs too that the web streams stuff is experimental.

**Comment by ehmicky** [comment]
I gave it a go and ran into the following problem: `child_process.spawn()` `stdio` option only accepts streams that have an underlying file descriptor.

The problem is: this is currently checked by verifying if the stream is an `instanceof` the following classes: `Pipe`, `TTY`, `TCP` and `UDP`. Those classes are implemented in C++ and are not accessible userland. 

https://github.com/nodejs/node/blob/5ac658102d8f84a4c3e00e3c54e89dc9784c3394/lib/internal/child_process.js#L340-L347

https://github.com/nodejs/node/blob/5ac658102d8f84a4c3e00e3c54e89dc9784c3394/lib/internal/child_process.js#L1060-L1071

Unfortunately, when passing a web stream to `stream.Readable.fromWeb()` or `stream.Writable.fromWeb()`, the return value is never an instance of `Pipe`/`TTY`/`TCP`/`UDP` . Even when the web stream has technically an underlying file descriptor, for example the `response.body` of `fetch()`.

I do not see a way to go around this problem. If you do, please let me know!

**Comment by ehmicky** [comment]
Update: there is a solution. When a web stream is passed to the `stdin`/`stdout`/`stderr` option, pass `'pipe'` instead. Once the process is spawned, pipe the web stream to `process.stdin|stdout|stderr`. I tried this approach already in #604.

**Comment by ehmicky** [comment]
`stdin` done at #615.

**Comment by ehmicky** [comment]
`stdout` and `stderr` done at #619.
