### ISSUE TITLE
Remove file descriptor restriction on the `stdin`/`stdout`/`stderr` option

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#617]
Node.js requires the streams passed to the `stdio` option to have an underlying file descriptor.

https://github.com/nodejs/node/blob/0afe731d357d4df9a65aeb06429bf663d8dc2975/lib/internal/child_process.js#L1060
https://github.com/nodejs/node/blob/0afe731d357d4df9a65aeb06429bf663d8dc2975/lib/internal/child_process.js#L340

Execa could remove that restriction: if a stream without a file descriptor is passed to the `stdio` option(s), we could pipe it to the child process after it spawned. This would re-use the code that does the same thing for web streams (#615).

This was actually already discussed in #81, although in different terms.

However, Node.js detects whether there is an underlying file descriptor using the undocumented `stream._handle` and `stream.handle` properties. Also, those must be instances of `Pipe`, `TTY`, `TCP` or `UDP` which are internal classes not accessible userland. I do not think we should build detection logic based on this, as any Node.js release might break it.

Alternatively, we could make users opt-in to that behavior. For example, wrapping the stream into an array or a plain object instead of passing `stream` directly, to the `stdio` option(s).

Or, users could turn the Node.js stream into a web stream which we now support (#603), using `Readable.toWeb()`/`Writable.toWeb()`. I.e. we would just add some documentation about this.

What are your thoughts on this @sindresorhus?

**Comment by sindresorhus** [comment]
I prefer to put minimal effort into legacy APIs like Node.js streams. So my preference would be documentation:

> Or, users could turn the Node.js stream into a web stream which we now support (https://github.com/sindresorhus/execa/issues/603), using Readable.toWeb()/Writable.toWeb(). I.e. we would just add some documentation about this.

**Comment by ehmicky** [comment]
Yes, I was also thinking along those lines, for the same reason. :+1:

**Comment by ehmicky** [comment]
When adding support for passing multiple values to the `std*` options (#643), we added a possible workaround for this issue, as a side effect. Namely, when passing a Node.js stream + another value, the Node.js stream will be handled by Execa instead of by `child_process.spawn()`. This removes the restriction above.

For example, `{ stdout: [nodeStream, 'pipe'] }` instead of `{ stdout: nodeStream }`.

We can document this workaround as it might help some users.
