### ISSUE TITLE
Cleanup doesn't work reliably

### ISSUE THREAD

**Issue by callumlocke** [sindresorhus/execa#62]
I'm using execa to start a child node process which simply starts an express server listening on port 5000.

But this child process often ends up running after I've exited the parent program, so when I run the parent again, I get an error saying port 5000 is already bound when it tries to start the child process. This happens about 25% of the time.

I haven't yet figured out what conditions cause the cleanup to fail. Any ideas?

**Comment by sindresorhus** [comment]
// @dignifiedquire

**Comment by callumlocke** [comment]
Sorry, I got some details wrong. Still debugging but I don't think my problem is with execa now.

**Comment by brandonros** [comment]
Any update? I'm seeing the same thing.
