### ISSUE TITLE
Allow `stdin`/`stdout`/`stderr` options to be an array

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#620]
Allowing the `stdin`/`stdout`/`stderr` options to be an array of values would be a small change from an API complexity standpoint, but offer some great expressiveness to users and handle a few important use cases.

---

A common use case that's been brought up multiple times:

```js
const { stdout } = await execa(..., { stdout: ['inherit', 'pipe'] })
```

I have needed this myself in production code. We used to document it in our `readme.md`. This is discussed in 2 long-standing open issues (which would then be solved): https://github.com/sindresorhus/execa/issues/121, https://github.com/sindresorhus/execa/issues/25.

Another use case would be:

```js
await execa(..., { stdin: ['inherit', 'pipe'] })
```

This was discussed when we changed the default value for the `stdin` option with Execa `$` since both `inherit` and `pipe` had benefits.

Other use case: logging errors on-disk while processing them programatically.

```js
const { stderr } = await execa(..., { stderr: [ 'pipe', './errors.txt'] })
```

---

Implementation-wise, all combinations should work (with a few small tweaks). When using `inherit` + something else, we would need to actually use `pipe` and emulate `inherit` with some piping logic (which mostly already exists due to the recent work around those options). This would mean the child process would not run in a TTY, so we should document that change of behavior.

What do you think?

**Comment by sindresorhus** [comment]
👍
