### ISSUE TITLE
readable stream 'end' event

### ISSUE THREAD

**Issue by vesparny** [sindresorhus/execa#63]
This is not an issue, but more a question on node streams.
Just wanted to know if there is any technical difference between those 2 implementations

```js
  function runCommandAndWriteToFile (cmd, name) {
   // cmd is an execa instance
    return new Promise((resolve) => {
      cmd.stderr.pipe(process.stdout)
      cmd.stderr.on('end', () => {
        cmd.then((res) => {
          const msg = `Command run:\n${res.cmd}`
          utils.log(chalk.magenta(msg))
          resolve()
        })
      })
    })
  }
```

and

```js
  function runCommandAndWriteToFile (cmd, name) {
    cmd.stderr.pipe(process.stdout)
    return cmd.then((res) => {
      const msg = `Command run:\n${res.cmd}`
      utils.log(chalk.magenta(msg))
    })
  }
```

thanks

**Comment by sindresorhus** [comment]
The latter is more correct as it uses [our listener](https://github.com/sindresorhus/execa/blob/842be7c11a33c71177ea03ff12412047f3d8bd07/index.js#L117) to the child_process `exit` event, which is guaranteed to be the last thing before the child exits.
