### ISSUE TITLE
Should `execa.sync()` throw on error?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/execa#66]
Currently it returns the error as an `.error` property, but I think that's a bit surprising (the async methods reject). At least I didn't realize: https://github.com/sindresorhus/clipboardy/commit/82acb3b7d362098a454db95a1e1fbf2dc6d940c5

Thoughts anyone?

**Comment by SamVerschueren** [comment]
Yes, would make way more sense to throw an error. Would also align with `async/await`.

```js
try {
    async execa('node', ['--version']);
} catch (err) {
    console.error(err);
}
```

```js
try {
   execa.sync('node', ['--version']);
} catch (err) {
    console.error(err);
}
```

**Comment by SamVerschueren** [comment]
@sindresorhus I can do a PR if you want. But maybe you want other opinions first. Just give me a shout.

**Comment by sindresorhus** [comment]
👍
