### ISSUE TITLE
`result.stdio` and `error.stdio`.

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#665]
We currently return the child process' `stdout` and `stderr`, as a property to the result and error objects.
We could do the same for the other file descriptors (3, 4, etc.), using [`childProcess.stdio`](https://nodejs.org/api/child_process.html#subprocessstdio). This would useful to any users writing to custom file descriptors.

It would behave just like `stdout` and `stderr` when it comes to buffering and encoding. It would in fact mostly use the same existing underlying logic, so the implementation would be fairly lightweight.

Just like `stdout` and `stderr`, it would be `undefined` when using `inherit`, `ignore`, `ipc`, etc. since those do leave `childProcess.stdio[*]`  as `null`.

`childProcess.spawnSync()` actually [does exactly this](https://nodejs.org/api/child_process.html#optionsdetached).

What do you think @sindresorhus?

**Comment by sindresorhus** [comment]
👍

**Comment by ehmicky** [comment]
Done in #676.
