### ISSUE TITLE
How to maintain console colors

### ISSUE THREAD

**Issue by mikeerickson** [sindresorhus/execa#69]
I have created a simple script:

```
	execa('bash',['./scripts/lint-styles.sh'])
		.then(result => {
			console.log(result.stdout);
		});
```

This script calls

```
#!/usr/bin/env bash

./node_modules/.bin/sass-lint "./resources/assets/sass/*.s+(a|c)ss" -q -v
```

When executed, the output is correct, but it does not have the color output which displays when executing from cli

**Comment by SamVerschueren** [comment]
Try this

```js
execa('bash',['./scripts/lint-styles.sh'], {stdio: 'inherit'})
```

**Comment by shellscape** [comment]
I've found that in most cases (not confirmed outside of an OSX env), using the option `env: { FORCE_COLOR: true }` works as well, without having to use `{stdio: 'inherit'}`, which can cause other issues #70.

Some bins/apps also have options, like Mocha `--colors`, which will force colors as well.

**Comment by mikeerickson** [comment]
@SamVerschueren @shellscape Thanks gents, I went with the `env: { FORCE_COLOR: true }` option (the `stdio` option as producing some spurious `null` output in addition to colors.

```
var execa = require('execa');

execa("eslint", ["./src/**/*.js"], {env: {FORCE_COLOR: true}})
  .then(result => {
	console.log(result.stdout);
});
```

**Comment by LiranBri** [comment]
note that true is not a valid env variable, as env variables are always strings. if you use typescript, it would not get passed.

so should be:
```javascript
var execa = require('execa');

execa("eslint", ["./src/**/*.js"], {env: {FORCE_COLOR: 'true'}})
  .then(result => {
	console.log(result.stdout);
});
```

**Comment by Samrose-Ahmed** [comment]
Not that using stdio:inherit will not let you access stdout/stderr
