### ISSUE TITLE
Inherited stdio results in null stdout, stderr in Error

### ISSUE THREAD

**Issue by shellscape** [sindresorhus/execa#70]
Ran across a funky error case today while converting gulp-mocha to use execa. If `{stdio: 'inherit'}` is used in execa's options, and the command fails, the resulting Error message contains `nullnull`

Line in question: https://github.com/sindresorhus/execa/blob/master/index.js#L201

Example output:

```
{ Error: Command failed: mocha /.../github/gulp-mocha/test/fixtures/fixture-fail.js
nullnull
    at Promise.all.then.arr (/.../github/gulp-mocha/node_modules/execa/index.js:201:11)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

FWIW, for commands that succeed, `result.stdout` and `result.stderr` are also both null in the `.then(result =>` handler when `{stdio: 'inherit'{` is used. That isn't mentioned anywhere in the README, and the option appears to be the only way to preserve terminal formatting.

**Comment by sindresorhus** [comment]
I agree we should handle it better by throwing an error or something. With `{stdio: 'inherit'}` we have no access to stdout/stderr. If you want to do something with the output you should not `inherit`.

**Comment by shellscape** [comment]
👍 

I'll add to my list a PR to update the README with that info.
