### ISSUE TITLE
Line-wise standard streams

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#706]
With #695, we just added line-wise transforms. However, this does not cover `childProcess.std*`.

```js
const childProcess = execa('...')
for await (const chunk of childProcess.stdout) {
  console.log(chunk) // Buffer, and not line-wise
}
```

What are your thoughts on adding the following?

```js
const childProcess = execa('...', {lines: true})
for await (const line of childProcess.stdout) {
  console.log(line) // String, and line-wise
}
```

This would work also for `childProcess.stdout.read()`, `childProcess.stdout.on('data')` and when redirecting from/to Node.js/web streams.

```js
const writableStream = new Writable({
  write(line, encoding, done) {
    console.log(line) // String, and line-wise
    done()
  }
})
await execa('...', {lines: true, stdout: writableStream})
```

This would be pretty fairly simple to implement since it can re-use most of the logic of 2 separate features:
  - Line-wise transforms (#695)
  - `objectMode` transform (#21)

Under the hood, when the `lines: true` option is used, we would just add an internal transform that is a noop, but is both line-wise and in `objectMode`.

**Comment by sindresorhus** [comment]
Yes, this would be nice 👍
