### ISSUE TITLE
`preferLocal` fails for globally installed CLI programs

### ISSUE THREAD

**Issue by acburdine** [sindresorhus/execa#72]
When you have a globally installed binary that uses `execa` within it, the `preferLocal` option doesn't work correctly. 

Example: `foo` is a js cli program that depends on `a` (which has a binary installed to `foo`'s node_modules/.bin/ folder.

```sh
npm link # within foo directory
foo doSomethingThatCallsA # within another directory
output: spawn a ENOENT
```

The reason for this is because `npmRunPath` uses the CWD by default. This isn't an issue in npm-run-path necessarily though, because execa should provide an option (along with `preferLocal` to specify the directory to look into.

For example:
```js
// foo.js
const execa = require('execa');

execa('a', ['some', 'options'], {
    preferLocal: true,
    localDir: __dirname 
});
```

More than happy to PR this, just want to get approval on the `localDir` option name or to have a better name suggested before I submit a PR 😄

**Comment by sindresorhus** [comment]
Yeah, makes sense. I've stumbled upon this myself too, but I forgot to open an issue about it. PR welcome 😃

---

Note to self: This can simplify https://github.com/sindresorhus/alfy/blob/1c68a9cbb9400e71b1b8b536830075734772aa2e/init.js // @SamVerschueren

**Comment by acburdine** [comment]
Turns out I just didn't read the code closely enough - the options passed into execa are passed into npmRunPath: https://github.com/sindresorhus/execa/blob/master/index.js#L41 -> meaning you can say `execa('a, ['some', 'options'], {preferLocal: true, cwd: 'someDir'});` and it will work.

It's not necessarily as intuitive - but it works. I can still submit a PR with an alias localDir option if wanted - it would really only function for readability though.
