### ISSUE TITLE
Allow newlines inside `$` command

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#721]
Allowing newlines inside `$` might be nice for long commands. For example:

```js
await $`command
  --flag-one
  --flag-two
  --flag-three
  ...
  --lots-of-flags`
```

At the moment, arguments are delimited by spaces. We should use `\s` instead.

https://github.com/sindresorhus/execa/blob/8ef8e90e13dc2ab8cc69ed360ba3485e464d39f0/lib/command.js#L26

Injections are not possible with `$` since dynamic values require using `${...}`, in which case `\s` will not be considered delimiters.

This should apply to `execaCommand()` too, which uses the same underlying logic. `execaCommand()` is meant for passing trusted dynamic input as is, for example for a REPL. Allowing newlines for a REPL is useful too. If the input is not trusted, `execa()` or `$` should be used instead.

What do you think @sindresorhus?

**Comment by sindresorhus** [comment]
I guess we could, but maybe we should keep it open a bit more to see if people can come up with any issues with it. It's not an important feature, but it will be harder to take it away later on.

The only downside I see is that you can no longer copy the command and run it in a real shell for debugging.

**Comment by ehmicky** [comment]
Good point about copying. One would need to add trailing backslashes, or join all lines into one before copying.

Let's keep this on the back burner and wait. :+1:

**Comment by aaronccasanova** [comment]
I like the idea 👍 I currently use arrays in `$` expressions to clean up long commands:

```ts
await $`command ${[
  '--flag-one',
  '--flag-two',
  '--flag-three',
  '...',
  '--lots-of-flags',
]}
`
```

**Comment by ehmicky** [comment]
Someone also [asked for this feature](https://github.com/google/zx/issues/539) with zx and it got 6 thumbs ups. There are some good points in favor of it being made. The main cons seems to be zx-specific (shell quoting-related) and does not impact Execa.

**Comment by ehmicky** [comment]
@sindresorhus What are your thoughts using the [following issue](https://github.com/google/zx/issues/539) from zx? Especially the fact that many users seem to want that feature and zx is currently missing it.

**Comment by sindresorhus** [comment]
Alright, lets do it.
