### ISSUE TITLE
`timeout` option's improper behavior

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#726]
The `timeout` option has been part of `child_process.spawnSync()` for a long time. However, it's only been introduced to `child_process.spawn()` with Node 14. 

`execaSync()` just passes the `timeout` option to `child_process.spawnSync()`.

Instead, `execa()` emulates it and calls `process.kill()` on timeout. However, it still passes the `timeout` option to `child_process.spawn()`. This creates a race condition where, on timeout, the child process is terminated sometimes by Execa, sometimes by `child_process.spawn()`'s internal logic. 

We should fix this by _not_ passing the `timeout` option to `child_process.spawn()`, but still pass it to `child_process.spawnSync()`.

Note: we could potentially consider removing our `timeout` option's logic since it is now implemented in core Node.js. Unfortunately, `child_process.spawn()`'s `timeout` logic just sends a `SIGTERM` without any hint that the process was terminated due to a timeout. 

https://github.com/nodejs/node/blob/26f63be8787a9289539e0f19b5d9197de5038cb0/lib/child_process.js#L763-L781

This is very unhelpful, as users might be left wondering why the child process ended. Execa adds `error.timedOut` and indicates the timeout in `error.message`, which we should kept. Therefore, we should keep our existing `timeout` logic.

**Comment by sindresorhus** [comment]
> Unfortunately, child_process.spawn()'s timeout logic just sends a SIGTERM without any hint that the process was terminated due to a timeout.

Maybe worth a Node.js issue? Would be nice if we could remove out code for this.

**Comment by ehmicky** [comment]
Yes, this makes sense. 
`spawnSync()` throws `ETIMEDOUT`, but `spawn()` cannot do this. So the only thing they could possibly do is to either emit an event, or set some boolean property on the child process.

**Comment by ehmicky** [comment]
Node issue: https://github.com/nodejs/node/issues/51561
