### ISSUE TITLE
More graceful behavior when `buffer: false` is misused

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#730]
When the `buffer: false` option is used, users become responsible for reading `childProcess.stdout|stderr|all`. If they don't, the child process will hang forever. We [document it](https://github.com/sindresorhus/execa#buffer):

> When set to false, you must read the output of [stdout](https://github.com/sindresorhus/execa#stdout-1) and [stderr](https://github.com/sindresorhus/execa#stderr-1) (or [all](https://github.com/sindresorhus/execa#all) if the [all](https://github.com/sindresorhus/execa#all-2) option is true). Otherwise the returned promise will not be resolved/rejected.

For users who use `buffer: false` because they do not intend to read the streams, that might create confusion. Arguably, they _should_ have used `stdout: 'ignore'` instead of `buffer: false`. But it might take them a while to figure that out. Therefore, it'd be a more graceful behavior to not leave the process hanging.

What's worse: the process might or might not hang. Apparently, that hanging behavior is fairly unreliable. From our tests, it seems not to happen on Windows, to always happen on Linux and to sometimes not happen on macOS. Also, it seems to only happen when >16KB has been written to those streams.

Other users might use `buffer: false` and do read the streams but in a later macrotask. That's a bad pattern from a performance standpoint since it blocks the streams until consumption. Users should start reading those streams as soon as `execa()` returns the child process.

I would recommend the following behavior:
  - If `buffer: false` is used
  - Wait for one macrotask (`await setTimeout(0)`)
  - If `childProcess.stdout|stderr|all` has not been read yet, i.e. if its `readableFlowing === null`, call its `.resume()` method

This does mean that users who use `buffer: false` and read streams too late would be missing the beginning of the data. However, this is a lesser evil than processes randomly hanging IMHO.

**Comment by ehmicky** [comment]
I was considering this as well, that's an option. :thinking: 

The two different problematic behaviors have a different severity:
  - Using `buffer: false` when `stdio: 'ignore'` should have been used is mostly a waste of resources. Node.js creates the child process's underlying pipes, and chunks are going through noop streams. I don't think this is a very big waste of resources though. The amount of memory will remain low due to streaming. The CPU cost will be low too due to the streams being mostly pass-throughs.
  - Using `buffer: false` and consuming the streams but too late is an application-level problem, since it might lead to missing data. That's probably a bigger problem.

That being said, I think it is a user mistake most of the time, but maybe not always. There might be a few valid use cases. I can think of the following three.

---

First case: the `buffer: false` applies to all streams. Due to this, the following usage is probably common.

```js
const childProcess = execa('...', {buffer: false});
childProcess.stdout.on('data', () => { ... });
```

In the above example, `childProcess.stderr` is not read, so users should ideally do this:

```js
const childProcess = execa('...', {buffer: false});
childProcess.stdout.on('data', () => { ... });
childProcess.stderr.resume();
```

It is very likely most users don't call `.resume()` like this, so doing it on their behalf might be a nice thing.

---

Second case: conditionally reading a stream or not depending on a condition that is not known yet at spawning time. For example, some automatic tests might use a wrapper around Execa. The child process might be spawned with `buffer: false`, with some of the tests reading the streams, others not.

---

Third case: purposefully reading a stream later. For example, if a process has a big output, but the user is only interested in the very end of it (e.g. some kind of final status line). One might intentionally start reading only after a specific signal, to avoid skipping through the big output.

---

In each of those cases, there is probably a better way to do it, but those are not hard error mistakes.
Strictness is usually better IMHO, but I am wondering whether we should be lenient here considering the potential for other unexpected use cases?

**Comment by sindresorhus** [comment]
Good points. I agree that `.resume()` is the best we can do for this.
