### ISSUE TITLE
Improve process piping API

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#743]
## Proposal

Changing the following:

```js
await execa(...).pipeStdout(execa(...));
await execa(...).pipeStderr(execa(...));
await execa(..., {all: true}).pipeAll(execa(...));
```

And:

```js
const childProcess = execa(...)
const secondChildProcess = execa(...)
childProcess.stdio[3].pipe(secondChildProcess.stdin)
await Promise.all([childProcess, secondChildProcess])
```

To this instead:

```js
await execa(...).pipe(execa(...));
await execa(...).pipe(execa(...), 'stderr');
await execa(..., {all: true}).pipe(execa(...), 'all');
await execa(...).pipe(execa(...), 3);
```

## Details

The method's second argument can be `'stdout'` (default value), `'stderr'`, `'all'` or any file descriptor number. 
Passing an input file descriptor (e.g. `0`) throws.

## Pros

1. The pipe methods currently only allow stdout/stderr/all, not other file descriptors. This adds support for it.
2. Having `stdout` as the default value encourages the most common case. In general, `stdout` is the recommended stream to pipe multiple processes. This is why Bash uses a single character `|` for it, while piping `stderr` is more verbose `2>&1 >/dev/null |`, and piping `all` is available as `|&` but less commonly seen because introduced in Bash 4. 
3. Reduce the number of methods, simplifying the API.

---

What do you think?

**Comment by sindresorhus** [comment]
👍
