### ISSUE TITLE
Simplify `.pipe*` argument type

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#744]
## Proposal

The `.pipe*(...)` methods can get three possible argument types: a child process, a file path or a stream.
The last two are now redundant with the `std*` options.

For example:

```js
await execa(...).pipeStdout('file.txt');
await execa(...).pipeStdout(stream);
```

Can now use:

```js
await execa(..., {stdout: {file: 'file.txt'}});
await execa(..., {stdout: stream});
```

We should remove support for passing a file path or stream to the `.pipe*()` methods, and only allow passing a child process.

## Pros

The `std*` options are better for file paths and streams and should be preferred.
  - They automatically handle listening for the underlying stream's errors and completion.
  - They can be combined with other destinations, by passing an array of values.

Also, this removes a source of confusion with the `.pipeStdout()` method (and other `.pipe(...)` methods). 
  - Right now, `source.pipeStdout(destination)` returns `destination` if it is a child process, but returns `source` if it is a file path or stream. 
  - This is confusing. For example: 
     - `source.pipeStdout(childProcess).pipeStdout(otherChildProcess)` sets `source -> childProcess -> otherChildProcess`, 
     - while `source.pipeStdout(stream).pipeStdout(otherStream)` sets `source -> stream` + `source -> otherStream`.

The above also means that the pipe methods currently do not listen to the stream's argument error and completion, which can result in uncaught exceptions crashing the process.

Finally, this makes our API more straightforward from a design standpoint:
  - The `stdin`/`stdout`/`stderr`/`stdio` options are the main way to redirect standard streams
  - The `.pipe*()` methods are only intended to pipe multiple processes

--- 

What do you think?

**Comment by sindresorhus** [comment]
👍
