### ISSUE TITLE
execa.command is not a function

### ISSUE THREAD

**Issue by yvonneyuinfj** [sindresorhus/execa#749]
"execa": "^8.0.1"

**Comment by ehmicky** [comment]
Hi @yvonneyuinfj,

To help you, we would need additional details, including code examples to reproduce.

However, I believe you might be referring to the fact that `execa.command()` has been renamed to [`execaCommand()`](https://github.com/sindresorhus/execa#execacommandcommand-options).

```diff
- await execa.command('...')
+ await execaCommand('...')
```

**Comment by yvonneyuinfj** [comment]
> Hi @yvonneyuinfj,
> 
> To help you, we would need additional details, including code examples to reproduce.
> 
> However, I believe you might be referring to the fact that `execa.command()` has been renamed to [`execaCommand()`](https://github.com/sindresorhus/execa#execacommandcommand-options).
> 
> ```diff
> - await execa.command('...')
> + await execaCommand('...')
> ```

Thanks for helping!
Apologies for not reading the API doc closely enough.
