### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by radiovisual** [sindresorhus/execa#75]
When I run my tests, which have this format:

```js
import test from 'ava';
import execa from 'execa';

test('action', async (t) => {
  const { stdout } = await execa('./cli.js', ['action']);
  t.true(stdout.search('export default ClassName;') > -1);
});
```

I am getting the Error of `Error: spawn EACCES` on each test run.

![image](https://cloud.githubusercontent.com/assets/5614571/24072076/5e551f38-0bd8-11e7-90de-0958672eb694.png)

I have a feeling it could be something simple I am overlooking, like bad formatting or something, but figured I would ask here in case I have stumbled onto something. Is this error trying to tell me that the module doesn't have access to execa's `index.js` file from within the `node_modules` directory? I deleted the node_modules directory and reinstalled everything, but I got the same set of errors.

If you want to see more of the code in context, the module that is experiencing this issue is [here](https://github.com/radiovisual/jsnip-cli).

Thanks in advance for your help.

**Comment by schnittstabil** [comment]
```shell
chmod +x cli.js
```

**Comment by radiovisual** [comment]
Thanks @schnittstabil , that did it. I knew it was going to be something simple I was overlooking.

**Comment by tommedema** [comment]
How can this happen for binary files within node_modules? I get this error when spawning the serverless framework CLI:

```
await execa(path.resolve(rootPath, 'node_modules/serverless/bin/serverless'), [
     command,
     '--aws-s3-accelerate',
     '--verbose',
     '--region', region,
     '--stage', stage
  ].concat(args), {
    cwd: servicePath,
    stdout: process.stdout,
    env: cEnv
  })
```

**Comment by tommedema** [comment]
@SamVerschueren that'd explain it, but no, I didn't.
