### ISSUE TITLE
Re-using the features from `execaNode()`

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#781]
`execaNode()` has some nice features:
  - prepend `'node'` as the binary argument
  - re-use the current Node.js binary, including its version
  - re-use the current Node.js CLI flags, without getting any issues when using `--inspect`
  - forces `shell: false`

However, those features are not available for users who either:
  - use `$` or `execaCommand()`
  - use synchronous methods like `execaSync()`
  - do not wish to add an `ipc` channel

We could fix this by adding a `{ node: true }` option (any other option name works too), which would do the same thing as what `execaNode()` is doing, except for adding an `ipc` channel.

What do you think?

**Comment by sindresorhus** [comment]
Why would you not want a `ipc` channel though? If there's no good reason, then having `{node: true}` be the same as `execaNode()` would make the docs simpler.

**Comment by ehmicky** [comment]
The only reason I was thinking of was to avoid the cost of setting up the IPC channel. 

A [named pipe](https://github.com/nodejs/node/blob/5acd42ed9e65971807fe8ddf9a47e4e9f2109484/lib/child_process.js#L177C17-L177C21) is created (or is a TCP Unix socket used? I am not sure [from looking](https://github.com/nodejs/node/blob/eca4b1a403959d5b83fb5a9adaae8f4c3580eea2/src/pipe_wrap.cc#L151) at [the libuv code](https://github.com/libuv/libuv/blob/v1.x/src/unix/pipe.c)). I am not sure whether this counts towards `ulimit -n`. :thinking: 

Performance-wise, the child process does [some additional setup](https://github.com/nodejs/node/blob/eca4b1a403959d5b83fb5a9adaae8f4c3580eea2/lib/internal/child_process.js#L583) when it starts. I tried benchmarking it with the following code.

```js
import {spawn} from 'node:child_process'
import {once} from 'node:events'

console.time()
for (let i = 0; i < 1e3; i += 1) {
  const childProcess = spawn('node', ['empty.js'], {stdio: ['pipe', 'pipe', 'pipe', 'ipc']})
  await once(childProcess, 'exit')
}
console.timeEnd()

console.time()
for (let i = 0; i < 1e3; i += 1) {
  const childProcess = spawn('node', ['empty.js'], {stdio: ['pipe', 'pipe', 'pipe']})
  await once(childProcess, 'exit')
}
console.timeEnd()
```

Which gives me:

```
default: 18.379s
default: 15.602s
```

I am not sure though whether the reasons above are enough to justify creating an `ipc` channel by default or not though. :thinking: How do you feel about this?

**Comment by sindresorhus** [comment]
People can just do `{node: true, ipc: false}` if they don't want it, right? If so, I think the consistency is worth the tiny performance overhead by default.

**Comment by ehmicky** [comment]
Yes, that's a good point. Also, the benchmark is on an empty file. The time to actually load the file should be much higher, making the time spent setting up the `ipc` channel not as significant.

So, what are you suggesting is the following, is this correct?
  - `ipc` option defaults to `true` if `{node: true}` is used
  - `execaNode(...)` is the same as `execa(..., {node: true})`

**Comment by sindresorhus** [comment]
Yes

And make sure there is a test for `{node: true, ipc: false}`.
