### ISSUE TITLE
`ipc` option

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#782]
When using Node.js IPC feature (which is pretty nice), I sometimes find having to add `'ipc'` at the end of the `stdio` array slightly cumbersome. It is also potentially error-prone, since one needs to remember for it to be the 4th item (or later), and not to repeat it (as some users might be tempted to). Also, it forces users to use the `stdio` option instead of the simpler `stdin`/`stdout`/`stderr` options Execa provides.

Moreover, while `ipc` does use a file descriptor, it does so in a different way than other `stdio` values.
  - The wire format is undocumented, so that file descriptor is not really something users directly use. It is more of an implementation detail.
  - Only one file descriptor can use it.
  - With Execa, it cannot be combined with other values for a given file descriptor. 

I am wondering whether Node.js should have exposed this feature using an `{ ipc: true }` option instead? Should we add that option, which would automatically add `ipc` to the underlying `stdio` option? We would then undocument passing `ipc` to the `stdio` option, but still support it for compatibility.

What are your thoughts about this?

**Comment by sindresorhus** [comment]
> I am wondering whether Node.js should have exposed this feature using an { ipc: true } option instead? Should we add that option, which would automatically add ipc to the underlying stdio option? We would then undocument passing ipc to the stdio option, but still support it for compatibility.

Yes, I agree that Node.js should have done that, and that we should do it.
