### ISSUE TITLE
Merge `execPath` and `nodePath` options

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#792]
The `execPath` and `nodePath` options have similarities:
  - The value is a path to the Node.js binary
  - The value can be a string or a file URL
  - The default value is `process.execPath`

However, they also have the following differences:
  - `nodePath` is the Node.js binary used to spawn the child process. This is what Execa directly executes. `execPath` is the Node.js binary used by the child process to spawn other child processes. This is set using the `PATH` environment variable.
  - `execPath` is relative to the `cwd` option (which defaults to `process.cwd()`). `nodePath` is always relative to `process.cwd()`.
  - `nodePath` is used with `execaNode()` (or the new `{node: true}` option). `execPath` is used when the `preferLocal` option is `true`.
  - Their value can be independent from each other. For example, when using `execaNode(..., { nodePath: '.../v16/node' })`, the child process will use Node 16, but its own child processes will use the parent process' Node version.

This might create some confusion. I don't think there is a strong reason for having two separate options. We probably should merge them into a single `nodePath` option.
  - It is the Node.js binary used both by the child processes, and its own child processes.
  - It always takes the `cwd` option into account.
  - It sets the `PATH` environment variable (if `preferLocal` is `true`).
  - With `execaNode()` (or the new `{node: true}` option), it is used to spawn the child process.

What do you think?

**Comment by sindresorhus** [comment]
👍
