### ISSUE TITLE
Add `childProcess.kill(error)`

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#810]
Terminating a child process with `childProcess.kill()` does not allow setting an error message or stack trace. This can result in obscure errors which only indicate `Terminated with SIGTERM` and are hard to debug.

It would be nice to allow users to do `childProcess.kill(error)`. It would behave exactly like `childProcess.kill()`, except the error rejected by Execa would be `error`. `error.signal` and `error.isTerminated` would still be set, and `error.message` would still indicate that the child process was terminated by a signal.

It would only be allowed with no signal name, i.e. using the `killSignal` (which defaults to `SIGTERM`), since this is explicitly meant for child process termination, not for any signal. Also, it makes the API simpler.

What do you think?

**Comment by sindresorhus** [comment]
👍
