### ISSUE TITLE
Add `.kill(signal, error)`

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#816]
Users can send `SIGTERM`.

```js
childProcess.kill()
```

Or any signal as argument.

```js
childProcess.kill('SIGKILL')
```

Or using the `killSignal` option.

```js
const childProcess = execa(..., {killSignal: 'SIGKILL'})
childProcess.kill()
```

With #810, we just added specifying an error message/stack.

```js
childProcess.kill(new Error('example'))
```

I initially assumed this would only be needed with the default termination signal (`killSignal` option).
However, I am currently working on a new feature which would require sending `SIGPIPE` + an error message/stack, regardless of the child process's `killSignal`.
Also, I can see that some users might want to both set `SIGKILL` and an error message/stack.

Therefore, we probably should allow the following.

```js
childProcess.kill('SIGKILL', new Error('example'))
```

**Comment by sindresorhus** [comment]
👍
