### ISSUE TITLE
Automatically wait for file streams to open

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/execa#82]
It might be possible to wait for the `open` event on file streams (if we can find a way to detect that a stream is in fact a file stream, and that it will indeed eventually open).

See the discussion [here](https://github.com/sindresorhus/execa/issues/81#issuecomment-290164731)

**Comment by sindresorhus** [comment]
We could detect the follow custom properties attached to it:

```
  path: 'ad',
  fd: null,
  flags: 'w',
  mode: 438,
```

Maybe we should add `isStream.fsWritable()` and `isStream.fsReadable()` methods to [`is-stream`](https://github.com/sindresorhus/is-stream)?

**Comment by jamestalmage** [comment]
I just made `is-file-stream`. https://github.com/jamestalmage/is-file-stream

**Comment by sindresorhus** [comment]
Even better. Less bloat for `is-stream`. The module looks good.

**Comment by SamVerschueren** [comment]
This is a great idea. Makes working with file streams much easier. I will have a look at implementing this.

**Comment by sindresorhus** [comment]
I think we should also at least try to get this into Node.js core by opening an issue argumenting it's the expected behavior.

**Comment by SamVerschueren** [comment]
Good point. We probably all know how this will end but at least we can try.

**Comment by sindresorhus** [comment]
@SamVerschueren At least we can then reference Node.js' unwillingness to good UX. It's always worth trying to improve core Node.js if possible, as it benefits of lot more users, and of course less code for us to maintain.

**Comment by SamVerschueren** [comment]
Totally agree with that.

**Comment by jamestalmage** [comment]
Basically, they only allow streams that have file descriptors, and under the hood, they convert streams to those file descriptors.

It would have been way less confusing for them **not** to allow streams, and just provide a `findUnderlyingFileDescriptor(stream)`.

Streams passed to `child_process.spawn` are handled completely differently than anywhere else in Node-land. Not having the magical "convenience" method would ultimately be so much less confusing.

**Comment by ehmicky** [comment]
Should this be closed in favor for https://github.com/sindresorhus/execa/issues/617?

(Also relevant: https://github.com/sindresorhus/execa/issues/616)

**Comment by sindresorhus** [comment]
Yup

**Comment by ehmicky** [comment]
This feature has been just fixed in Execa 9.0.0. Please see (and share!) the [release post](https://medium.com/@ehmicky/execa-9-release-d0d5daaa097f) and the [changelog](https://github.com/sindresorhus/execa/releases/tag/v9.0.0).

Please see more information [here](https://github.com/sindresorhus/execa/blob/main/docs/streams.md#file-descriptors).
