### ISSUE TITLE
`lines` option is not in typescript types

### ISSUE THREAD

**Issue by gibso** [sindresorhus/execa#830]
Hey guys, love the project, thank you very much for this.

The `lines` execa option that is documented in the README is not part of the typescript types. So when I write sth like

```typescript
  const running = execaCommand(commandWithArgs, {
    cwd,
    lines: true,
    buffer: true,
    stdout: "pipe",
  });
```

it can run successful but the typescript compiler says
```bash
src/utils/exec-command.ts:27:5 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(command: string, options?: Options<"utf8"> | undefined): ExecaChildProcess<string>', gave the following error.
    Object literal may only specify known properties, and 'lines' does not exist in type 'Options<"utf8">'.
  Overload 2 of 2, '(command: string, options?: Options<BufferEncodingOption> | undefined): ExecaChildProcess<Buffer>', gave the following error.
    Object literal may only specify known properties, and 'lines' does not exist in type 'Options<BufferEncodingOption>'.

27     lines: true,
       ~~~~~
```

Would be great if someone finds the time to take a look at this. Thank you!

**Comment by ehmicky** [comment]
Hi @gibso,

This feature has not been released yet.
The next release is bigger than usual, so this has been taking more time.

Stay tuned! :)

**Comment by gibso** [comment]
That's great, thanks for the quick update!

**Comment by ehmicky** [comment]
There are quite a few other unreleased things currently in the `README.md`: transforms, and a bunch of new features related to `stdin`/`stdout`/`stderr`. 

You can see the `README.md` for the currently published version [here](https://github.com/sindresorhus/execa/tree/v8.0.1).

**Comment by ehmicky** [comment]
Execa 9.0.0 has now been released. Please see (and share!) the [release post](https://medium.com/@ehmicky/execa-9-release-d0d5daaa097f) and the [changelog](https://github.com/sindresorhus/execa/releases/tag/v9.0.0).
