### ISSUE TITLE
Ability to turn off buffering

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/execa#84]
If you only pipe the output it's a waste of resources to buffer it and the user can also easily hit the `maxBuffer`.

Either `{buffer: false}` or detect when `.then()` is used. I would prefer the latter, but not sure how feasible it is.

---

This would have prevented https://github.com/sindresorhus/gulp-mocha/issues/169

**Comment by gabrielcsapo** [comment]
I think I have a solution for this. I am working on it now 😄 The second case is feasible, hope to have something up in the next hour or so.

**Comment by SamVerschueren** [comment]
Hehehe, wanted to start on this one as well, glad you mentioned it :). Had something in my mind for the 2nd case as well. Looking forward to the PR :).
