### ISSUE TITLE
Shorthand for piping stdout and stderr

### ISSUE THREAD

**Issue by kaatt** [sindresorhus/execa#85]
I use this pattern a lot and have created a function for personal use:
```
const cp = execa('echo', ['foo', 'unicorns'])
cp.stdout.pipe(process.stdout)
cp.stderr.pipe(process.stderr)
```

Do you think it's a good idea to include it as a shorthand in the library? It could be named `execa.echo` or `execa.log` or `execa.piped`...

**Comment by SamVerschueren** [comment]
I think what you are looking for is the `stdio` option

```js
execa('echo', ['foo', 'unicorns'], {stdio: 'inherit'});
```

**Comment by kaatt** [comment]
Yeah, exactly! Thanks!

Sindre, you can close this.
