### ISSUE TITLE
Avoid confusion with signals

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#856]
We currently expose the following options and error properties:
  - `signal` option
  - `unpipeSignal` option
  - `killSignal` option
  - `error.signal`
  - `error.signalDescription`

The first two are `AbortSignal` instances. The last three are OS signals.
This might be confusing to some users. Especially the `signal` option and `error.signal` which use the exact same term even though they are quite different.

What are your thoughts on renaming some of those to avoid any confusion?
For example, we could do the following two things:
  - renaming `signal` option to `cancelSignal` (like `error.isCanceled`)
  - renaming `error.signal` to `error.signalName`

**Comment by sindresorhus** [comment]
> renaming signal option to cancelSignal (like error.isCanceled)

`abortSignal` may be a better name?

> renaming error.signal to error.signalName

Is it worth doing a breaking change for this if we already rename the `signal` option?

**Comment by ehmicky** [comment]
> `abortSignal` may be a better name?

I was hesitating with that one too. One thing is that `cancelSignal` would match `error.isCanceled`. `error.isCanceled` is only `true` with that specific option. Another is that `unpipeSignal` is also an `AbortSignal` instance, so that might avoid some confusion there too?

> Is it worth doing a breaking change for this if we already rename the signal option?

I was wondering about that too. :)
Unlike the `signal` option, `error.signal` has been around for many years, so would be a bigger breaking change. Let's not do it if you think this is not worth the breaking change?

**Comment by sindresorhus** [comment]
Let's go with `cancelSignal`.

**Comment by sindresorhus** [comment]
> Unlike the signal option, error.signal has been around for many years, so would be a bigger breaking change. Let's not do it if you think this is not worth the breaking change?

I don't think it's worth a breaking change. I don't think there's much confusion as an error would generally not contain an `AbortController#signal`.

**Comment by ehmicky** [comment]
Sounds good.
So let's just rename the `signal` option to `cancelSignal`. :+1:
