### ISSUE TITLE
Add `extendEnv` option

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/execa#87]
Many people, including me, forgets that the `env` option overrides all the environment of the parent. This can cause many weird problem, like binaries not being found because there's no PATH. Would be nice to have a shortcut option that just extends the existing environment instead of replacing it.

From: https://github.com/sindresorhus/clipboardy/pull/16#issuecomment-301237176

**Comment by SamVerschueren** [comment]
Can't we just extend by default and add an option to not extend instead? So setting `extendEnv` to `true` by default.

**Comment by sindresorhus** [comment]
👍 Even better.

**Comment by SamVerschueren** [comment]
Will have a look at it!
