### ISSUE TITLE
Use consistent variable name for child processes

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#877]
Our source code and documentation examples use different variable names for child processes: `spawned`, `subprocess` and `childProcess`. We should be consistent and use a single name. 

I would personally choose `childProcess` to reflect the `child_process` core module, but any other works.

**Comment by sindresorhus** [comment]
One problem with `childProcess` is that it can conflict if you import `child_process` as a default import. It can also be confusing as it's not always clear when scanning code whether it refer to `child_process` or the child process instance.

**Comment by ehmicky** [comment]
Good point. Should we use `subprocess` then?

**Comment by ehmicky** [comment]
Another idea: calling it `child`.
  - Same name as `childProcess.child`, which is the property we want to move the child process to (https://github.com/sindresorhus/execa/issues/413)
  - Reminds of `child_process` name, yet is a different word

**Comment by sindresorhus** [comment]
I'm fine with `child`.

**Comment by ehmicky** [comment]
I started working on this but realized the following: [Node.js calls it](https://nodejs.org/api/child_process.html#subprocesschannel) `subprocess` in its documentation.

Another thing that became clearer when starting to read the documentation with the word `child` is that it might not be as clear to all users that we're talking about processes here, while `subprocess` makes that clearer.

On the other hand, it might be good to be consistent with the property we're going to add to `execaPromise` with #413. Even though Node.js calls it `child`, we might want to call it `subprocess` for consistency, and also to allow users to destructure more easily.

```js
const execaPromise = execa(...);
const {subprocess} = execaPromise;
subprocess.kill();
await execaPromise;
```

Based on this, I am now thinking of:
  - Renaming `spawned`/`childProcess` to `subprocess`
  - Edit #413 so we call the future property `execaPromise.subprocess` instead of `execaPromise.child`.

What do you think?

**Comment by sindresorhus** [comment]
> Based on this, should we do the following instead?

Consistency with Node.js docs is a big benefit 👍
