### ISSUE TITLE
Allow template strings with all methods

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#891]
## Problem

The `$` method was initially intended for Node.js scripts. In other words: series of commands run as a main file.

However, some users seem to be using it because they prefer the template string syntax over the array syntax that `execa()` offers. Using a single string instead of passing an array seems to a preferred syntax for many users. This is probably because it is more similar to typing a command in a shell. 

`$` being used for two fairly different purposes is creating some issues. For example, since we currently assume `$` to always be used for scripts, we set the default option for `stdin` to `'inherit'`. However, this default value is not the best for non-script users.

We should fix the syntax to distinguish:
  - A method dedicated to script users. We could then tweak even more behavior for them, knowing that this is only meant to be run in a typical script file.
  - A method that works like `execa()` but uses a template string syntax.

## Proposal

Add a new `script()` method. It returns `$` but with script-friendly default options. 

```js
import {script} from 'execa';

const $ = script();

await $`echo example`;
```

It can take an options object as argument. This creates a clear pattern for "global" options. This is a common need in scripts. For example, when debugging a script, one would usually want to set the `verbose` option for all commands. 

```js
import {script} from 'execa';

const $ = script({verbose: 'short'});
```

Our current syntax for this is somewhat awkward.

```js
import {$ as $_} from 'execa';

const $ = $_({verbose: 'short'});
```

The current `$` method would be kept as is, except it would not include script-friendly default options.

```js
import {$} from 'execa';

const childProcess = $`node script.js`;
childProcess.stdin.end('example'); // This does not crash anymore
await childProcess;
```

---

This would make sure users can enjoy `$` template string syntax without getting issues with script-friendly default options. This would also allow us to confidently add more script-specific behavior to `script()`. Finally, this would set a better syntax for global options in scripts.

What do you think?

**Comment by sindresorhus** [comment]
I don't think we should optimize for using `$` for non-scripts. The most common case for needing the template syntax is for scripts.

**Comment by sindresorhus** [comment]
> A method that works like execa() but uses a template string syntax.

I agree a method like this could be useful, but I think using the name `$` for this will only cause confusion as we currently recommend it for scripts.

**Comment by ehmicky** [comment]
> I don't think we should optimize for using `$` for non-scripts. The most common case for needing the template syntax is for scripts.

:+1: 

> I agree a method like this could be useful, but I think using the name `$` for this will only cause confusion as we currently recommend it for scripts.

Let's do that instead then, if that sounds good to you. :heavy_check_mark: 

One option would be to re-use the existing methods, and just allow them to also use template strings.

```js
import {execa, execaSync, execaNode} from 'execa';

await execa`echo example`
execaSync`echo example`
await execaNode`script.js`
```

We already currently do this with the `.pipe()` method, which can either take regular arguments or a template string.

One upside is that it could allow users to use `execaNode` + a template string, which is something that is not currently possible (although they can use the `node` option).

This might also be simpler to document.

Thoughts?

**Comment by sindresorhus** [comment]
I'm fine with supporting template strings for the normal methods if it can be done non-ambiguously.

**Comment by ehmicky** [comment]
One side note: the template string syntax passes options like this:

```js
$(options)`command`
```

So to support the template string syntax, we would need to allow options binding, re-using the logic from `$`.

```js
execa(options)`command`
```

This would actually be useful. Setting global options or shared options is something I personally often use with Execa, especially in tests.

```js
const boundExeca = execa(options)
```
