### ISSUE TITLE
Allow `node: true` as a global option

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#898]
## Problem

The `node: true` option is helpful when running Node.js files. It ensures the Node.js version and flags are consistent, and it adds an IPC channel.

However, it is not currently possible to set it as a global option because it crashes when the command either: 
  - specifies `node` as a command explicitly
  - is not using Node.js

```js
import {$ as $_} from 'execa';

const $ = $_({node: true});

await $`file.js argument` // This works
await $`node file.js argument` // This crashes
await $`echo example` // This crashes
```

## Proposal

The following proposal applies only when `node: true` is used.

We could detect whether the command uses Node.js, one of:
  - command is `node`
  - command is file path, and filename is `node`
  - file has a `node` shabang
  - any of the above with `node.exe`
  - file extension is `.js`, `.cjs`, `.mjs` or (since `--loader ts-node/esm` might be used) `.ts`, `.cts`, `.mts`, and no shabang is used

If the command uses Node.js, add the Node.js-specific features (version, CLI flags, IPC channel). Do not add `node` if already present as a command or as a shabang.

If the command does not use Node.js, do nothing.

What do you think?

**Comment by sindresorhus** [comment]
This feels a little bit too magic and fragile. My thinking is that if I specify `{node: true}`, I want it. Letting `echo example` work then may even cover up a mistake that should ideally fail loudly. And what if the file is called `echo.js`? Node.js allows executing without specifying extension.

**Comment by ehmicky** [comment]
Yes, that's a good point about the file extensions.

Let's close this then. :+1:
