### ISSUE TITLE
$ escape breaks the command that is stored as a variable

### ISSUE THREAD

**Issue by bigBellyBlow** [sindresorhus/execa#902]
in case I have a command like

```js
const command = `node tests.js --config`
await $`${command}`
```

then it throws ENOENT node ... on Linux and MAC but works on windows. 

same command without variable works fine on all OSs

```js
await $`node tests.js --config`
``` 

This is a simple example of a much complicated script that use any number of arguments that should follow in specific order

**Comment by ehmicky** [comment]
Hi @bigBellyBlow,

Any value passed to `${...}` is fully escaped. Spaces are not considered delimiters. So in your example, Execa is trying to run a binary named `node tests.js --config`, which it cannot find, which produces `ENOENT`.

If you want both the file and its arguments are dynamic (e.g. they are supplied by users), [`execaCommand()`](https://github.com/sindresorhus/execa?tab=readme-ov-file#execacommandcommand-options) should be used instead.

> This is the preferred method when executing a user-supplied command string, such as in a REPL.

```js
const command = `node tests.js --config`
await execaCommand(command)
```

**Comment by bigBellyBlow** [comment]
> Hi @bigBellyBlow,
> 
> Any value passed to `${...}` is fully escaped. Spaces are not considered delimiters. This protects you from shell injections. This also enables running commands which have spaces in their name or file path.
> 
> So in your example, Execa is trying to run an executable file named `"node tests.js --config"`, which it cannot find, which produces `ENOENT`.
> 
> However, Execa does provide with a way to run commands where both the file and its arguments are dynamic (e.g. they are supplied by users): [`execaCommand()`](https://github.com/sindresorhus/execa?tab=readme-ov-file#execacommandcommand-options).
> 
> > This is the preferred method when executing a user-supplied command string, such as in a REPL.
> 
> ```js
> const command = `node tests.js --config`
> await execaCommand(command)
> ```
> 
> Alternatively, if the command or arguments are dynamic, but are an array of values (as opposed to a single string combining both), `$` can be used. This is preferred over `execaCommand()`, but is not always possible depending on your case.
> 
> ```js
> const file = 'node'
> const arguments = ['tests.js', '--config']
> await $`${file} ${arguments}`
> ```

Thank you, it does work, I did not try it because its documentation stated it still escape characters and to make it work, I need to escape whitespace. 

> Arguments are [automatically escaped](https://www.npmjs.com/package/execa#shell-syntax). They can contain any character, but spaces must be escaped with a backslash like execaCommand('echo has\\ space').

Did I get it wrong? Anyways I believe my issue is resolved and if you want me

**Comment by ehmicky** [comment]
Great! :+1:
