### ISSUE TITLE
Rename `from: 3` option to `from: 'fd3'`.

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/execa#918]
The `subprocess.readable|writable|duplex()` and `subprocess.pipe()` have a `from` and `to` options to select a custom file descriptor. Those default to `'stdout'` and `'stdin'`. They can also be set to `'stderr'`, `'all'` or a file descriptor number.

Instead of a file descriptor number, the option value should probably be `'fd...'` like `'fd3'`.

This might be clearer. Also, the file descriptor number is used as a name, not an arithmetic value, so a string might be more proper. Finally, it makes the type simpler: `enum` instead of `enum | number`.

This is not a breaking change since the options above have not been released yet.

What do you think?

**Comment by sindresorhus** [comment]
I agree. It's not a common use-case anyway.
