### ISSUE TITLE
Official example not working

### ISSUE THREAD

**Issue by shirohana** [sindresorhus/execa#946]
I'm trying `execa@8.0.1` with the [official example](https://github.com/sindresorhus/execa/blob/main/readme.md#globalshared-options), but it doesn't work.

> ### Global/shared options
> 
> ```ts
> import {execa as execa_} from 'execa';
> 
> const execa = execa_({verbose: 'full'});
> 
> await execa('echo', ['unicorns']);
> //=> 'unicorns'
> ```

and I got the following error:

```sh
❯ node run.mjs
file:///Users/shirohana/try-execa/run.mjs:5
await execa('echo', ['unicorns']);
      ^

TypeError: execa is not a function
    at file:///Users/shirohana/try-execa/run.mjs:5:7
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.10.0
```

**Comment by ehmicky** [comment]
Hi @shirohana,

This feature has not been released yet. It should be released in a few weeks.

In the meantime, you can see the `8.0.1` documentation [here](https://github.com/sindresorhus/execa/tree/v8.0.1).

**Comment by shirohana** [comment]
Got it, sorry for bothering you.

By the way, excuse me, the latest release was 7 months ago, can I find the milestone or roadmap somewhere?

**Comment by ehmicky** [comment]
We are not using a milestone nor roadmap.
However, we are almost done with this release.

**Comment by ehmicky** [comment]
Execa 9.0.0 has now been released. Please see (and share!) the [release post](https://medium.com/@ehmicky/execa-9-release-d0d5daaa097f) and the [changelog](https://github.com/sindresorhus/execa/releases/tag/v9.0.0).
