### ISSUE TITLE
shellSync error should also return stdout

### ISSUE THREAD

**Issue by vibl** [sindresorhus/execa#98]
When throwing an error, `execa.shellSync` seems to return the error message as a string.

IMO it should also return stdout, as programs can return both stdout and stderr (for example `ls ; cat does-not-exist.txt`)

FWIW, that's `child_process.execSync()` behavior.

**Comment by sindresorhus** [comment]
Agreed, we should ensure it's always an error with `stdout` and `stderr` attached as properties, just like the async version. This also applies to `execa.sync()`.

**Comment by vibl** [comment]
Cool :-)

Also, it would be nice if error handling were optional.

Personally, I would get rid of throwing errors altogether: I'm guessing most users want to pipe their process output in a Unix way as much as possible, without having to `try {} catch {}` all the time.

I have forked and commented out all `throw` in Execa. It's now a breeze to be use, especially with Ramda.pipe and Ramda.pipeP.

**Comment by sindresorhus** [comment]
> I'm guessing most users want to pipe their process output in a Unix way as much as possible, without having to `try {} catch {}` all the time.

From experience, most people want it to throw so it doesn't fail silently by mistake. I'm open to adding an option to not throw though. We already have the `reject` option for the async methods, wonder if there's any way we could consolidate with one option for both async and sync.
