### ISSUE TITLE
Question about next release

### ISSUE THREAD

**Issue by knjshimi** [sindresorhus/execa#986]
Hi guys!

First of all, huge thanks to all contributors here for Execa. It's an essential part of a cli tool that I built and use everyday.

I noticed that new commits are being pushed constantly for a while now, and the latest release happened a while ago.

Do you have a plan or date for when the next release is going to be publicly available?

Thank you heaps!

**Comment by ehmicky** [comment]
Hi @knjshimi,

Thanks a lot!

We're adding a few more last PRs. We do not have a plan or date for the upcoming release, but it should be in the coming weeks.

**Comment by ehmicky** [comment]
Execa 9.0.0 has now been released. Please see (and share!) the [release post](https://medium.com/@ehmicky/execa-9-release-d0d5daaa097f) and the [changelog](https://github.com/sindresorhus/execa/releases/tag/v9.0.0).

**Comment by knjshimi** [comment]
> Execa 9.0.0 has now been released. Please see (and share!) the [release post](https://medium.com/@ehmicky/execa-9-release-d0d5daaa097f) and the [changelog](https://github.com/sindresorhus/execa/releases/tag/v9.0.0).

Oh I saw that! Reading it now, thanks @ehmicky and great work team!
